- config/locales/es-MX.yml
didn't found it on TranslateWiki
> minor translation

- app/helpers/taxa_helper.rb
- app/models/project_list.rb
- app/views/guide_taxa/show.html.haml
- app/views/identifications/by_login.html.erb
- app/views/messages/new.html.haml
- app/views/posts/new.html.haml
- app/views/users/_show.html.erb
- app/views/welcome/_index.html.erb
- config/locales/en.yml
- config/locales/fr.yml
Hi @kueda,
Thanks for the previous merge. Here's more commits that would be great to merge before the official launch.
Thanks!
> Improve french translations - pt. 2

- config/locales/fr.yml
-- Repost of #592 against the `i18n` branch --
Hi @kueda
Some more translations that can hopefully make it before the deployment. Special thanks to @loarie for bringing up a few of them!
Thanks!
> Improve french translations - pt. 3

- app/views/lists/by_login.html.erb
- app/views/lists/new.html.erb
- app/views/lists/show.html.erb
- app/views/projects/by_login.html.erb
- app/views/shared/_header.html.haml
- config/locales/en.yml
- config/locales/fr.yml
One more! Should be good to go for the launch.
Thanks!
> Improve french translations - pt. 4

- app/controllers/observations_controller.rb
- app/helpers/observations_helper.rb
- app/views/observations/_observation_component.html.erb
- app/views/observations/show.html.erb
- config/locales/es.yml
> Locale- and place-specific taxon names where we used to show species_guess

- app/views/projects/show.html.erb
> added date display for 24-hour bioblitz scenario

- app/views/facebook/index.html.haml
I think this is what is preventing our FB app from being approved
> added FB js to facebook canvas endpoint

- config/routes.rb
hoping this will fix our broken FB canvas page
> added POST route for facebook

- app/assets/javascripts/guide_taxa/edit.js
- app/assets/javascripts/guides/show.js
- app/assets/stylesheets/guides/show.css
- app/controllers/guide_taxa_controller.rb
- app/controllers/guides_controller.rb
- app/models/guide.rb
- app/models/guide_photo.rb
- app/models/guide_taxon.rb
- app/views/guide_taxa/_guide_photo_fields.html.haml
- app/views/guide_taxa/_guide_taxon.xml.builder
- app/views/guides/show.html.haml
- config/locales/en.yml
- lib/meta_service.rb
Closes #542 
* allows guide photos to be tagged
* adds UI to choose what tagged images to show when viewing a guide on the web
* includes photo tags in XML responses so they can be used in the apps
> Guide photo tags

- Gemfile
- Gemfile.lock
- app/models/local_photo.rb
- lib/tasks/inaturalist.rake
- spec/models/local_photo_spec.rb
> Image dimensions

- app/es_indices/observation_index.rb
- lib/darwin_core/archive.rb
- lib/observation_search.rb
- spec/controllers/observation_controller_api_spec.rb
- spec/lib/darwin_core/archive_spec.rb
@pleary, can you take a look at this? I had to change some parts of elastic_query and related methods. Specs seem to pass, but wanted to run this by you all the same.
> Added min_id obs API param, ability to page by min_id and limit.

- app/es_indices/observation_index.rb
- app/es_indices/taxon_index.rb
- app/models/conservation_status.rb
- app/models/observation.rb
- app/views/observations/_filter_fields.html.erb
- db/migrate/20151030205931_add_mappings_to_observations_index.rb
- lib/elastic_model/elastic_model.rb
- spec/controllers/observation_controller_api_spec.rb
- spec/controllers/users_controller_api_spec.rb
- spec/lib/acts_as_spammable/active_record_spec.rb
- spec/lib/elastic_model/indices/observation_index_spec.rb
- spec/models/identification_spec.rb
> more observation API params 

- tools/apidoc/api.rb
> spelling fix for api docs

- app/models/place.rb
- app/views/places/edit.html.haml
I believe its now no longer possible for users to set admin_level on places
> removed admin_level UI from places edit

- app/assets/javascripts/jquery/plugins/inat/taxon_autocomplete.js.erb
- app/es_indices/observation_index.rb
- app/es_indices/place_index.rb
- app/es_indices/taxon_index.rb
- app/models/comment.rb
- app/models/identification.rb
- app/models/listed_taxon.rb
- app/models/observation.rb
- app/models/photo.rb
- app/models/place_geometry.rb
- app/models/place_taxon_name.rb
- app/models/taxon.rb
- app/models/taxon_name.rb
- db/migrate/20151228144302_edit_observations_index_mapping.rb
- lib/elastic_model/elastic_model.rb
- lib/observation_search.rb
- spec/lib/elastic_model/indices/observation_index_spec.rb
code from the observations-search branch needed to prepare the ES indices for the new features. The changes are mostly additions. taxon.default_photo_url was turned into a taxon.default_photo object, so there is one change to taxon autocomplete to accept either value from the node API
> Search transition

- Gemfile.lock
- config/locales/en.yml
trivial change - mostly wanted to test making commits from this new VB setup
> semantics change for still_needs_id

- app/controllers/places_controller.rb
- app/models/place.rb
attempt to keep standard places from changing
> only admins can edit places with admin_level not nil

- app/assets/stylesheets/observations.css.scss
- app/views/observations/show.html.erb
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
- db/structure.sql
added placeholder Dir1 from https://github.com/inaturalist/inaturalist/issues/921 also #946 typo and minor Spanish translation
> placeholder to obs.show and 2 minor typo/translation fixes

- app/controllers/complete_sets_controller.rb
- app/controllers/exploded_atlas_places_controller.rb
- app/models/listed_taxon.rb
- app/views/atlases/_form_fields.html.haml
- app/views/atlases/edit.html.haml
- app/views/atlases/show.html.haml
- app/views/complete_sets/_form_fields.html.haml
- app/views/complete_sets/edit.html.haml
- app/views/complete_sets/show.html.haml
- db/migrate/20170110025430_add_is_active_to_atlases.rb
- db/migrate/20170110025450_add_is_active_to_complete_sets.rb
- db/structure.sql
- spec/controllers/listed_taxa_controller_api_spec.rb
- spec/models/listed_taxon_spec.rb
added is_active to atlases and complete_sets, only log when active
> Complete sets

- app/controllers/controlled_terms_controller.rb
- app/controllers/taxa_controller.rb
- app/es_indices/controlled_term_index.rb
- app/models/controlled_term.rb
- app/webpack/taxa/photos/components/photo_browser.jsx
- app/webpack/taxa/photos/containers/photo_browser_container.js
- app/webpack/taxa/photos/containers/place_chooser_container.js
- app/webpack/taxa/photos/ducks/photos.js
- app/webpack/taxa/photos/webpack-entry.js
- app/webpack/taxa/shared/ducks/taxon.js
- app/webpack/taxa/show/actions/taxon.js
- app/webpack/taxa/show/components/charts.jsx
- app/webpack/taxa/show/components/taxonomy_tab.jsx
- app/webpack/taxa/show/containers/charts_container.js
- app/webpack/taxa/show/containers/place_chooser_container.js
- app/webpack/taxa/show/containers/taxonomy_tab_container.js
- app/webpack/taxa/show/ducks/leaders.js
- app/webpack/taxa/show/ducks/observations.js
- app/webpack/taxa/show/webpack-entry.js
- npm-shrinkwrap.json
Use controlled terms instead of observation fields on the taxon page.
> Taxon Page Controlled Terms

- app/models/identification.rb
- app/models/taxon_change.rb
- spec/models/identification_spec.rb
- spec/models/taxon_merge_spec.rb
- spec/models/taxon_swap_spec.rb
A couple small tweaks to pre-load some more data while committing records for taxon changes, particularly identifications.
> 721 taxon change performance

- app/assets/stylesheets/observations/identify.css.scss
- app/assets/stylesheets/observations/identify/blind.css.scss
- app/models/identification.rb
- app/webpack/observations/identify/actions/identification_actions.js
- app/webpack/observations/identify/actions/observations_actions.js
- app/webpack/observations/identify/components/app.jsx
- app/webpack/observations/identify/components/discussion_list_item.jsx
- app/webpack/observations/identify/components/identification_form.jsx
- app/webpack/observations/identify/components/observation_modal.jsx
- app/webpack/observations/identify/components/side_bar.jsx
- app/webpack/observations/identify/containers/app_container.js
- app/webpack/observations/identify/containers/identification_form_container.js
- app/webpack/observations/identify/containers/observation_modal_container.js
- app/webpack/observations/identify/reducers/search_params_reducer.js
- app/webpack/observations/identify/webpack-entry.js
- db/migrate/20170317183900_add_blind_cols_to_identifications.rb
- db/structure.sql
- spec/models/identification_spec.rb
Experimental version of Identify that hides most of the social cues.
> blind identify

- app/assets/stylesheets/projects/stats_slideshow.css.scss
- app/controllers/stats_controller.rb
- app/views/stats/project_slideshow.html.haml
- app/webpack/project_slideshow/components/project_map.js
- app/webpack/project_slideshow/components/slideshow.js
- app/webpack/project_slideshow/models/util.js
- app/webpack/project_slideshow/reducers/index.js
- config/routes.rb
Adapted the NPS jumbotron slideshow for the City Nature Challenge.
> CNC slideshows

- app/controllers/welcome_controller.rb
- app/views/welcome/index.html.haml
> restores welcome/index announcements

- app/controllers/identifications_controller.rb
- app/controllers/observations_controller.rb
- app/es_indices/identification_index.rb
- app/es_indices/observation_index.rb
- app/models/identification.rb
- app/models/observation.rb
- spec/controllers/identifications_controller_api_spec.rb
- spec/controllers/observation_controller_api_spec.rb
- spec/lib/elastic_model/indices/observation_index_spec.rb
Kind of wimped out and went with the preference approach. I figure if it becomes problematic we can convert to a column on identifications later. Mostly concerned with performance implications for indexing.
> Record whether or not identifications come from vision (#1393)

- app/controllers/flags_controller.rb
- app/controllers/identifications_controller.rb
- app/controllers/project_observations_controller.rb
- app/es_indices/identification_index.rb
- app/es_indices/observation_index.rb
- app/models/annotation.rb
- app/models/comment.rb
- app/models/identification.rb
- app/models/observation_field_value.rb
- app/models/photo.rb
- app/models/project_observation.rb
- app/models/quality_metric.rb
- app/models/sound.rb
- app/models/user.rb
- config/initializers/acts_as_votable.rb
- db/migrate/20170710150124_add_to_observations_index.rb
- db/migrate/20170710211319_add_to_ids_index.rb
- db/structure.sql
- lib/acts_as_flaggable/flag.rb
- spec/lib/elastic_model/indices/observation_index_spec.rb
- add new fields to obs/IDs index
- change non_owner_ids to identifications with own_observation attribute
- change identifiers ES query to look at both non_owner_ids and identifications, so queries work while re-indexing
> Obs index changes

- app/assets/javascripts/i18n/translations.js
- app/assets/stylesheets/observations/identify/observation_modal.css.scss
- app/assets/stylesheets/observations/identify/suggestions.css.scss
- app/webpack/observations/identify/components/chooser_popover.jsx
- app/webpack/observations/identify/components/suggestions.jsx
- app/webpack/observations/identify/ducks/suggestions.js
- app/webpack/taxa/shared/components/place_chooser_popover.jsx
- config/locales/en.yml
- npm-shrinkwrap.json
- package.json
Add visions results as a source for suggestions on Identify.
> Visual suggestions

- app/models/project.rb
Something like the following to update the data:
```ruby
start = Time.now
updated = 0
test = true
Project.find_each do |project|
puts project.id
icon = Dir["#{Rails.root}/public/attachments/projects/icons/#{project.id}/original/*"].first
if icon.present?
project.update( icon: File.open( icon ) ) unless test
updated += 1
puts "\tuploading"
else
puts "\tno icon"
end
end
puts
puts "Updated #{updated} projects in #{Time.now - start}s"
puts
```
> Move project icons to s3.

- app/controllers/announcements_controller.rb
- app/models/announcement.rb
- app/models/local_photo.rb
- app/views/announcements/_form.html.erb
- app/views/announcements/index.html.haml
- lib/paperclip_processors/metadata_filter.rb
Closes #1493, continues to remove EXIF and IPTC tags from photos while preserving color profiles. Uh, and apparently I put some small updates to annotations in there.
> Preserve color profiles

- app/assets/javascripts/jquery/plugins/inat/taxon_autocomplete.js.erb
- app/controllers/taxa_controller.rb
- app/controllers/users_controller.rb
- app/helpers/taxa_helper.rb
- app/models/taxon_name.rb
- app/models/user.rb
- app/views/guides/_guide_taxa.html.erb
- app/views/layouts/application.html.erb
- app/views/layouts/basic.html.haml
- app/views/observations/show2.html.haml
- app/views/users/edit.html.erb
- config/locales/en.yml
- config/locales/es.yml
- lib/inat_api_service.rb
- package-lock.json
> Opt out of common names

- app/assets/stylesheets/observations/identify/suggestions.css.scss
- app/webpack/observations/identify/components/suggestions.jsx
- app/webpack/observations/identify/containers/suggestions_container.js
> Added prev next buttons to suggestions on Identify

- db/migrate/20180109232530_add_user_observation_index_to_identifications.rb
- db/structure.sql
Closes #1491 (or it should, at least)
> Prevent Multiple Current IDs

- app/models/identification.rb
- app/models/observation.rb
- spec/models/taxon_merge_spec.rb
- spec/models/taxon_split_spec.rb
- spec/models/taxon_swap_spec.rb
> Avoid most disagreements when generating IDs from taxon changes

- config/locales/br.yml
- config/locales/es.yml
- config/locales/fi.yml
- config/locales/fr.yml
- config/locales/it.yml
- config/locales/lb.yml
- config/locales/oc.yml
- config/locales/qqq.yml
- config/locales/ru.yml
- config/locales/zh-CN.yml
- config/locales/zh-TW.yml
> Translatewiki updates for 19 Jan 2018

- app/models/observation.rb
- spec/models/observation_spec.rb
> Removed conservative_non_disagreement_count in attempt to fix #1682

- app/models/emailer.rb
- app/views/emailer/custom_email.html.haml
Created a custom email method on emailer so we write scripts that send emails from iNat staff to users for administration purposes.
> Custom email method on emailer

- app/controllers/atlases_controller.rb
- app/models/atlas.rb
- app/models/taxon.rb
essentially involved adding geoprivacy=open,obscured in a few places
> made it so atlases ignore obs with geoprivacy = private

- config/locales/ar.yml
- config/locales/bg.yml
- config/locales/de.yml
- config/locales/el.yml
- config/locales/es-MX.yml
- config/locales/es.yml
- config/locales/fr.yml
- config/locales/it.yml
- config/locales/ja.yml
- config/locales/ko.yml
- config/locales/pt-BR.yml
- config/locales/pt-PT.yml
- config/locales/qqq.yml
- config/locales/ru.yml
- config/locales/zh-CN.yml
- config/locales/zh-TW.yml
Want to make sure high visibility stuff in the header gets released sooner rather than later.
> Translatewiki update for 10 May 2018

- app/models/deleted_sound.rb
- app/models/observation_sound.rb
- app/models/sound.rb
- app/models/user.rb
- db/migrate/20180504213719_create_deleted_sounds.rb
- db/structure.sql
- lib/tasks/inaturalist.rake
- spec/models/observation_spec.rb
- spec/models/sound_spec.rb
This definitely needs a look-over before merging. Basically replicated DeletedPhoto for sounds (which we're currently not deleting at all?), but also revises how we clean up photo and sound files on S3, which I think might have been broken for a while.
Will close #1751
> Added DeletedSound, updated rake tasks to work with newish Aws gem

- app/models/observation.rb
- app/views/observations/export.html.haml
- config/locales/en.yml
- lib/elastic_model/acts_as_elastic_model.rb
- spec/models/place_spec.rb
> Add admin level names in export

- app/controllers/projects_controller.rb
- app/models/project.rb
- spec/models/project_spec.rb
Closes #1770 and #1778, still need to test on staging, query might not be all that great.
> Use project observation rule places when fetching projects for a place.

- app/assets/javascripts/ang/controllers/observation_search.js
- app/assets/javascripts/ang/inaturalist_angular.js
- app/assets/javascripts/inaturalist/map3.js.erb
- app/assets/javascripts/jquery/plugins/inat/taxonmap.js.erb
- app/assets/javascripts/wax.g.js
- app/assets/stylesheets/index.css.scss
- app/helpers/application_helper.rb
- app/webpack/projects/show/util.js
- app/webpack/taxa/show/components/taxon_page_map.jsx
- app/webpack/taxa/show/containers/highlights_tab_container.js
- config/locales/en.yml
- tools/taxa_from_csv.rb
> Use latest google maps renderer

- app/models/user.rb
- config/config.yml.example
Adds a method to destroy the user but also several others sources of data, including:
* DeletedUser
* DeletedObservation
* DeletedPhoto
* DeletedSound
* S3 photos
* S3 sounds
* Logstash activity (requires an additional config)
> Forget user

- app/assets/javascripts/inaturalist/map3.js.erb
- app/assets/javascripts/jquery/plugins/inat/taxonmap.js.erb
- app/assets/stylesheets/observations/identify/observation_modal.css.scss
- app/assets/stylesheets/observations/identify/suggestions.css.scss
- app/assets/stylesheets/observations/show2.scss
- app/assets/stylesheets/shared/taxonomic_branch.scss
- app/assets/stylesheets/taxa/show2.css.scss
- app/webpack/observations/identify/components/suggestions.jsx
- app/webpack/observations/identify/containers/suggestions_container.js
- app/webpack/observations/identify/ducks/suggestions.js
- app/webpack/observations/show/components/community_identification.jsx
- app/webpack/shared/components/cover_image.jsx
- app/webpack/shared/components/split_taxon.jsx
- app/webpack/shared/components/taxonomic_branch.jsx
- app/webpack/taxa/shared/components/taxon_photo.jsx
- app/webpack/taxa/show/components/taxonomy_tab.jsx
* Maps in suggestions list
* Place option removed when viewing vision results
* Link icons by taxon names
* Taxonomy on detail view
* Place chooser defaults to admin level places
> Updates to Suggestions UI

- app/controllers/taxon_changes_controller.rb
- app/models/taxon_change.rb
- spec/models/taxon_swap_spec.rb
> added rank level conflict check to taxon swap commit

- app/assets/stylesheets/wiki.css
- app/models/taxon_change.rb
- app/views/taxon_changes/_form.html.erb
- app/views/taxon_changes/_show_change_taxon.html.haml
- config/locales/en.yml
- db/migrate/20180906232956_add_move_children_to_taxon_changes.rb
- db/structure.sql
- lib/ratatosk/lib/ratatosk.rb
- lib/ratatosk/spec/ratatosk_spec.rb
- spec/models/taxon_merge_spec.rb
- spec/models/taxon_swap_spec.rb
made it so that complete taxa prevent automatic grafting by ratatosk
> Ratatosk proof complete taxa

- app/views/taxon_changes/_show_change_taxon.html.haml
- spec/models/taxon_swap_spec.rb
> Opt-in to move input children to output

- app/helpers/application_helper.rb
- app/views/emailer/_footer.html.erb
- app/views/shared/_footer.html.haml
- config/locales/en.yml
- config/locales/es.yml
- config/locales/fr.yml
- config/locales/pt-BR.yml
- config/locales/pt-PT.yml
These changes make it so if you're on a network site the bottom homepage footer has the 'joint initiative' statement and the email now has a similar bottom footer. If you're on the iNat site, only difference is email now has the Nat Geo logo
> Footer branding

- app/models/observation.rb
- spec/models/observation_spec.rb
> Allow obs to be voted out of NID if observer has opted out of CID

- app/assets/stylesheets/colors.css.scss
- app/assets/stylesheets/donate.scss
- app/assets/stylesheets/index.css.scss
- app/assets/stylesheets/responsive.scss
- app/assets/stylesheets/users/registrations.scss
- app/controllers/donate_controller.rb
- app/views/donate/index.html.haml
- app/views/emailer/_footer.html.erb
- app/views/shared/_footer.html.haml
- config/locales/en.yml
- config/locales/qqq.yml
- config/routes.rb
- test/mailers/previews/emailer_preview.rb
Adds a page where people can donate money to iNaturalist (#2049), donate button currently only visible to staff.
> Donate page

- app/controllers/comments_controller.rb
- app/controllers/guide_sections_controller.rb
- app/controllers/guide_taxa_controller.rb
- app/controllers/guides_controller.rb
- app/controllers/identifications_controller.rb
- app/controllers/lists_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/observations_controller.rb
- app/controllers/posts_controller.rb
- app/controllers/projects_controller.rb
- app/controllers/users_controller.rb
- lib/acts_as_spammable/action_controller/base.rb
- lib/acts_as_spammable/active_record/base.rb
- spec/models/user_spec.rb
Uses information from requests to get better responses from Akismet.
> Akismet fixes

- app/webpack/observations/uploader/components/location_chooser.js
- app/webpack/observations/uploader/components/location_chooser_map.jsx
Fixes #1908, in which entering coordinates into the Google Search would search Google for places and use the coordinates associated with the Google place instead of the coordinates entered by the user.
> Search for coordinates

- app/assets/stylesheets/observations/identify.css.scss
- app/assets/stylesheets/observations/identify/observation_modal.css.scss
- app/assets/stylesheets/observations/show2.scss
- app/assets/stylesheets/shared/full_screen_modal.scss
- app/assets/stylesheets/taxa/show2.css.scss
- app/controllers/taxa_controller.rb
- app/webpack/observations/identify/components/observation_modal.jsx
- app/webpack/taxa/show/components/photo_chooser_modal.jsx
a few minor changes with taxon_frameworks
> Make taxon photo chooser modal fill height of screen (closes #2085)

- app/controllers/taxa_controller.rb
- app/controllers/taxon_curators_controller.rb
- app/controllers/taxon_framework_relationships_controller.rb
- app/models/external_taxon.rb
- app/models/project.rb
- app/models/taxon.rb
- app/models/taxon_change.rb
- app/models/taxon_framework_relationship.rb
- app/views/taxon_changes/show.html.haml
- app/webpack/shared/components/taxonomic_branch.jsx
- spec/models/taxon_framework_relationship_spec.rb
- spec/models/taxon_spec.rb
- spec/models/taxon_swap_spec.rb
some fixes for taxon frameworks
> Taxon concepts

- app/views/emailer/_header.html.erb
- app/views/emailer/new_message.html.haml
- app/views/emailer/updates_notification.html.erb
> Custom fonts in email

- app/assets/javascripts/jquery/plugins/inat/universal_autocomplete.js.erb
- app/assets/stylesheets/index.scss
- app/views/shared/_header.html.haml
An attempt to make this useful tool more obvious.
> Green header search button

- app/helpers/application_helper.rb
- app/models/taxon.rb
- app/views/taxon_changes/_update_committed.html.haml
- app/views/taxon_changes/_update_email_committed.html.haml
- app/views/taxon_changes/show.html.haml
- config/locales/en.yml
- spec/models/taxon_spec.rb
> Synonymous taxa for inactive outputs

- app/assets/javascripts/ang/templates/observation_search/results_grid.html.haml
- app/assets/stylesheets/observations/search.css
- app/assets/stylesheets/observations/search.scss
- app/assets/stylesheets/shared/observations_grid_item.scss
- app/webpack/shared/components/observations_grid_item.jsx
Changes to obs search and Identify.
> Different design for photo counts in obs grid and list

- app/assets/javascripts/users/registrations.js
- app/assets/stylesheets/bootstrap-inat.css
- app/assets/stylesheets/donate.scss
- app/assets/stylesheets/donorbox-iframe.scss
- app/assets/stylesheets/user_parents.scss
- app/assets/stylesheets/users/registrations.scss
- app/controllers/user_parents_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/emailer.rb
- app/models/user.rb
- app/models/user_parent.rb
- app/views/emailer/parental_consent.html.haml
- app/views/emailer/user_parent_confirmation.html.haml
- app/views/layouts/registrations.html.haml
- app/views/user_parents/confirm.html.haml
- app/views/user_parents/new.html.haml
- app/views/users/_license_fields.html.erb
- app/views/users/registrations/_form.html.haml
- app/views/users/registrations/new.html.haml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20190514191221_add_birthday_to_users.rb
- db/migrate/20190514192302_create_user_parents.rb
- db/migrate/20190516011313_add_pi_consent_at_to_users.rb
- db/migrate/20190516181748_add_donor_verified_columns.rb
- db/structure.sql
- spec/blueprints.rb
- spec/models/user_parent_spec.rb
- test/mailers/previews/emailer_preview.rb
- tools/donorbox.rb
Allows a parent to provide consent for their child to use iNat, and verify their identity with a credit card payment.
Closes #2264, #2251, #2250, and #2249.
> Parent child authorization flow

- app/assets/javascripts/ang/controllers/observation_search.js
- app/assets/javascripts/application.js.erb
- app/assets/javascripts/inaturalist/map3.js.erb
- app/assets/javascripts/jquery/plugins/inat/taxonmap.js.erb
- app/helpers/application_helper.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/layouts/basic.html.haml
- app/views/layouts/bootstrap.html.erb
- app/views/observations/show.html.haml
- app/views/places/index.html.erb
- app/views/places/new.html.erb
- app/views/projects/show2.html.haml
- app/webpack/.eslintrc
- app/webpack/observations/compare/components/map_comparison.jsx
- app/webpack/observations/compare/containers/map_comparison_container.js
- app/webpack/observations/identify/components/observation_modal.jsx
- app/webpack/observations/identify/components/suggestion_row.jsx
- app/webpack/observations/identify/components/suggestions.jsx
- app/webpack/observations/show/components/map.jsx
- app/webpack/observations/uploader/components/location_chooser_map.jsx
- app/webpack/projects/show/components/before_event_tab.jsx
- app/webpack/projects/show/components/observations_map_view.jsx
- app/webpack/projects/show/components/observations_tab.jsx
- app/webpack/projects/show/components/overview_map.jsx
- app/webpack/projects/show/components/overview_tab.jsx
- app/webpack/projects/show/components/umbrella_map.jsx
- app/webpack/taxa/show/components/taxon_page_map.jsx
- config/locales/en.yml
- config/locales/es-ES.yml
Use map type preference on most maps across the site. Closes #2305.
> Sticky map type

- Gemfile
- Gemfile.lock
- app/controllers/oauth_authorizations_controller.rb
- app/views/doorkeeper/authorizations/new.html.haml
- app/views/oauth_applications/_form.html.haml
- app/views/oauth_applications/index.html.haml
- app/views/oauth_applications/show.html.haml
- config/application.rb
- db/migrate/20190702063435_enable_pkce.rb
- db/structure.sql
Following on from https://github.com/inaturalist/inaturalist/pull/2309, I present a PR that enables the PKCE flow for iNat.
The changes that I made:
1. add the DB migration that DoorKeeper requires
1. enable CORS for the endpoint that clients need access to
1. set the `@responsive` flag for the authorize view so it renders a bit nicer on a mobile screen.
1. ensure that the PKCE query params are passed through the authorize screen
1. add a column to the list of OAuth applications to show the confidential flag
1. add a control to set/view the confidential flag on an OAuth application and add an example link that performs the first part of the PKCE flow
In the course of doing this, I found two things that are now on our wish list:
1. the authorize screen is now "responsive" but that really …
> feat: add support for the authorization code with PKCE OAuth flow

- app/helpers/bootstrap_form_builder.rb
- app/views/taxon_frameworks/_form.html.haml
- lib/darwin_core/archive.rb
- lib/darwin_core/occurrence.rb
- lib/darwin_core/simple_multimedia.rb
Closes #2344. Note that this renames the CSV file we use for photos from `images.csv` to `media.csv`and that file now includes sounds.
> Sounds in DwC-A

- app/models/observation.rb
- app/models/project.rb
- app/views/flags/global_index.html.haml
- app/views/flags/show.html.haml
- app/webpack/projects/form/components/regular_form.jsx
- app/webpack/projects/form/form_reducer.js
- app/webpack/projects/show/components/about.jsx
- app/webpack/projects/show/components/requirements.jsx
- config/locales/en.yml
- lib/tasks/inaturalist.rake
> Project quality grade pref

- app/views/lists/_tools.html.erb
Provides the switched order of tools described in [Issue 2425](https://github.com/inaturalist/inaturalist/issues/2425)
> Switches order of List tools, Issue #2425

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/layouts/bootstrap.html.erb
- app/views/users/edit.html.erb
- config/locales/en.yml
1. Prompts users of iNat to join a member site if they are viewing the site from a place associated with that site
1. Prompts users of other network sites to join the network site affiliated with the place they're viewing that site from (e.g. if you're viewing ArgentiNat from Australia, you get a prompt to join iNaturalist.AU)
Closes #2492
> Network Affiliation Prompt

- app/assets/javascripts/taxon_framework_relationships/taxon_framework_relationships.js
- app/assets/stylesheets/taxon_framework_relationships/taxon_framework_relationships.scss
- app/models/taxon.rb
- app/models/taxon_framework_relationship.rb
- app/views/taxon_framework_relationships/_show_taxon_framework_relationship.html.haml
Some changes to the display of taxon framework relationships, a bug fix in coverage by taxon frameworks, and a change to what constitutes relationship=match
> Tfr changes

- app/models/identification.rb
- app/models/observation.rb
Minor changes to how we update observations after adding identifications. I'm pretty sure observations were not always getting indexed, and obs stats were not always getting updated. It remains a fairly brittle area.
> Ident obs indexing

- app/webpack/projects/show/components/before_event_tab.jsx
#2673
Add flag link to project before_event_tab component
New around here, but I didn't see anything like `mocha` or `jest` so just from some local click testing, this seems to operate fine.
> Add flag link to project before_event_tab component

- app/views/users/search.html.haml
- config/locales/en.yml
> fix(people/search) : 'or email' placeholder removed #2753

- README.textile
- app/helpers/application_helper.rb
- app/views/emailer/_footer.html.erb
- app/views/shared/_footer.html.haml
- app/views/users/edit.html.erb
> Update network page link to sites

- app/webpack/observations/uploader/actions/actions.js
- config/locales/en.yml
#2779 
Updates submit check in obs uploader to check for either no photos OR no taxon name (or species guess)
> Add warning to obs uploader

- app/controllers/users_controller.rb
#2817 
Update post counts on followers and following user tables. Also remove
unused assignment of post counts for user search table.
> Update post counts

- db/migrate/20201023174221_add_index_to_identifications_taxon_id.rb
- db/structure.sql
> Add index to identifications taxon_id

- app/views/users/_glance.html.erb
- app/views/users/_subnav_bootstrap.html.haml
Updates links with params for verifiable any and place any
#2815
> Update user obs links

- app/assets/javascripts/jquery/plugins/inat/universal_autocomplete.js.erb
- app/views/users/_glance.html.erb
- app/views/users/_subnav_bootstrap.html.haml
#2815
Handles additional user obs path update, make params consistent.
> Update user obs path

- app/es_indices/observation_index.rb
- lib/data_partner_linkers/gbif.rb
- lib/elastic_model/acts_as_elastic_model.rb
- spec/models/taxon_stage_spec.rb
- tools/gbif_observation_links.rb
Also
* allows models to specify an amount of time to sleep between index batches
* minor updates to GBIF obs link script
> Lower the default obs batch index size

- app/controllers/curator_applications_controller.rb
- app/models/emailer.rb
- app/views/curator_applications/new.html.haml
- app/views/emailer/curator_application.html.haml
- app/views/messages/show.html.haml
- config/locales/en.yml
- config/routes.rb
- test/mailers/previews/emailer_preview.rb
Adds a form people can fill out to apply to be a site curator. Closes #2932
> Curator Application

- app/assets/stylesheets/taxa/show.scss
- app/webpack/taxa/photos/containers/place_chooser_container.js
- app/webpack/taxa/shared/components/place_chooser_popover.jsx
- app/webpack/taxa/show/components/app.jsx
- config/locales/en.yml
Tried to make it more obvious when a place has been chosen on taxon detail pages.
> Taxon detail place chooser

- app/controllers/comments_controller.rb
- app/views/comments/_listing_for_dashboard.html.erb
- app/views/comments/index.html.erb
- app/views/projects/_join.html.haml
- app/webpack/projects/show/components/project_membership_button.jsx
- config/locales/en.yml
Attempt to avoid what I presume is a costly `GROUP BY` on /comments (and the Real Time section of the dashboard).
> Fixes for /comments

- app/webpack/observations/show/components/observation_field_value.jsx
> Display observer's username in obs field popup

- app/controllers/photos_controller.rb
- app/es_indices/place_index.rb
- app/helpers/application_helper.rb
- app/views/atlases/index.html.haml
- app/views/listed_taxa/_place_tip.html.erb
- app/views/lists/_listed_taxon.html.erb
- app/views/observations/index.html.haml
- app/views/taxon_framework_relationships/index.html.haml
- app/webpack/observations/show/components/project_fields_modal.jsx
- app/webpack/observations/show/components/projects.jsx
- app/webpack/observations/uploader/components/taxon_autocomplete.jsx
- app/webpack/projects/show/components/news.jsx
- app/webpack/shared/components/user_text.jsx
- config/locales/en.yml
- db/migrate/20210220195556_add_names_to_places_index.rb
- db/structure.sql
This adds a nested object to documents in the place index that uses the same fields we're using in the taxon index. This will allow our existing search API to search on these fields without modification, so people search for "china," "中国," or "Китай" will all be able to find the country China.
Not 100% sure if this is the right way to add a nested field to the index, though.
Closes #2951
> Index translated place names

- app/webpack/taxa/shared/ducks/taxon.js
- app/webpack/taxa/show/actions/taxon.js
- app/webpack/taxa/show/components/charts.jsx
- app/webpack/taxa/show/components/highlights_tab.jsx
- app/webpack/taxa/show/components/taxon_page_tabs.jsx
- app/webpack/taxa/show/containers/charts_container.js
- app/webpack/taxa/show/containers/highlights_tab_container.js
- app/webpack/taxa/show/containers/taxon_page_tabs_container.js
- app/webpack/taxa/show/ducks/observations.js
The important change here is waiting to fetch the History histogram until that tab is clicked.
Otherwise, I also added loading text to the Seasonality and History histograms and added lazy loading for the map, recent observations, discoveries, and wanted sections.
> Taxon details: lazy loading

- app/assets/javascripts/ang/templates/observation_search/results_table.html.haml
I was trying to read the Angular code anyway, so I figured I'd take this one.
> Link observer icon and login name to their profile in Explore List view

- app/assets/javascripts/jquery/plugins/inat/place_autocomplete.js.erb
- app/assets/stylesheets/observations/identify.scss
- app/webpack/observations/identify/components/place_autocomplete.jsx
> Search API for places autocomplete

- app/webpack/users/edit/components/app.jsx
> Added additional save button to users/edit (closes #3020)

- app/models/local_photo.rb
- app/models/photo.rb
- lib/acts_as_flaggable/flag.rb
- Flagged photos will be moved out of the open data bucket
- Bugfix: unresolving flags should trigger flagging callbacks
> Photo flagging

- app/controllers/users/registrations_controller.rb
- app/models/oauth_application.rb
- db/migrate/20210625223935_add_oauth_application_id_to_users.rb
- db/structure.sql
- spec/controllers/registrations_controller_api_spec.rb
Closes #3079, though the exact request in that issue is impossible given the current API.
> Record OAuth app used to create a user

- app/views/stats/index.html.haml
#2776
Updates `/stats` link from `/pages/network` to `/sites/network`
> Update stats network link

- app/views/lists/show.html.erb
- config/locales/en.yml
#3030 
Added quotes @tiwane if that works, otherwise all set!
> Update new list text

- app/models/place.rb
Was thinking something like this for #2547 @kueda. 
I was assuming the skip validation was primarily around lat/lon, but let me know if you can think of another place where it would be conditional.
I played around with this in console and specs are green, but honestly must admit I don't have a great strategy here for manual testing.
> Selectively validate on place bbox update

- app/webpack/observations/identify/components/suggestions.jsx
#3108
Pre-req: https://github.com/inaturalist/iNaturalistAPI/pull/261 required to allow functionality
> Add alpha sort to taxa suggest

- app/assets/stylesheets/taxa/show.scss
- app/webpack/taxa/show/components/articles_tab.jsx
- app/webpack/taxa/show/containers/articles_tab_container.js
- config/locales/en.yml
> Added info to taxon detail showing CV model inclusion

- app/webpack/shared/components/user_text.jsx
- package-lock.json
- package.json
#3038
First step in removing underscore.
> Remove safe-html dependency

- app/views/announcements/edit.html.haml
- app/views/announcements/index.html.haml
- app/views/announcements/show.html.haml
> Add announcement page titles

- app/controllers/announcements_controller.rb
- app/views/announcements/index.html.haml
> Add site ids to announcement index

- app/controllers/flags_controller.rb
- app/models/place.rb
- app/views/flags/global_index.html.haml
- app/views/places/show.html.haml
- app/views/shared/_activity_item.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20190104024910_add_resolved_at_and_flaggable_user_id_to_flags.rb
- lib/acts_as_flaggable/flag.rb
- lib/acts_as_spammable/rakismet.rb
- spec/controllers/flags_controller_spec.rb
- spec/lib/acts_as_spammable/rakismet_spec.rb
- spec/models/flag_spec.rb
#2472 
Kind of from a while back, but if this is still on the table @tiwane, @kueda, this adds in the ability to track flagged places from within iNat proper
(subject to change in https://github.com/inaturalist/inaturalist/pull/3151)
> 2472 Add flags to places

- app/webpack/observations/identify/ducks/suggestions.js
#2867 
Many of these Redux idioms are still fairly foreign to me, but this tested well in an admittedly small dataset. Subsequently this just covers the filter persistence, and not the query issue as that looks to be a bit more work/grokking of the patterns. Would love to hear any feedback.
Also, there is an existing edge case/bug where unknowns show the last observation's taxa ancestry. 
To reproduce select an obs adjacent to an "Unknown". When filtering on ranked taxon level for the observation (eg Vascular Plants for a observation of a sagebrush), clicking on prev/next from the modal to the adjacent "Unknown" observation will not be able to populate a recommended taxon level for this (the only reasonable one here is State of matter life), but rather defaults back to the last (Vascular …
> Persist obs identification modal suggestion filters

- app/models/user_mute.rb
- spec/models/quality_metric_spec.rb
- spec/models/saved_location_spec.rb
- spec/models/site_admin_spec.rb
- spec/models/site_featured_project_spec.rb
- spec/models/site_spec.rb
- spec/models/sound_spec.rb
- spec/models/source_spec.rb
- spec/models/subscription_spec.rb
- spec/models/taxon_ancestor_spec.rb
- spec/models/taxon_change_spec.rb
- spec/models/taxon_change_taxon_spec.rb
- spec/models/taxon_framework_relationship_spec.rb
- spec/models/taxon_framework_spec.rb
- spec/models/taxon_link_spec.rb
- spec/models/taxon_name_spec.rb
- spec/models/taxon_photo_spec.rb
- spec/models/taxon_range_spec.rb
- spec/models/taxon_spec.rb
- spec/models/trip_purpose_spec.rb
- spec/models/trip_spec.rb
- spec/models/trip_taxon_spec.rb
- spec/models/update_action_spec.rb
- spec/models/user_block_spec.rb
- spec/models/user_mute_spec.rb
- spec/models/user_parent_spec.rb
- spec/models/user_privilege_spec.rb
- spec/models/user_spec.rb
- spec/models/year_statistic_spec.rb
> Add shoulda matchers q y

- spec/models/guide_spec.rb
- spec/models/guide_taxon_spec.rb
- spec/models/guide_user_spec.rb
- spec/models/identification_spec.rb
- spec/models/list_rule_spec.rb
- spec/models/list_spec.rb
- spec/models/listed_taxon_alteration_spec.rb
- spec/models/listed_taxon_spec.rb
- spec/models/message_spec.rb
- spec/models/model_attribute_change_spec.rb
- spec/models/moderator_action_spec.rb
- spec/models/moderator_note_spec.rb
Related: https://github.com/inaturalist/inaturalist/pull/3155
> Add shoulda matchers "g-m"

- app/models/observation_field.rb
- spec/models/observation_field_spec.rb
- spec/models/observation_field_value_spec.rb
- spec/models/observation_link_spec.rb
- spec/models/observation_photo_spec.rb
- spec/models/observation_review_spec.rb
- spec/models/observation_sound_spec.rb
- spec/models/observation_spec.rb
- spec/models/observations_export_flow_task_spec.rb
- spec/models/observations_place_spec.rb
- spec/models/password_spec.rb
- spec/models/photo_spec.rb
- spec/models/picasa_photo_spec.rb
- spec/models/place_geometry_spec.rb
- spec/models/place_spec.rb
- spec/models/place_taxon_name_spec.rb
- spec/models/post_spec.rb
- spec/models/project_asset_spec.rb
- spec/models/project_list_spec.rb
- spec/models/project_observation_field_spec.rb
- spec/models/project_observation_spec.rb
- spec/models/project_spec.rb
- spec/models/project_user_invitation_spec.rb
- spec/models/project_user_spec.rb
- spec/models/provider_authorization_spec.rb
> Add shoulda matchers o p

- app/models/observations_export_flow_task.rb
- spec/models/observations_export_flow_task_spec.rb
Is this what you had in mind for #3145, @pleary?
> Stop exporting tasks that don't exist

- app/assets/javascripts/ang/controllers/observation_search.js
- app/assets/javascripts/ang/inaturalist_angular.js
- app/assets/javascripts/inaturalist/map3.js.erb
- app/assets/javascripts/jquery/plugins/inat/taxonmap.js.erb
- app/assets/stylesheets/bootstrap-inat.scss
- app/webpack/observations/compare/components/tabs.jsx
- app/webpack/observations/compare/ducks/compare.js
- app/webpack/observations/identify/components/observation_modal.jsx
- app/webpack/observations/identify/components/taxon_map.jsx
- app/webpack/observations/show/components/map.jsx
- app/webpack/observations/uploader/components/location_chooser.js
- app/webpack/observations/uploader/components/location_chooser_map.jsx
- app/webpack/observations/uploader/models/util.js
- app/webpack/projects/show/components/umbrella_map.jsx
- app/webpack/projects/show/util.js
- app/webpack/shared/components/error_boundary.jsx
- app/webpack/taxa/show/components/taxon_page_map.jsx
- app/webpack/taxa/show/components/taxon_page_tabs.jsx
- config/locales/en.yml
Attempt to prevent pages from becoming completely non-functional when Google Maps is blocked for some reason.
> Google maps blocking

- app/helpers/flags_helper.rb
Fixes minor bug with the `FlagHelper` when trying to link to a resource that has not edit view
> Flag helper bug

- app/assets/javascripts/ang/templates/observation_search/filter_menu.html.haml
- app/controllers/taxa_controller.rb
- app/models/guide_photo.rb
- app/models/local_photo.rb
- app/models/photo.rb
- app/webpack/taxa/show/components/photo_chooser_modal.jsx
- config/environments/prod_dev.rb
- lib/tasks/inaturalist.rake
- spec/lib/darwin_core/simple_multimedia_spec.rb
- Guide and Taxon photos will should be created as LocalPhotos
- Alternate photo URL generation using only data from original_url, preparing for URLs to be removed from the table
> Convert everything to LocalPhotos

- app/controllers/donate_controller.rb
- app/controllers/guides_controller.rb
- app/controllers/observations_controller.rb
- app/controllers/posts_controller.rb
- app/controllers/trips_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/helpers/guides_helper.rb
- app/models/devise_mailer.rb
- app/models/emailer.rb
- app/models/guide.rb
- app/views/emailer/_header.html.erb
- app/views/emailer/observations_export_failed_notification.html.haml
- app/views/emailer/observations_export_notification.html.haml
- app/views/guides/show.html.haml
- app/views/guides/show.xml.builder
- app/views/observations/dwc.eml.erb
- app/views/stats/year.html.haml
- app/views/taxa/dwc.eml.erb
Work toward #3264, which I no longer think is fully doable, as I now think we need to keep something like FakeView.
> Removed unnecessary uses of FakeView

- app/assets/javascripts/observations/by_login.js
Fixes #3262 
I broke it in commit 415f2a91ecf963f57c36e6460227f59d472c13c9
Issue was that it was sending the param name rather than the token, so failed authentication on POST.
> Fix Edit Observations add to project and Flickr tagger

- app/models/conservation_status.rb
- spec/models/conservation_status_spec.rb
> Stop setting status geoprivacy based on IUCN equivalent

- app/models/observation.rb
- app/models/taxon_name.rb
- spec/controllers/observation_controller_api_spec.rb
- spec/models/observation_spec.rb
- spec/models/taxon_name_spec.rb
- tools/donorbox-plans.rb
- tools/donorbox.rb
* Bugfix: couldn't add taxon names in Malayalam (closes #3300)
* Replace cancelled donorbox plans with subsequent active ones (closes #3310)
* Only reset coords if they haven't already changed when unobscuring (closes #3301)
> Several bug fixes

- app/assets/javascripts/inaturalist/map3.js.erb
- app/helpers/application_helper.rb
- tools/import_conservation_statuses_for_partner.rb
Also added a minor change for conservation status import logging.
> Updated version of Google Maps; fixed issue w/ wax interactivity

- .sass-lint.yml
- app/assets/stylesheets/stats/year.scss
- app/controllers/donate_controller.rb
- app/models/year_statistic.rb
- app/views/layouts/bootstrap.html.erb
- app/views/shared/_footer.html.haml
- app/webpack/stats/year/components/app.jsx
- app/webpack/stats/year/components/compare.jsx
- app/webpack/stats/year/components/donate.jsx
- app/webpack/stats/year/components/donate_banner.jsx
- app/webpack/stats/year/components/observations.jsx
- app/webpack/stats/year/components/translators.jsx
- config/locales/en.yml
* Added donation banner at the top for default site YIR and user YIR when viewing the default site
* Changed layout for Donate and Store sections
* Changed `utm_source` on /donate to the domain of the current site instead of the site name; we've been explicitly setting it that way from the footer link for a long time, so that kind of standardizes around that
* Removed controls from Compare for the sites, since we're not actually generating the "date observed" data for those
Most changes are due to code style changes and messing with the grid containers to accommodate a full width banner in the new Donate section.
> Year In Review 2021: high priority updates

- app/assets/stylesheets/flags/new.scss
- app/controllers/flags_controller.rb
- app/views/flags/_flag_list.html.haml
- app/views/flags/new.html.haml
- config/locales/en.yml
- lib/acts_as_flaggable/flag.rb
- spec/controllers/flags_controller_spec.rb
Issue: https://github.com/inaturalist/inaturalist/issues/3098
This is what happens when you try to submit the form with no reason.
Note: My IDE did some trailing space deletion that I hope we can all live with.
> Add comment field to new flag form

- lib/darwin_core/archive.rb
- lib/darwin_core/occurrence.rb
- lib/darwin_core/simple_multimedia.rb
- spec/lib/darwin_core/archive_spec.rb
* Create any extensions that use obs search within a single round of searching
* Cache taxonomy for faster ranked ancestor lookups
* More preloading
> Dwca changes

- config/locales/en.yml
Resolves https://github.com/inaturalist/inaturalist/issues/3344
> Added edit_moderator_note to en.yml

- app/assets/javascripts/ang/controllers/observation_search.js
So that when searching for a nearby location it starts directly at the center of the google search result instead of where the map happens to be centered on in the browser.
This can avoid clicking on Niger in the search results and being sent to Nigeria by mistake.
Fixes #2911
> Fix google location search

- app/controllers/flags_controller.rb
- app/views/flags/show.html.haml
- lib/acts_as_flaggable/flag.rb
- spec/blueprints.rb
- spec/controllers/flags_controller_api_spec.rb
- spec/factories/flags.rb
Resolves https://github.com/inaturalist/inaturalist/issues/2589
> Only Taxon Flags can be Self Resolved

- db/migrate/20220217224804_remove_photos_table_columns.rb
- db/structure.sql
- spec/models/local_photo_spec.rb
- spec/models/photo_spec.rb
Removes columns from the photos table that are no longer needed
> Remove photos columns

- app/controllers/taxa_controller.rb
- app/helpers/application_helper.rb
- app/models/taxon.rb
- app/models/taxon_name.rb
- db/migrate/20220308015748_remove_taxa_unique_name.rb
- db/structure.sql
- lib/ratatosk/spec/name_provider_example_groups.rb
- lib/ratatosk/spec/nzor_provider_spec.rb
- lib/ratatosk/spec/ratatosk_spec.rb
- spec/fixtures/taxa.yml
- spec/models/taxon_spec.rb
Removed some vestigial data. Closes #3387
> Remove taxon unique name

- app/assets/javascripts/inaturalist/map3.js.erb
- app/assets/stylesheets/observations/uploader.scss
- app/helpers/application_helper.rb
- app/webpack/computer_vision/webpack-entry.js
- app/webpack/lifelists/show/webpack-entry.js
- app/webpack/observations/compare/webpack-entry.js
- app/webpack/observations/identify/webpack-entry.js
- app/webpack/observations/show/webpack-entry.js
- app/webpack/observations/uploader/components/drag_drop_zone.js
- app/webpack/observations/uploader/components/google_places_search_box.jsx
- app/webpack/observations/uploader/components/location_chooser.js
- app/webpack/observations/uploader/components/location_chooser_map.jsx
- app/webpack/observations/uploader/components/photo_marker_overlay_view.js
- app/webpack/observations/uploader/webpack-entry.js
- app/webpack/project_slideshow/webpack-entry.js
- app/webpack/projects/form/webpack-entry.js
- app/webpack/projects/show/webpack-entry.js
- app/webpack/search_slideshow/webpack-entry.js
- app/webpack/taxa/photos/webpack-entry.js
- app/webpack/taxa/show/webpack-entry.js
- app/webpack/users/edit/webpack-entry.js
- package-lock.json
- package.json
Replace react-google-maps with our own code that uses the Google Maps API directly, albeit a bit less react-y.
Closes #3393
> Replace react google maps

- lib/site_data_exporter.rb
- spec/lib/site_data_exporter_spec.rb
* code style cleanup
* use replica for observation db queries
* fix broken db connection config lookup for psql commands
* added a spec
> Site data export fixes

- app/webpack/observations/uploader/models/util.js
- app/webpack/shared/components/rejected_files_error.jsx
> Update file type error messages

- app/views/observations/_form_fields.html.erb
- app/webpack/observations/uploader/models/obs_card.js
- app/webpack/taxa/show/components/photo_chooser_modal.jsx
- config/locales/en.yml
- package-lock.json
- package.json
Two small changes from @tiwane's most recent support report. Only possible liability I can see is the update to the `uuid` JS package. Neither of the changes are urgent. I'll merge them in when I get back if no one else does.
> obs/edit re-order photo link position & taxon photo chooser tip

- app/controllers/taxa_controller.rb
The intent is to support URLs like /taxa/Aves/browse_photos so people we can route requests to taxon sub-paths by name and not just by ID.
> Support taxon sub-paths with only a name

- app/helpers/application_helper.rb
> Escape skids for markdown user mentions

- app/models/post.rb
Main change here is to use the `HasJournal` concern for `editable_by?`
> Use journal concern in Post, rubocop autocorrect

- app/models/observation.rb
- spec/models/observation_spec.rb
Infraspecific IDs move the obs taxon to species #3543
> Infraspecific ID behavior change

- app/assets/javascripts/ang/controllers/observation_search.js.erb
- app/assets/javascripts/ang/factories/observations.js.erb
- app/assets/javascripts/ang/models/observation.js
- app/assets/javascripts/ang/models/taxon.js.erb
As part of https://github.com/inaturalist/inaturalist/issues/3038
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_isundefined
> Replace usages of `_.isUndefined`.

- lib/inat_api_service.rb
- lib/inat_api_service/v2/client.rb
- spec/lib/inat_api_service/stubs/get_taxon_by_id.json
- spec/lib/inat_api_service/v2/client_spec.rb
- tools/development_tools/import_taxon_from_production.rb
- tools/development_tools/taxon_importer/taxon_importer.rb
- Adds `TaxonImporter` for pulling production taxa.
> Add TaxonImporter tool, apiv2 client

- app/models/taxon_name.rb
- config/locales/en.yml
- lib/darwin_core/vernacular_name.rb
- spec/lib/darwin_core/vernacular_name.rb
- tools/clean_lexicons.rb
* Rubocop style fixes
* Include names with a blank lexicon in DwC-A for community review
* Added several synonymies to cleaning script
> Lexicon cleanup

- app/assets/javascripts/ang/controllers/observation_search.js.erb
- app/assets/javascripts/inaturalist/map3.js.erb
- app/webpack/observations/identify/reducers/search_params_reducer.js
- app/webpack/observations/show/ducks/confirm_modal.js
- app/webpack/observations/uploader/reducers/drag_drop_zone.js
- app/webpack/taxa/photos/ducks/photos.js
- app/webpack/users/edit/ducks/user_settings.js
As part of https://github.com/inaturalist/inaturalist/issues/3038
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_isarray
> Replace usages of `_.isArray`.

- app/webpack/observations/show/components/flagging_modal.jsx
- app/webpack/projects/shared/models/project.js
- app/webpack/projects/show/containers/flagging_modal_container.js
- package-lock.json
> Ensure local Project model extends inatjs model; use instanceof

- app/controllers/places_controller.rb
- app/views/places/search.html.erb
> Only users with organizer privilege can see place creation

- app/assets/javascripts/ang/controllers/observation_search.js.erb
- app/assets/javascripts/ang/factories/observations.js.erb
- app/assets/javascripts/stats.js
- app/assets/javascripts/torque.full.uncompressed.js
- app/webpack/lifelists/show/reducers/lifelist.js
- app/webpack/observations/compare/components/history_comparison.jsx
- app/webpack/observations/identify/actions/observations_actions.js
- app/webpack/observations/identify/ducks/suggestions.js
- app/webpack/observations/uploader/actions/actions.jsx
- app/webpack/observations/uploader/components/drag_drop_zone.jsx
- app/webpack/observations/uploader/components/left_menu.jsx
- app/webpack/observations/uploader/components/location_chooser_map.jsx
- app/webpack/observations/uploader/components/time_shifter.jsx
- app/webpack/observations/uploader/reducers/drag_drop_zone.js
- app/webpack/projects/form/form_reducer.js
- app/webpack/projects/show/components/requirements.jsx
- app/webpack/shared/components/histogram.jsx
- app/webpack/shared/components/rejected_files_error.jsx
- app/webpack/shared/ducks/config.js
- app/webpack/shared/util.js
- app/webpack/stats/year/components/compare.jsx
- app/webpack/stats/year/components/translators.jsx
- app/webpack/taxa/photos/components/photo_browser.jsx
- app/webpack/taxa/photos/ducks/photos.js
- app/webpack/taxa/shared/ducks/taxon.js
- app/webpack/taxa/show/containers/charts_container.js
As part of https://github.com/inaturalist/inaturalist/issues/3038
https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_keys
> Replace usages of `_.keys`

- app/controllers/users/passwords_controller.rb
- app/models/user.rb
- spec/controllers/registrations_controller_api_spec.rb
- spec/controllers/users/passwords_controller_spec.rb
Temporary fix for bug preventing Seek users from resetting a password.
> Allow reset password to succeed with an application/anonymous JWT

- app/assets/javascripts/application_bundle.js
- app/assets/javascripts/i18n/to_time.js
> JS lowercase month strftime

- app/models/emailer.rb
- tools/mass_mailer.rb
Converts the email confirmation reminder script into something that can be used to deliver any mailer action.
> Mass mailer

- app/views/donate/index.html.haml
- app/views/donate/monthly_supporters.html.haml
- app/views/emailer/_footer.html.erb
- app/views/shared/_footer.html.haml
- app/webpack/users/edit/components/profile.jsx
- config/locales/en.yml
- config/routes.rb
Suspend donations while we update our donation infrastructure.
> Donation suspension

- app/assets/javascripts/taxa/conservation_statuses_form.js
- app/assets/javascripts/taxon_names/form.js
- app/assets/stylesheets/taxa/show.scss
- app/controllers/conservation_statuses_controller.rb
- app/controllers/taxon_names_controller.rb
- app/models/taxon_name.rb
- app/views/conservation_statuses/edit.html.haml
- app/views/taxon_names/_form.html.haml
- app/views/taxon_names/edit.html.haml
- app/webpack/taxa/show/components/taxonomy_tab.jsx
- config/locales/en.yml
- spec/controllers/taxon_names_controller_spec.rb
- #3726
- #3727
- Taxon page incudes place names (addresses the goal behind #3735)
- #3795
> Names changes

- config/initializers/global.rb
- tools/mass_mailer.rb
Uses Sendgrid email address validation API to the mass mailer script in an attempt to preserve our sender reputation when sending mass mail.
Also adjusted the try_and_try_again method to support exponential backoff.
> Sendgrid validation

- app/assets/javascripts/ang/controllers/observation_search.js.erb
- app/assets/javascripts/inaturalist/map3.js.erb
- app/assets/javascripts/modal_image.js
- app/controllers/observations_controller.rb
- app/helpers/application_helper.rb
- app/views/layouts/bootstrap.html.erb
- app/views/shared/_header.html.haml
- Adds ability to load Google Maps JS asynchronously
- Attempts to address timing issues leading to results not being mapped properly in explore #3636
> Explore maps timing

- app/controllers/admin_controller.rb
Tries to prevent some debilitating PG queries originating in the admin user content tool.
> Admin user content guardrails

- app/controllers/admin_controller.rb
- app/es_indices/user_index.rb
- app/views/admin/users.html.haml
Rework user search (admin) to use ES instead of the DB
> Index user's email and IP

- app/assets/javascripts/inaturalist/map3.js.erb
- app/assets/javascripts/jquery/plugins/inat/taxonmap.js.erb
- app/controllers/geo_model_controller.rb
- app/views/geo_model/explain.html.haml
- app/webpack/geo_model/explain/components/app.jsx
- package-lock.json
Use tile layers on Geomodel explain page instead of GeoJSON data layers
> Geomodel explain tile layers

- app/models/local_photo.rb
- spec/models/local_photo_spec.rb
We try to use word combinations from filenames to look up taxa to accommodate names that might be in the middle of a filename, but this can result in some gargantuan database queries. This tries to limit this problem by:
* Only looking for 1-, 2-, and 3-word combinations
* Ensuring the list of tags extracted from a photo is unique
> Limits to taxon lookups from photo filenames

- app/assets/stylesheets/stats/year.scss
- app/models/year_statistic.rb
- app/views/observations/show.html.haml
- app/views/shared/_outlink_site_icons_js.html.haml
- app/views/shared/_outlink_sites_js.html.haml
- app/views/stats/year.html.haml
- app/webpack/observations/show/components/research_grade_progress.jsx
- app/webpack/stats/year/components/broader_impacts.jsx
- app/webpack/stats/year/components/pie_chart.jsx
- app/webpack/stats/year/components/summary.jsx
- config/initializers/paperclip.rb
- config/locales/en.yml
* Adds a "People" pie chart to the summary at the top of the global and site pages #3907
* Adds a "Broader Impacts" section for linking out to observation link sources #3908
> Year in review additions

- app/models/observation_accuracy_experiment.rb
- app/views/observation_accuracy_experiments/_methods.html.haml
- app/views/observation_accuracy_experiments/show.html.haml
- config/locales/CONTRIBUTORS.md
- config/locales/en.yml
Fixes for obs acc experiment detail page related to recent i18n updates.
> Obs acc i18n fixes

- app/models/user.rb
closes [#4002](https://github.com/inaturalist/inaturalist/issues/4002)
> closes #4002

- app/controllers/provider_oauth_controller.rb
- app/models/user.rb
- config/initializers/devise.rb
- config/initializers/doorkeeper.rb
- spec/controllers/oauth_tokens_controller_spec.rb
- spec/controllers/provider_oauth_controller_spec.rb
> Login without email confirmation

- app/models/segmentation_statistic.rb
- db/migrate/20240326135332_add_segmentation_statistics.rb
- db/structure.sql
The aggregated segmentation data will be stored every month in this new table.
A method `get_viz_stats_for_day` will return a view of these data for the D3 Treemap.
In `production_schedule.rb`, the generation will be scheduled like that:
```
every :month, at: '5:00 pm', on: :first_day
nice_rails_command "SegmentationStatistic.generate_stats_for_day(Time.now.utc - 1.day)"
end
```
> Segmentation Statistics

- app/models/emailer.rb
- app/views/emailer/first_observation.html.haml
- app/views/emailer/observer_appeal.html.haml
- tools/first_observation_experiment.rb
experiment to see if sending en email after the first observations results in more/higher quality observations
> First observation

- app/assets/stylesheets/application_bundle.css
- app/assets/stylesheets/lifelists.scss
- app/assets/stylesheets/shared/confirmation_banner.scss
- app/models/user_privilege.rb
- app/views/geo_model/explain.html.haml
- app/views/geo_model/index.html.haml
- app/views/layouts/application.html.erb
- app/views/layouts/bootstrap.html.erb
- app/views/lifelists/by_login.html.haml
- app/views/observations/compare.html.haml
- app/views/observations/identify.html.haml
- app/views/observations/show.html.haml
- app/views/projects/show2.html.haml
- app/views/shared/_confirmation_banner.haml
- app/views/stats/year.html.haml
- app/views/taxa/browse_photos.html.haml
- app/views/taxa/show.html.haml
- app/views/users/edit2.html.haml
- app/webpack/.eslintrc
- app/webpack/shared/ducks/config.js
- app/webpack/users/confirmation_banner/components/banner.jsx
- app/webpack/users/confirmation_banner/containers/banner_container.js
- app/webpack/users/confirmation_banner/reducers/reducer.js
- app/webpack/users/confirmation_banner/webpack-entry.js
- config/locales/en.yml
- config/webpack.config.js
- spec/models/user_privilege_spec.rb
- Adds a banner encouraging users to confirm their email address #4031
- Requires a confirmed email address to earn organizer privilege #4032
> User confirmation changes

- app/controllers/observation_accuracy_experiments_controller.rb
- app/models/observation_accuracy_experiment.rb
- app/views/observation_accuracy_experiments/_methods.html.haml
- app/views/observation_accuracy_experiments/show.html.haml
- config/locales/en.yml
- db/migrate/20240429211140_add_post_id_to_observation_accuracy_experiment.rb
- db/structure.sql
Three changes:
1. use country rather than continent to match validators to sample observations to provide more localized matching
2. add disclaimer to message to not-reply and provide optional link to accompanying blog post for more context/feedback
3. add hand-holding text to message to help people accessing this message through the iNat Android app
> Observation accuracy experiment 4 updates

- tools/seek_common_names.rb
Mainly updates list of languages supported by Seek. Also Rubocop compliance.
> Seek common names update

- app/controllers/flags_controller.rb
- app/views/flags/index.html.haml
Just added the `will_paginate` helpers to the correct view.
Also took the opportunity to clean just a bit. 
`@unresolved` and `@resolved` were not use at all in this part of the code and were loading for nothing.
> #3758: Add pagination on flags

- app/helpers/application_helper.rb
- app/views/places/show.html.haml
- config/locales/en.yml
Minor updates. Should be merged after https://github.com/inaturalist/inaturalist/pull/4105 is merged _and deployed_ to minimize churn.
> I18n updates

- app/assets/stylesheets/blueprint-bootstrap.scss
- app/assets/stylesheets/blueprint-inat.scss
- app/assets/stylesheets/bootstrap_bundle.scss
- app/assets/stylesheets/donate.scss
- app/assets/stylesheets/index.scss
- app/assets/stylesheets/lifelists.scss
- app/assets/stylesheets/observations/identify/filters_button.scss
- app/assets/stylesheets/observations/identify/observation_modal.scss
- app/assets/stylesheets/observations/search.scss
- app/assets/stylesheets/observations/show.scss
- app/assets/stylesheets/projects/new2.scss
- app/assets/stylesheets/projects/show2.scss
- app/assets/stylesheets/projects/stats_slideshow.scss
- app/assets/stylesheets/shared/activity_item.scss
- app/assets/stylesheets/shared/annotations.scss
- app/assets/stylesheets/shared/flash_message.scss
- app/assets/stylesheets/shared/google_maps.scss
- app/assets/stylesheets/shared/observation_fields.scss
- app/assets/stylesheets/shared/taxonomic_branch.scss
- app/assets/stylesheets/stats/year.scss
- app/assets/stylesheets/taxa/geo_explain.scss
- app/assets/stylesheets/taxa/show.scss
- app/assets/stylesheets/users.css
- app/assets/stylesheets/users/edit.scss
- app/assets/stylesheets/users/registrations.scss
- app/assets/stylesheets/users/user_popover.scss
- app/assets/stylesheets/welcome.scss
- app/views/donate/index.html.haml
- app/views/emailer/_fonts.css.erb
* Ensures font weight 700 uses a thicker font than 600
* Updates styles accordingly to prevent changes in how fonts are displayed
* A few other small style updates like #4119, and updates for Google map infowindows after recent style change
> Fix font weight order

- app/assets/stylesheets/observations/show.scss
- app/webpack/observations/show/components/map_details.jsx
- app/webpack/observations/uploader/components/google_places_autocomplete.jsx
- app/webpack/observations/uploader/components/location_chooser.jsx
- app/webpack/observations/uploader/components/location_chooser_map.jsx
- config/locales/en.yml
* Coordinates can be copied on obs show #3897
* Coordinates can be searched again in explore if they match a decimal coordinate pattern: lat, lng #3952
> Coordinate copy and search

- app/assets/javascripts/inaturalist/map3.js.erb
- lib/inat_api_service.rb
added not-in-list-id to explore params and also did some rubocop cleanup on lib/inat_api_service.rb
> not-in-list-id-explore-param & rubocop appeasement

- app/models/site.rb
- app/views/shared/_header.html.haml
- config/locales/en.yml
Adds additional links to the More menu as long as sites have corresponding preferences
> Add links to header More menu

- app/assets/javascripts/ang/controllers/observation_search.js.erb
- app/assets/javascripts/guide_taxa/show.js
- app/assets/javascripts/inaturalist/map3.js.erb
- app/assets/javascripts/jquery/plugins/inat/taxonmap.js.erb
- app/assets/javascripts/jquery/plugins/jquery.latLonSelector.js.erb
- app/assets/javascripts/observations/edit.js
- app/assets/stylesheets/observations/uploader.scss
- app/assets/stylesheets/shared/saved_location_chooser.scss
- app/views/observations/edit.html.erb
- app/views/observations/index.html.haml
- app/views/places/index.html.erb
- app/webpack/observations/identify/components/observation_modal.jsx
- app/webpack/observations/identify/components/taxon_map.jsx
- app/webpack/observations/uploader/components/location_chooser_map.jsx
- config/locales/en.yml
* Adds the default OpenStreetMap tiles (from tiles.openstreetmap.org) as a base map option for all maps
* Added OSM attribution to all maps when OSM tiles shown
* Changes base map control to a dropdown by default
> OpenStreetMap base map

- app/assets/stylesheets/users/edit.scss
- app/controllers/users_controller.rb
- app/views/layouts/bootstrap.html.erb
- app/views/users/delete.html.haml
- app/webpack/users/edit/components/account.jsx
- app/webpack/users/edit/components/app.jsx
- app/webpack/users/edit/components/applications.jsx
- app/webpack/users/edit/components/cc_licensing_modal.jsx
- app/webpack/users/edit/components/content.jsx
- app/webpack/users/edit/components/notifications.jsx
- app/webpack/users/edit/components/profile.jsx
- app/webpack/users/edit/components/relationships.jsx
- app/webpack/users/edit/components/settings_item.jsx
- app/webpack/users/edit/components/taxon_name_priorities.jsx
- app/webpack/users/edit/components/toggle_switch.jsx
- app/webpack/users/edit/components/user_following.jsx
- config/locales/en.yml
- db/structure.sql
- spec/controllers/users_controller_spec.rb
* lots of small stuff
* license descriptions modal
* nav select fixed to top
* save button fixed to bottom
* scarier styling for the danger zone in mobile and web
> Mobile account settings style

- app/webpack/projects/show/components/app.jsx
- app/webpack/projects/show/components/project_membership_button.jsx
- app/webpack/projects/show/ducks/project.jsx
- app/webpack/projects/show/webpack-entry.js
Enable APIv2 for all users on collection and umbrella project pages
> Projects APIv2

- app/controllers/announcements_controller.rb
- app/controllers/welcome_controller.rb
- app/helpers/application_helper.rb
- app/models/announcement.rb
- app/models/announcement_dismissal.rb
- app/models/announcement_impression.rb
- app/views/announcements/_announcement.html.haml
- config/initializers/logstasher.rb
- db/migrate/20240923134239_create_announcement_impressions.rb
- db/migrate/20240923134658_create_announcement_dismissals.rb
- db/structure.sql
- spec/helpers/application_helper_spec.rb
- spec/models/announcement_dismissal_spec.rb
- spec/models/announcement_impression_spec.rb
- spec/models/announcement_spec.rb
* Creates new models `AnnouncementImpression` and `AnnouncementDismissal`
* Impressions are created when announcements are rendered
* Dismissals are synced with announcement.dismiss_user_id when the value changes
* Both are logged to the logstash log file
> Announcement Impressions

- app/controllers/users_controller.rb
- app/models/cohort_lifecycle.rb
- app/models/observation_accuracy_experiment.rb
- app/views/users/dashboard.html.haml
- lib/inat_api_service.rb
Some possible refactoring ideas for this branch so far:
* Remove logic from the UsersController and moved into model and view
* Move score_observation API logic into INatAPIService using application token for authentication
> Refactor ideas for first_observation_update

- app/controllers/provider_oauth_controller.rb
* feat: use apple.app_bundle_ids from config when verifying a JWT from apple, allowing us to permit tokens from iNat legacy and iNat Next
* fix: unbreak error processing when the token is blank
* fix: improve style compliance and fix types
> feat: support Sign in with Apple from multiple apps

- app/models/user.rb
It was limited to the number of auto-generated logins already in the database. This should allow it to generate new unique logins indefinitely.
The caveat is that now it can potentially run literally forever, and even under ideal circumstances, it will need to recur a few times in production b/c of the number of users with logins that looks like `/naturalist\d+/`.
> fix: allow User.suggest_login to suggest unique logins forever

- app/models/year_statistic.rb
- app/webpack/stats/year/components/translators.jsx
- config/locales/en.yml
> feat: add iNatHelp contributions to YIR Translators chart

- app/assets/stylesheets/index.scss
- app/helpers/application_helper.rb
- app/helpers/users_helper.rb
- app/views/comments/_comment.html.erb
- app/views/comments/_listing_for_dashboard.html.erb
- app/views/friendships/index.html.haml
- app/views/observations/_observations_component_for_dashboard.html.erb
- app/views/observations/new.html.erb
- app/views/places/_update_new_observations.html.erb
- app/views/posts/_posts.html.haml
- app/views/posts/browse.html.haml
- app/views/projects/_form.html.erb
- app/views/projects/_join.html.haml
- app/views/projects/_update_created_post.html.erb
- app/views/projects/contributors.html.erb
- app/views/projects/members.html.haml
- app/views/projects/show.html.erb
- app/views/projects/show_iframe.html.erb
- app/views/shared/_activity_item.html.erb
- app/views/shared/_activity_item_for_dashboard.html.erb
- app/views/shared/_by_login_header_bootstrap.html.haml
- app/views/taxa/_update_new_observations.html.erb
- app/views/users/_dashboard_updates.html.haml
- app/views/users/_followees.html.haml
- app/views/users/_show.html.haml
- app/views/users/_table.html.erb
- app/views/users/_update_created_observations.html.erb
- app/views/users/_update_created_post.html.haml
- app/webpack/shared/components/user_image.jsx
- spec/helpers/users_helper_spec.rb
This started as an effort to make Alex look nicer, but since Abhas also wants to look nicer, why don't we just make everyone look nicer. I wasn't really sure if anyone else cared.
> Display higher resolution user images

- app/assets/stylesheets/index.scss
> fix: center user profile pics when displaying as a background

- app/models/moderator_action.rb
- config/initializers/has_moderator_actions.rb
> fix: let curators who hid something unhide it from non-React views

- app/assets/stylesheets/index.scss
- app/assets/stylesheets/lists.scss
- app/helpers/application_helper.rb
- app/views/lists/by_login.html.haml
- app/views/users/_show.html.haml
> fix: unsquash user icon in non-React views & add space after notif icon

- app/webpack/observations/uploader/components/taxon_autocomplete.jsx
- app/webpack/taxa/show/containers/photo_preview_container.js
if the request photo exists in the taxon's taxon_photos it will appear first, otherwise the parameter is ignored
> Taxon pages can feature requested taxon photo

- app/controllers/donate_controller.rb
- app/views/donate/fundraiseup.html.haml
- config/routes.rb
> feat: add FundraiseUp landing page

- app/assets/stylesheets/index.scss
- app/assets/stylesheets/users.css
- app/views/users/index.html.erb
> fix: contain and center user profile pics on /people

- app/assets/javascripts/application.js.erb
- app/assets/stylesheets/index.scss
- app/helpers/application_helper.rb
- app/webpack/taxa/show/components/taxon_page_map.jsx
* fix: localize async Google Maps like we do synchronous ones so users see map
tiles in the locale of their iNat account, not their browser
* fix: use obs bounds on taxa/show when map tab loaded first; otherwise map
does not zoom to bounds
* fix: control user icon width in mention dropdown; fixes a bug in which it
was way to big, but also makes it a bit bigger than it was before to match
the size of taxon images in taxon autocomplete
> fix: localize Explore maps, taxa/show map loading, mention autocomplete

- app/assets/stylesheets/index.scss
- app/views/shared/_header.html.haml
> feat: expand clickable area of links in site header

- app/models/place.rb
- app/models/place_geometry.rb
- spec/models/place_geometry_spec.rb
- spec/models/place_spec.rb
> fix: update check list after observations added to new place

- app/helpers/application_helper.rb
- spec/helpers/application_helper_spec.rb
> fix: stop inserting <br> tags inside of tags with newlines

- README.md
Probably a minor mishap on the convert commit to markdown.
> doc: workflow badge link

- app/assets/javascripts/i18n/inflections.js
- app/assets/stylesheets/projects/show2.scss
- app/webpack/projects/show/components/app.jsx
- config/initializers/i18n.rb
> fix: adjust projects/show layout at small window sizes

- app/views/subscriptions/_edit_inline.html.erb
- config/locales/en.yml
> fix: show translated txt when unsubscribing from a post on dashboard

- app/assets/stylesheets/index.scss
> fix: stop stretching user icon in post header notification

- app/views/observations/_observation.atom.builder
> feat: add georss:featureName element to observation Atom feeds

- app/assets/stylesheets/wiki.scss
- app/controllers/wiki_pages_controller.rb
- app/views/layouts/application.html.erb
> feat: show wiki pages without columns to iNat Next responsively

- app/models/user.rb
- app/models/user_parent.rb
- config/locales/en.yml
- spec/controllers/provider_authorizations_controller_spec.rb
- spec/controllers/provider_oauth_controller_spec.rb
- spec/factories/sites.rb
- spec/factories/user_parents.rb
- spec/models/project_user_invitation_spec.rb
- spec/models/user_parent_spec.rb
- spec/models/user_spec.rb
> feat: consider all 3rd party auth users as confirmed if email present

- app/controllers/taxa_controller.rb
- app/controllers/trips_controller.rb
- app/models/taxon.rb
- app/views/taxa/_description.html.haml
- app/views/taxa/_form.html.erb
- config/locales/en.yml
- db/migrate/20250404192042_change_taxa_auto_description_to_shows_wikipedia.rb
- db/structure.sql
- spec/models/taxon_spec.rb
* fix: hide Wikipedia prompt for taxa that should not show Wikipedia content
* refactor: change auto_description to shows_wikipedia for accuracy
Closes WEB-645
> fix: hide Wikipedia prompt for taxa that should not show Wikipedia content

- app/assets/stylesheets/projects/show2.scss
- app/assets/stylesheets/projects/stats_slideshow.scss
- app/assets/stylesheets/shared/linear_gradient.scss
- app/webpack/projects/show/components/header_with_more_link.jsx
- app/webpack/projects/show/components/news.jsx
- app/webpack/projects/show/components/overview_stats.jsx
- app/webpack/projects/show/components/partial_details.jsx
- app/webpack/projects/show/components/requirements.jsx
- app/webpack/projects/show/components/umbrella_news.jsx
> feat: collapse project requirements w/ show more button

- app/models/observation.rb
Replace two separate ES queries with one query with a `filters` aggregation. On the whole this should be a little faster and a little less demanding of Elasticsearch
> refactor: update observation probably_captive? to use a single ES query

- app/assets/stylesheets/taxa/photos.scss
- app/webpack/taxa/photos/components/photo_browser.jsx
- app/webpack/taxa/photos/containers/photo_browser_container.js
- app/webpack/taxa/photos/ducks/photos.js
> feat: show link to view obs in taxon photo browser

- app/assets/javascripts/ang/templates/observation_search/taxa_grid.html.haml
> feat: add button to exclude species in Explore species contextual menu

- app/assets/stylesheets/messages.scss
- app/views/messages/_row.html.haml
- app/views/messages/new.html.haml
- app/views/messages/show.html.haml
> feat: require subject and body for new messages on web

- app/assets/javascripts/jquery/plugins/inat/user_autocomplete.js.erb
- app/assets/stylesheets/autocomplete.scss
Make user autocomplete menus shorter by default to help address [WEB-670](https://linear.app/inaturalist/issue/WEB-670)
> fix: reduce default width of user autocomplete results

- app/models/observation.rb
- config/locales/en.yml
- spec/models/observation_basics_spec.rb
> fix: prevent incorrect date parsing of single year in observed_on_string

- app/views/announcements/_form.html.haml
- config/locales/en.yml
> feat: move staff and creator targeting options to top part of annc form

- app/webpack/observations/identify/actions/current_observation_actions.js
- app/webpack/observations/identify/reducers/current_observation_reducer.js
- app/webpack/observations/show/components/annotations.jsx
> fix: prevent previous annotations from stacking up

- app/assets/javascripts/announcements/form.js
- app/models/announcement.rb
- app/views/announcements/_form.html.haml
> feat: hide dismissible checkbox for placements that can't be dismissed

- app/models/observation.rb
- spec/models/observation_basics_spec.rb
> feat: exclude open space place names from place_guess when obscuring

- app/controllers/identifications_controller.rb
- app/views/taxon_changes/_show_change_taxon.html.haml
- app/views/taxon_changes/_update_committed.html.haml
- config/locales/en.yml
fix #4363 
MERGE FIRST THIS: https://github.com/inaturalist/iNaturalistAPI/pull/510
> feat: link taxon change dashboard update to affected idents

- app/webpack/observations/identify/actions/observations_actions.js
fix: #4519 
That was easy hehe
> fix: make Mark All As Unreviewed in Identify work

- app/webpack/observations/show/components/activity_item.jsx
- config/locales/en.yml
> feat: indicate that taxon change ID was auto-added and not by user

- app/webpack/users/edit/components/content.jsx
- config/locales/en.yml
> feat: link project help in setting to official help docs

- app/assets/stylesheets/users/edit.scss
- app/webpack/shared/components/rejected_files_error.jsx
- app/webpack/users/edit/components/profile.jsx
- app/webpack/users/edit/containers/profile_container.js
- app/webpack/users/edit/ducks/user_settings.js
- config/locales/en.yml
- lib/tasks/inaturalist.rake
> fix: better validation and display of errors for user profile pictures

- app/assets/javascripts/ang/templates/observation_search/filter_menu.html.haml
- app/models/taxon.rb
- config/locales/en.yml
- lib/tasks/inaturalist.rake
> feat: clarify equivalent levels in hrank and lrank dropdowns in Explore

- app/webpack/observations/show/components/projects.jsx
- app/webpack/observations/uploader/components/projects_chooser.jsx
Also restore obs/show project selector excluding existing obs projects.
Bug caused in WEB-509
> fix: restore user projects by default on obs/show and obs/upload

- app/controllers/eol_controller.rb
- app/models/eol_photo.rb
- lib/eol_service.rb
- spec/fixtures/eol_service/_api_pages_1_0_1274016_xml_licenses=all-images_page-images_per_page=36-maps_per_page=0-texts_per_page=0-videos_per_page=0-sounds_per_page=0-details=1
- spec/fixtures/eol_service/_api_pages_1_0_485229_xml_licenses=all-images_per_page=10-text_per_page=0-videos_per_page=0-details=true
- spec/fixtures/eol_service/_api_search_1_0_xml_exact=1-q=Nycticorax
- spec/fixtures/meta_service/https-eol-org-api-pages-1-0-1274016-xml-licenses-all-images_page-images_per_page-36-maps_per_page-0-texts_per_page-0-videos_per_page-0-sounds_per_page-0-details-1
- spec/fixtures/meta_service/https-eol-org-api-search-1-0-xml-exact-1-q-nycticorax
- spec/models/eol_photo_spec.rb
> fix: allow addition of taxon photos from EOL again

- .rubocop.yml
- app/assets/javascripts/flags/index.js
- app/assets/javascripts/jquery/plugins/inat/user_autocomplete.js.erb
- app/webpack/observations/identify/components/user_autocomplete.jsx
- app/webpack/projects/form/components/user_selector.jsx
Depends on https://github.com/inaturalist/iNaturalistAPI/pull/520
> feat: allow suspended users to be returned in some user autocomplete searches, related to WEB-706

- app/views/emailer/collection_project_changed_for_trusting_member.html.haml
- test/mailers/previews/emailer_preview.rb
> feat: update help link in collection project trust email

- app/views/welcome/_index.html.haml
- app/webpack/stats/year/components/translators.jsx
> fix: switch new iOS app URL on home page and Year in Review

- app/webpack/observations/identify/components/observation_modal.jsx
> fix: remove button from tab in single-tab Observation Modal

- app/webpack/observations/show/components/annotations.jsx
> fix: use correct label for Annotations agree button

- app/assets/javascripts/jquery/plugins/inat/user_autocomplete.js.erb
- app/models/project.rb
- app/webpack/projects/form/components/project_form.jsx
- app/webpack/projects/form/form_reducer.js
- spec/models/project_spec.rb
> fix: allow removal of admins from collection and umbrella projects on projects/edit

- app/models/user.rb
- spec/models/update_action_spec.rb
> fix: show own ident for dashboard notification re: subsequent ident

- app/assets/stylesheets/taxa/show.scss
- app/webpack/taxa/show/components/charts.jsx
> feat: highlight current month on seasonality graph

- app/assets/javascripts/jquery/plugins/inat/photo_selectors.js
> fix: restore photo search for guide taxa

- app/assets/javascripts/jquery/plugins/inat/project_autocomplete.js.erb
> fix: ensure obs/show project chooser only shows your projects

- tools/seek_common_names.rb
Tested this with adding the new line directly into this file with vim on staging and successfully exporting the common names in the new language.
> feat: export Slovak from seek_common_names.rb

- app/controllers/taxon_changes_controller.rb
- app/models/taxon_change.rb
- app/views/taxon_changes/_form.html.haml
- app/views/taxon_changes/_show_change_taxon.html.haml
- app/views/taxon_changes/edit.html.haml
- app/views/taxon_changes/index.html.haml
- app/webpack/taxa/show/components/taxon_change_alert.jsx
- config/locales/en.yml
- config/routes.rb
- db/migrate/20250826232001_add_status_to_taxon_changes.rb
- db/structure.sql
- spec/models/taxon_change_spec.rb
linear ticket
https://linear.app/inaturalist/issue/WEB-795/add-withdrawn-status-to-taxon-changevs
functional spec:
https://docs.google.com/document/d/194OQCzS946Sb8mYqzU4KhO2DbaCv3nCEmEEpepQ0qB0/edit?tab=t.0
> Withdrawn state

- app/assets/stylesheets/index.scss
- app/views/shared/_header.html.haml
donate button on logged out header for iNat site only
https://linear.app/inaturalist/issue/WEB-804/add-donate-button-to-logged-out-header
> Logged out header donate button

- app/models/observation.rb
- app/webpack/observations/show/components/assessment.jsx
- app/webpack/observations/show/components/quality_metrics.jsx
- config/locales/en.yml
WEB-633
Closing the issue will require reassessing all existing RG obs, with the anticipated impact being ~0.25% of RG obs.
> feat: require Community and Observation taxon to match for RG
