inaturalist/inaturalist

app/assets/javascripts/inaturalist/map3.js.erb, app/assets/stylesheets/observations.css.scss, app/views/observations/_observation_component.html.erb
Scott noticed that the map infowindows were not loading. Not sure why this started happening now, but the `iw.content = ` expression is no longer working so I updated them to `iw.setContent()`. I also noticed recently the info windows almost always had scrollbars, so there are some CSS tweaks to fix that.
=> Fixes map infowindows; also tweaks their style to get rid of scrollbars

public/robots.txt
allow archive.org's wayback machine to create historical archives of the
inaturalist project.
=> explicitly allow the archive.org indexer

app/models/flickr_photo.rb, app/models/taxon.rb, config/environments/prod_dev.rb, lib/flickr_cache.rb, spec/lib/flickr_cache_spec.rb
Caching the photo search, and subsequent getSizes on all resulting images, as generated by taxa#photos. Should work with any Flickraw call (e.g. replace `flickr.photos.getSizes(photo_id: 1234)` with `FlickrCache.fetch(flickr, "photos", "getSizes", photo_id: 1234)`)
=> Caching some Flickr API requests

app/controllers/observations_controller.rb, app/es_indices/observation_index.rb, app/es_indices/place_index.rb, app/es_indices/project_index.rb, app/es_indices/taxon_index.rb, app/es_indices/update_index.rb, app/models/update.rb, db/migrate/20150421155510_create_updates_index.rb, lib/tasks/es.rake, spec/controllers/users_controller_api_spec.rb
This has a migration that will delete all updates older than 2014-11-01, which can take a few minutes. There may be some query locking that happens during the delete, so we should release this at a slow time, or put up the maintenance page for a few minutes while it runs. The Updates ES indexing will need to be kicked off manually after the deploy
=> Added the Updates ES index logic

config/initializers/time_zone_codes.rb
This is because Brisbane doesn't have daylight savings. This might be better changed to somewhere that does (for example, Sydney or Melbourne).
=> Removed Brisbane "Daylight Savings"

config/locales/fr.yml
Some more translation work as requested by James.
I figured I could open a PR for `master` since this only affects the french yml file — let me know if you'd rather have it opened against `i18n`.
Thanks!
=> Add missing French translations for Project join page

app/controllers/facebook_controller.rb
I got [this page](https://calm-ridge-9213.herokuapp.com/facebook/) loading as our [facebook canvas page](https://apps.facebook.com/inaturalist). I tried simulating several differences in our [broken endpoint ](http://www.inaturalist.org/facebook/)to see if I could break it (e.g. not having the FB js directly below the javascript)
The only difference I think might be breaking things on our end is the [default X-Frame-Options that Rails 4 added](http://stackoverflow.com/questions/16561066/ruby-on-rails-4-app-not-works-in-iframe).
Lets see if this works...
=> added X-frame exception for facebook endpoint

app/controllers/users_controller.rb, app/models/identification.rb, app/models/user.rb, app/views/users/edit.html.erb, config/locales/en.yml, lib/has_subscribers.rb, spec/models/user_spec.rb
Add preference to stop receiving notifications about redundant IDs.
=> Supress redundant IDs

tools/globi_observation_links.rb
I used https://developer.mozilla.org/en-US/docs/Web/API/History/pushState to allow for search ? in url instead of hash / anchor. Apparently, search engines crawl search ? but not hashes.
Thanks!
=> change hash # to search ? to allow for crawling

app/views/observations/show.html.erb, app/views/quality_metrics/_quality_metrics.html.erb, config/locales/en.yml
In another attempt to reduce the confusion causing people to vote yes on 'Community can improve/confirm ID?' AKA 'Still needs ID', I moved it up with the rest of the community ID pieces and have it not display if the obs is not a research grade candidate or the obs already has a community ID of species or lower. If the obs is needs ID but there are no votes yet, 'Yes' is hidden (to prevent people proactively voting yes)
I also consolidated the 'appropriate?' logic which appeared below licensing and was mostly repeated again in the data quality assessment into the data quality assessment
=> Made former 'Still needs ID?' conditionally display and deduped Appropriate UI

app/models/project.rb
@pleary, do you think this would kill performance for the aggregator? I'm trying to prevent it from creating the same project observation twice. Not entirely sure why it would be doing that, but maybe it's running on multiple machines at the same time?
=> Trying to add obs from the aggregator in a transaction (#996)

app/controllers/welcome_controller.rb, app/models/site.rb, spec/controllers/welcome_controller_spec.rb
This used to be controlled via the `config.yml` file, but this change will allow site admins to change it from the website.
=> Made home wiki page depend on Site preference.

app/controllers/observations_controller.rb, app/models/emailer.rb, app/models/mushroom_observer_import_flow_task.rb, app/views/emailer/moimport_finished.html.haml, app/views/observations/moimport.html.haml, config/routes.rb
A quick and dirty tool for importing observations from Mushroom Observer. Not intended to be publicly linked or really even kept around for that long.
=> Mushroom Observer Import

app/controllers/application_controller.rb, app/models/local_photo.rb, app/views/photos/show.html.erb, config/initializers/paperclip.rb
Force paperclip to check the content type of the file instead of relying on the file name. This should prevent us from storing photo files without extensions and deal with some issues with Twitter previews. Older photos can still be repaired and rotated, but any future code dealing with the `path` or `url` of past photos attachments will need to re-download the image referenced in `original_url` before doing any work.
=> Content type detection

app/controllers/observations_controller.rb, app/controllers/shared/lists_module.rb, app/models/check_list.rb, app/models/list.rb, app/models/listed_taxon.rb, app/models/taxon.rb, app/views/check_lists/show.html.erb, tools/listed_taxa_from_csv.rb, tools/rebuild_tree.sh
Relying on joining with taxa and using taxa.ancestry. There are 470k taxa and 8.1M listed_taxa so we're using a little extra space by duplicating ancestry in LT. But the wort part is all the delayed jobs we create to update LT.taxon_ancestor_ids when taxa change. This will get rid of all of those jobs.
This will not yet remove LT.taxon_ancestor_ids since that would take a while to compute again if there were a problem. We can create a migration to remove that column if this deploy works well for a while
=> Stop using listed_taxa.taxon_ancestor_ids

config/locales/en.yml
Fixed occurrences of two spelling errors in the english language configuration file (en.yml) :
- recieve was changed to receive
- elses was changed to else's
=> Fixed spelling errors: recieve and elses

app/models/deleted_photo.rb, app/models/photo.rb, db/migrate/20160913224325_add_fields_to_deleted_photos.rb, db/structure.sql, lib/tasks/inaturalist.rake
- Adds 2 columns to deleted_photos: `removed_from_s3` and `orphan`
- Adds a rake task to delete orphaned photos, creating DeletedPhotos with `orphan=true`
- Updates `delete_expired_photos` to delete orphans from s3 after just 1 month, and also sets `removed_from_s3` on DeletedPhotos purged from S3
=> Purging photos

app/models/user.rb, spec/models/user_spec.rb
I've clarified the error message when signing up with an invalid login name, and prevent suggesting a login beginning with a number for new OAuth accounts to address #1139.
I've used this to get familiar with the code, happy to know if I'm in need of more schoolin'.
=> Do not suggest a login beginning with a number (#1139)

app/models/taxon_range.rb, spec/models/taxon_range_spec.rb
I think the cause of #1127 is that the method to generate the geometry and geojson is never called.
I added an after_save trigger to generate the geometry from KML or vice versa. It seems to fix the issue, but would break anything that expects a TaxonRange in a state where just one of the two fields is blank. I didn't find such a case other than in the existing model spec, but I'm still getting familiar with the app.
=> Build geometry or KML for a taxon range after saving (#1127)

app/controllers/observations_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/users/edit.html.erb, config/initializers/paperclip.rb, db/migrate/20160929155608_restore_user_icon.rb, db/structure.sql, spec/controllers/observation_controller_api_spec.rb, spec/controllers/users_controller_api_spec.rb
Transition from the temporary state where we have both a `local_icon` and `s3_icon`, back to a stable state with a single `icon` which lives in S3
=> User icons s3 cleanup

app/assets/javascripts/taxon_names/taxon.js, app/models/taxon_name.rb, app/views/taxon_names/taxon.html.haml, spec/models/taxon_name_spec.rb
I experimented with a nil default for taxon name position, but hit sorting comparison errors.
In this alternative, new taxon names get created with position equal to the number of names for the taxon (not including itself). This can create gaps, but sorts correctly, and the current situation can create gaps already. There also seem to be fallback orderings by ID in place that handle duplicate positions.
When the "Manage names" ordering interface is loaded, name positions are reset to be consecutive starting at zero for the default as the original poster suggested.
=> Position new taxon names after existing ones (#1125)

app/assets/javascripts/jquery/plugins/inat/taxon_autocomplete.js.erb, app/controllers/taxa_controller.rb, spec/controllers/taxa_controller_spec.rb
It looks like at least part of the problem in #1067 is that there is no default for options.perPage on external searches. This is generating a querystring with per_page=undefined, and that never shows results. This PR adds a default value of 10 like the internal request.
=> Provide a default per page value for external taxon searches (#1067)

app/controllers/shared/lists_module.rb, app/models/life_list.rb, app/models/list.rb, app/models/project.rb, app/models/project_list.rb, app/models/project_observation.rb, app/views/lists/show.html.erb, db/migrate/20161110221032_remove_show_from_place_from_project.rb, db/structure.sql, spec/models/project_list_spec.rb
closes #1190 - I also pulled out project.show_from_place which hasn't been used in the UI since we stopped displaying project_lists by default but was still hanging around
=> stop updating project lists with taxa from project observations

tools/apidoc/api.rb
A handful of small typos jumped out at me while reading the API documentation.
=> Minor typo fixes in API docs.

app/assets/stylesheets/taxa/show2.css.scss, app/controllers/taxa_controller.rb, app/models/quality_metric.rb, app/webpack/shared/components/cover_image.jsx, app/webpack/taxa/shared/components/taxon_photo.jsx, app/webpack/taxa/show/components/photo_preview.jsx, spec/controllers/quality_metrics_controller_api_spec.rb, spec/models/quality_metric_spec.rb
When we have the dimensions for a photo and it's so wide that it will probably get cropped by having it cover the available space on the taxon page, have the photo preview contain the photo instead.
=> Taxon page photo contain

app/assets/stylesheets/taxa/show/wikipedia.css.scss, app/es_indices/place_index.rb, app/models/place_geometry.rb, db/migrate/20170110185648_add_bounding_box_to_places_index.rb, db/structure.sql
This adds the bounding box of the place geometry to the places index. It basically does the same thing as the geom, so its in the index as a GeoJSON polygon, and thus has some redundant data, particularly the first and last coordinates. Happy to change that and use the Google-style sw / ne point format if that's preferable.
The intent here is to have the bounding boxes available to anyone consuming places so they can do simple geo stuff and zoom maps accordingly. Proximate need is to zoom the map on the taxon page appropriately when the user chooses a place.
=> Add bounding box to places index

app/controllers/identifications_controller.rb, app/models/taxon_change.rb, app/models/taxon_split.rb, app/views/taxon_changes/show.html.haml, lib/observation_search.rb, spec/helpers/make_helpers.rb, spec/models/observation_spec.rb, spec/models/taxon_split_spec.rb
Instead of ignoring identifications for taxon splits where the choice of output taxon is uncertain, this change adds new IDs of the closest common ancestor taxon of all the output taxa. Closes #1235.
=> Common ancestor IDs for ambiguous splits

app/models/listed_taxon.rb, app/models/observation.rb, app/models/quality_metric.rb, app/views/quality_metrics/_quality_metric_row.html.erb, config/locales/en.yml, spec/models/observation_spec.rb
Automatically add a captive vote to observations in places where there are mostly captive observations of that taxon. More specifically, vote captive if the community taxon or taxon is genus or lower AND there are at least 10 observations of that taxon in the smallest enclosing county, state, or country AND more than 80% of those observations have been marked as captive. So pretty conservative, actually, but should deal with the most common cultivated plants, dogs, cats, etc.
=> Automatic captive

app/assets/javascripts/application.js.erb
This very minor thing was bugging me.
When I'm searching something up on inaturalist using the header search box (see below), the header submenus disappear if you're typing something in but accidentally move the cursor outside of the dropdown box.
This change prevents the box from closing if the user is typing something in.
=> Prevent submenus from closing if the user is using the search inputs

app/controllers/users_controller.rb, app/controllers/welcome_controller.rb
The Canada site wants different announcements if the locale is French or English. Currently, if the Site is set, it fetches announcements of all locales for that site. This change is meant to only fetch announcements with a specific locale for a site if announcements have both site and locale set.
=> site specific announcements can also be locale specific

app/controllers/application_controller.rb, app/models/site.rb, config/initializers/logstasher.rb
Uses the Accept-Language HTTP header to set the user's locale if it hasn't been set already.
=> Set the locale from the Accept-Language header

app/controllers/check_lists_controller.rb, app/controllers/taxa_controller.rb, app/es_indices/taxon_index.rb, app/models/taxon_name.rb, spec/spec_helper.rb
Makes names in the taxon index a nested type to support locale- and place-specific weighting in the node API. See https://github.com/inaturalist/iNaturalistAPI/issues/115 and https://github.com/inaturalist/iNaturalistAPI/issues/117
Note: this will require taking down the site to re-create the taxon index.
=> Nested taxon names

app/controllers/users_controller.rb, app/es_indices/observation_index.rb, app/models/listed_taxon.rb, app/models/observation.rb, app/models/place.rb, app/views/layouts/bootstrap.html.erb, app/webpack/observations/identify/actions/current_observation_actions.js, app/webpack/observations/identify/ducks/suggestions.js, app/webpack/observations/show/ducks/observation_places.js, spec/lib/elastic_model/indices/observation_index_spec.rb
Closes #1663 by making the `place_ids` attribute in the observation index just the publicly visible places, and adds a new `private_place_ids` for all the places visible to the observer. This will involve re-indexing all geo-referenced observations, but I think we can do that without taking down the site, since the `place_ids` attribute will continue to work. People searching for obs in contexts where they should see private coordinates will miss some observations for a week, I guess, until the indexing is complete and we've released the changes to the node API.
=> Separate place IDs in observation index

app/es_indices/place_index.rb, app/models/observation.rb
This does address my concern of improving scores for large places in universal search, but it's also kind of a messy solution in which places get re-indexed infrequently and generally only in response to obs updates (not creation). Are we ok with that? It's fine for my purposes since I only need rough numbers, but if someone is expecting these counts to be exactly accurate they're going to disappointed.
=> Try adding observations_count to places index

app/es_indices/identification_index.rb, app/es_indices/observation_index.rb, app/es_indices/project_index.rb, app/es_indices/user_index.rb, spec/lib/elastic_model/acts_as_elastic_model_spec.rb, spec/lib/elastic_model/indices/project_index_spec.rb, spec/lib/elastic_model/indices/user_index_spec.rb
Add `spam` attribute to several indices of models can that can be spam, and added `suspended` to the user index. Closes #1735
=> Index spam status

app/models/year_statistic.rb, lib/darwin_core/archive.rb, lib/inat_api_service.rb, tools/dwca.rb
This add options to tools/dwca that allows creating a duplicate archive which includes a taxa.csv file that includes all active taxa, and allows sending a POST request to an endpoint when that archive is updated. This also modifies parameters for INatAPIService methods to use a hash of options rather than an ever increasing list of parameters
=> add dwca options for generating file with all taxa, posting archive

app/models/annotation.rb, app/models/controlled_term_taxon.rb, app/models/observation.rb, app/models/taxon.rb, config/locales/en.yml, db/migrate/20180518231918_add_foreign_key_indices_to_annotations.rb, db/structure.sql, spec/models/annotation_spec.rb
Removes taxon-specific annotations when taxonomy or taxon associations change.
=> Remove annotations when they are no longer relevant (closes #1696)

app/controllers/application_controller.rb, app/controllers/comments_controller.rb, app/controllers/listed_taxa_controller.rb, app/controllers/messages_controller.rb, app/controllers/observation_photos_controller.rb, app/controllers/observation_sounds_controller.rb, app/controllers/observations_controller.rb, spec/controllers/observation_photos_controller_api_spec.rb
Hopefully this won't be too disruptive, but I suspect it will change some response statuses from the API.
=> Use 403 Forbidden status  when returning permission errors

app/controllers/identifications_controller.rb, app/models/taxon_name.rb, spec/controllers/identifications_controller_api_spec.rb, spec/models/taxon_name_spec.rb, spec/models/taxon_spec.rb
Some more complications for common name choice (see https://www.inaturalist.org/journal/bodofzt/18372-canada-usa-north-america and https://groups.google.com/d/topic/inaturalist/P8iNMY0WYNM/discussion). Now priority looks like this:
1. Name that matches both language and the exact place (e.g. user's place is Mexico and name's place is Mexico, but not user's place is Mexico and name's place is North America)
1. Name that matches the exact place
1. Name that matches locale and place (including ancestor places)
1. Name that matches locale
One things that are no longer happening are showing names that match an ancestor place but not a locale, e.g. showing a Mexican user an English name b/c that name was associated with North America. Another is that we are not showing a language from an …
=> Locale priority for common names

app/controllers/taxa_controller.rb, app/controllers/taxon_changes_controller.rb, app/models/taxon.rb, app/models/taxon_change.rb, spec/models/taxon_merge_spec.rb, spec/models/taxon_spec.rb, spec/models/taxon_swap_spec.rb
The goal of this is to try to reduce the number of active taxa with ancestries that include inactive nodes by more strongly validating what curators can do. Specifically, this should make it so that:
1) taxon changes won't commit if the inputs have active children unless they are swaps/merges and 'move children' is checked (e.g. curator should manually move children before committing change)
1) active taxa can't be created/updated to be active with inactive parents (unless inactive parent is an output of a draft change since curators may have to manually move children to inactive output taxa before committing as described above)
2) taxa can't be updated to inactive if they have active children
@kueda I've done a pretty rigorous job testing this and playing with it on staging but would …
=> Inactive taxa validations

app/controllers/taxon_changes_controller.rb, app/models/taxon_change.rb, spec/models/taxon_merge_spec.rb, spec/models/taxon_swap_spec.rb
Since adding the taxon change validations a few weeks ago, a few common legit use cases surfaced that the validations were preventing. They were:
1) merging a species and all its active spp into some other taxon - which is more efficient than multiple taxon changes - was prevented by the active children validation
2) swapping a sp into its synonymous ssp was prevented by the rank level validation
this branch contains caveats for both of those cases
=> Taxon change validation updates

app/assets/javascripts/inaturalist/map3.js.erb, app/controllers/identifications_controller.rb, app/controllers/taxa_controller.rb, app/es_indices/identification_index.rb, app/es_indices/observation_index.rb, app/es_indices/taxon_index.rb, app/models/observation.rb, app/models/observation_field_value.rb, app/models/photo.rb, app/models/shared/license_module.rb, app/models/sound.rb, app/models/taxon.rb, app/models/user.rb, lib/observation_search.rb, spec/controllers/identifications_controller_api_spec.rb, spec/controllers/observation_controller_api_spec.rb, spec/controllers/users_controller_api_spec.rb, spec/lib/elastic_model/indices/observation_index_spec.rb, spec/models/local_photo_spec.rb, spec/models/project_user_spec.rb, spec/models/taxon_spec.rb
Attempt to make the obs index smaller. Removes some things from the obs index (identifications, photos, project observations) and adds some non-nested items as needed to keep functionality. Also modifies obs indexing to fetch listed taxa in bulk for assessing introduced, native and endemic. Modify ES queries as needed to work with index changes.
=> ES index updates

app/es_indices/observation_index.rb, lib/elastic_model/acts_as_elastic_model.rb
- unset associations loaded only for indexing when indexing is done
- periodically force garbage collecting after indexing individual instances
=> Free up memory during non-bulk indexing

app/assets/javascripts/i18n/translations.js, app/webpack/taxa/show/components/similar_tab.jsx, app/webpack/taxa/show/components/taxon_page_tabs.jsx, app/webpack/taxa/show/containers/similar_tab_container.js, app/webpack/taxa/show/containers/taxon_page_tabs_container.js, config/locales/en.yml
Works by looking for misidentifications of species in the genus, not of the genus itself, so it's kind of a half-measure.
=> Shows the Similar tab on taxon pages for genera

app/assets/javascripts/inaturalist/map3.js.erb, app/assets/javascripts/wax.g.js
- Updates wax.g to allow for configurable tile size
- Use 512x512px tiles for non-interactive polygon tiles
=> Larger polygon tiles

Gemfile, Gemfile.lock
This is what is currently confusing Dependabot.
=> Specify Gemfile references as refs, not branches

app/controllers/users_controller.rb, app/models/emailer.rb, app/views/emailer/_footer.html.erb, app/views/emailer/_header.html.erb, app/views/emailer/parental_consent.html.haml, config/initializers/devise.rb, config/locales/en.yml, config/routes.rb, lib/devise_application_json_web_token.rb, lib/devise_json_web_token.rb, lib/json_web_token.rb, spec/controllers/users_controller_api_spec.rb, test/mailers/previews/emailer_preview.rb
Adds an endpoint our own apps can use to send an email to a potential parent asking them to create an account for their child. Email content and any further restrictions may need some more work, but this is probably ready for developer testing, at least.
This has the kind of weird consequence that when you make a request to the Rails app with our application JWT, it will create a `current_user` but with an ID of `-1`. Devise / Warden seem to want some kind of user object, and this allows us to see that auth was successful but that the "user" is anonymous. If this seems like too much of a risk, I think we could redo this so the auth part just skips Devise no `current_user` gets populated.
=> Parental consent email endpoint

app/assets/stylesheets/users/show.scss, app/controllers/donate_controller.rb, app/controllers/users_controller.rb, app/models/local_photo.rb, app/models/user.rb, app/views/donate/monthly_supporters.html.haml, app/views/users/_show.html.haml, app/views/users/edit.html.erb, config/environments/development.rb, config/locales/en.yml, config/routes.rb, db/migrate/20190820224224_add_donorbox_plan_columns_to_users.rb, db/structure.sql, tools/donorbox-plans.rb
Adds a Monthly Supporters page and the ability for Monthly Supporters to display a badge on the profile page. At present requires `test=monthly_supporters` param to view. Closes #2369, #2367,  and #2368.
=> Monthly Supporters

app/assets/javascripts/i18n/pluralizations.js, app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/users/edit.html.erb, app/webpack/stats/year/components/growth.jsx, app/webpack/stats/year/components/identifications.jsx, app/webpack/stats/year/components/observations_grid.jsx, config/environments/production.rb, config/locales/en.yml
Addresses #2490. The setting is currently only available at /users/edit?test=no-tracking until translators have a shot at the large amount of text.
=> No tracking preference

app/assets/javascripts/i18n/pluralizations.js, app/assets/javascripts/i18n/translations.js, app/assets/stylesheets/stats/year.scss, app/models/year_statistic.rb, app/views/stats/year.html.haml, app/webpack/stats/year/components/app.jsx, app/webpack/stats/year/components/observations.jsx, app/webpack/stats/year/components/streaks.jsx, config/locales/en.yml
Adds an observation streaks chart to Year In Review for sites (wasn't that interesting for most individual users). Also fixes a bug with JS pluralization breaking on delimited but not separated numbers like "2,354"
=> Observation Streaks for Year In Review

app/webpack/observations/identify/actions/current_observation_actions.js, app/webpack/observations/identify/actions/identifiers_actions.js, app/webpack/observations/identify/actions/observations_actions.js, app/webpack/observations/identify/containers/follow_button_container.js, app/webpack/observations/identify/reducers/observations_reducer.js, app/webpack/observations/show/components/follow_button.jsx, app/webpack/observations/show/containers/follow_button_container.js, app/webpack/observations/show/ducks/observation.js, app/webpack/observations/show/ducks/subscriptions.js, app/webpack/shared/components/observations_grid_item.jsx, config/webpack.config.js, package-lock.json
* try to only fetch subscriptions when you follow/unfollow someone, not every
time you view a tab with the Follow button
* keep a local cache of places, try not to re-fetch lots of places all the time
* Don't refresh the list of top identifiers if the current user isn't on it
Note that following a user from obs/show or Identify was broken before this
commit.
=> Some attempts to cut down on the number of requests made in Identify

app/models/observation.rb, spec/models/observation_spec.rb, tools/export_multitier_vision_data.rb
Tracing through the error, I found that in this case the observation started with a private geoprivacy, so its lat/lng were nil, and then when setting the geoprivacy to open, with the taxon still being protected in the observation area, it would get to this point in `obscure_coordinates` with its lat/lng having been re-assigned in code to patch the private coords, but the `latitude_was` and `longitude_was` were nil. That leaves the obs in a state where geoprivacy is open, but the public coordinates are nil instead of being obscured.
I made a spec for that case, and all specs are passing, but it would be great to get a second set of eyes on this in case there are some consequences of this change I'm not seeing.
=> Potential fix for #2330

app/views/guides/index.html.haml, config/locales/en.yml
Fixes #2493 by adding a notice box to the guides page with the message suggested by tiwane.
=> Add banner to /guides noting its deprecated status

app/controllers/messages_controller.rb, app/models/message.rb, app/views/flags/_flag.html.haml, app/views/flags/global_index.html.haml, app/views/flags/show.html.haml, app/views/messages/show.html.haml, config/locales/en.yml, db/migrate/20200117011717_add_flaggable_content_to_flags.rb, db/structure.sql, lib/acts_as_flaggable/acts_as_flaggable.rb, lib/acts_as_flaggable/flag.rb, spec/models/flag_spec.rb, spec/models/message_spec.rb
* ensures messages do not get deleted after flagging
* messages remain visible after flagging
* flags persist after the flaggable record gets deleted
* flags preserve the main text attribute of the flaggable record so some history of what was actually flagged gets preserved even if the owner of the flaggable record deletes that record; this content is visible to curators except for messages
=> Revise message flagging

app/models/controlled_term.rb, app/models/observation_field.rb, app/models/photo.rb, app/models/place.rb, app/models/post.rb, app/models/sound.rb, app/models/taxon.rb, app/models/user.rb, db/migrate/20200116234248_add_uuid_columns.rb, db/structure.sql, lib/acts_as_flaggable/flag.rb
Adds UUIDs to several more models that are accessible via the API. Holds off on populating these columns for large tables so we can do that without hanging the site.
=> Add UUID columns to more tables

lib/elastic_model/elastic_model.rb
Specifically, it maps the Hawaiian ʻokina to a blank, which is how our analyzers
seems to treat apostrophes. This means searches for taxon names with the ʻokina
can be performed with the ʻokina, with an apostrophe, or without either.
This will require recreating and reindexing the Taxon index, so we'll have to pull this in and perform this the next time we have downtime.
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-mapping-charfilter.html
Closes #2560
=> Adds a char filter to most ES analyzers for custom char mapping

app/models/annotation.rb, app/models/place.rb, app/models/site.rb, app/views/sites/_form.html.haml, app/views/sites/show.html.haml, db/migrate/20200220211829_add_extra_place_id_to_sites.rb, db/structure.sql, tools/export_site_data.rb
Adds an additional place association on sites so they can support data exports from two places (e.g. a national boundary and an EEZ). Also includes data from several other models in the export.
Closes #2572 
Closes #2580
=> Additional site data in exports

bin/setup
Should allow simplifying the Rails setup instructions in the [Development Setup Guide][1].
Editing some of these files will likely be needed but duplicating N+1 config file
is needlessly tedious.
[1]: https://github.com/inaturalist/inaturalist/wiki/Development-Setup-Guide#installing-inat
=> Move configuration file copying to bin/setup

bin/setup
One less thing to copy and paste from the [Development Setup Guide][1] (which is error prone) by hand when it can be done (and updated in one place) through `bin/setup`.
I've included some logic to abort if `createdb` is not available as a shell command with some error feedback in that case:
> Error: PostgreSQL needs to be installed before setup can be completed.
[1]: https://github.com/inaturalist/inaturalist/wiki/Development-Setup-Guide#set-up-the-template-database
=> Add Postgres database template setup to bin/setup

config/initializers/delayed_jobs_serialization.rb, spec/initializers/delayed_jobs_serialization_spec.rb
only serialize model primary keys to reduce handler size, since all Delayed Jobs needs is the primary key
=> DJ improvements

lib/darwin_core/occurrence.rb
For consistency with the rest of Darwin Core, we capitalized "ID" in the term name http://rs.gbif.org/terms/1.0/identifiedByID
=> Correct case of identifiedByID

app/assets/javascripts/inaturalist/map3.js.erb, app/webpack/taxa/show/components/taxon_page_map.jsx
Adds a layer of captive obs to the taxon page map. Also
* layer colors in the legend
* uses default orange color for obs points as well as the grid, instead of switching to iconic taxon color for points
@pleary, one question I have before merging: would it be preferable to make the change to point colors in the API? Not sure which is better re: tile caching.
=> Captive layer

app/assets/javascripts/application.js.erb, app/assets/javascripts/jquery/plugins/inat/taxonmap.js.erb, app/views/layouts/application.html.erb, app/views/layouts/bootstrap.html.erb
Modifies how we fetch message and notification counts for the header for logged-in users. The two have been combined into one endpoint implemented in the node API
The taxa/map_layers endpoint has also been moved to the node API and JS updated accordingly here.
These three endpoints account for nearly 30% of all Rails requests. They are all currently relatively fast, and might see some small performance improvements when moved to node, particularly with two of them combined into one call. But the main benefit will be getting these common requests out of the Rails Passenger queues and into node/express.js
=> Use the API for common quick count requests

app/assets/javascripts/i18n/translations.js, app/assets/stylesheets/projects/new2.scss, app/controllers/projects_controller.rb, app/webpack/projects/form/components/project_form.jsx, app/webpack/projects/form/components/shared_form.jsx, app/webpack/projects/form/containers/project_form_container.js, app/webpack/projects/form/form_reducer.js, app/webpack/shared/components/user_image.jsx, config/locales/en.yml, spec/controllers/projects_controller_api_spec.rb
Allows the current project owner to assign one of the managers (aka admins) as the owner, and in doing so forsaking the ability to delete the project or assign a different owner, as well as causing the "created by {user}" text to be inaccurate.
Closes #1968
=> Allow collection project owner to be changed

app/views/observation_fields/merge.html.haml
#2677
I think this will fix the js error and restore the `jquery.chooser` functionality. However since that introduces a functional change to the page, let me know what you think and if we want to tighten it up any.
=> Fix js error on observation field merge page

app/assets/javascripts/i18n/translations.js, app/webpack/observations/uploader/actions/actions.js
#2623 
This should handle file limits for drag and drop, combine cards, and move a single photo from one card to another.
Let me know if I've missed any other ways these might exceed the limit.
=> Limit photos uploaded or combined in upload to observations

app/controllers/shared/lists_module.rb, app/models/list.rb
#2688
This would be the proposed fix should you feel ok with adding additional (short-lived) cache keys for csv exports.
Also fixes a small issue in `generate_csv_cache_key`:
```ruby
if options[:view] = "taxonomic"
```
I don't think this should be assignment, but rather comparison operator.
=> 2688 checklist export with user locale

config/locales/en.yml
Changing the description of taxon swap from "1-to-1 name change" to "Replace input taxon with output taxon".
=> Clarifying description of taxon swap, per issue 2276

app/assets/javascripts/jquery/plugins/inat/taxon_autocomplete.js.erb
#2710 
Edit observation taxa autocomplete uses a custom message in the result list for a placeholder. This allows that to stay but still use the placeholder text that was assigned when submitting the observation.
React uploader taxa autocomplete is unaffected.
=> Set placeholder title in edit obs

app/controllers/observations_controller.rb, app/models/place.rb, app/views/observations/index.html.haml
This attempts to improve the Open Graph tags we include at https://www.inaturalist.org/observations with some customization based on the search parameters. That requires loading some data in Rails, which might be too much of a performance burden to bear, hence the PR for review. If we don't want to do that, we can show the generic site description as the `og:description` instead.
=> Attempts to improve og tags on obs search

app/webpack/shared/components/text_editor.jsx, app/webpack/shared/components/text_editor_format_button.jsx
#2722 
This adds mousetrap bindings for bold, italics, and links in the `TextEditor` component. The use of refs required converting `TextEditorFormatButton` from a functional component. 
Additionally, this can't really be handled in the `keyboard_shortcuts.js` file as we need to bind to an element rendered by the component rather than the default `document`. 
I'm not 100% certain this is the cleanest approach, but it seems to click-test well. Open to any suggestions to make it more idiomatic.
=> Add mousetrap bindings for bold, italics, and links in TextEditor

app/webpack/observations/identify/actions/identification_actions.js, app/webpack/observations/show/components/activity_item.jsx
* Removed agree button from ident activity item when
* ident is not leading
* observation is RG
* Disabled agree keyboard shortcut in Identify when
* it's your obs
* obs is RG
* CID exists and is species or lower
=> Removed agree functionality in a few places

app/views/users/registrations/_form.html.haml, config/locales/en.yml
#2745 
Pretty straightforward addition. Only one thing to note: ToS, PP, and CG are not being audited the same way GDPR compliance is (and I don't imagine it necessarily needs to be, but let me know if it does) and therefore this is outside of the form-builder as well as missing any backend validation. 
Although it would be kind of ridiculous you could, say, edit the DOM and submit the form to create a user without actually checking the box. However, unlike the compliance around GDPR there is the explicit:
> By accessing or using any part of the Website, each user ("You", "Your" or "User") agrees to the terms and conditions of this Agreement.
so I don't really see a problem with this.
Maybe you can check it out if you have the time @pleary? If not, I'm sure kueda can upon returning.
=> Add TOS checkbox to signup

app/controllers/observations_controller.rb
#2754 
Duplicating an observation will no longer bring over observation fields from the original. 
There was some discussion regarding duplicating tags, however this does not yet add that in.
=> Remove duplicating observation fields when duplicating observation

app/views/observations/new.html.erb
#2765 
Changes "Cancel" button to consistently return to original observation if duplicating.
=> Modify path for cancel button when new observation is a result of dup

app/webpack/observations/show/components/observation_field_input.jsx
#2767 
Provide numeric input for numeric type observation fields on the Observation Show page. 
With existing code submission of the numeric observation field would persist and show up on reload. However, any attempt to edit the observation would show the field blank as it could not be coerced into an `input type="number"`. The `observation/new` path never allowed irregular data.
With this change, when I changed one such value to a non-numeric value it shows up just fine on the observation so this shouldn't have an issue with any existing irregular data and it will be preserved and shown on the Observation Show page. As before, it will show up blank on the "Edit" page.
Can you see any issue with users using numeric observation fields to store non-numeric data and no longer being able to …
=> Provide numeric input for numeric type obs fields

app/models/identification.rb, spec/models/identification_spec.rb
#2751 
Fixes first issue
> An identification added to an observation without any current identifications should not be a disagreement
=> Prevent disagreeing with non-current identifications

app/models/taxon_name.rb, config/locales/en.yml
What do you think of this @kueda for checking off a few boxes from #2675?
The first validation will check and recommend the English name for any lexicon we have a translation for.
The second validation will restrict custom lexicon names to the latin character set plus punctuation, spaces, and right now digits. Since these should all be English, we shouldn't allow other character sets through. Let me know if you want to tweak the regex though.
So before jumping further into the list on the path to cleaning up the data, I'd like to know what db constraints, indexes, etc. might be introduced non-disruptively and what kind of real data we will be looking at. In order to do so I was wondering if it would be possible to get an export of select columns (`name`, `lexicon`, and `taxon_id` and …
=> Add validations for custom lexicon for taxon names

app/models/taxon_name.rb, config/locales/en.yml, db/migrate/20200824210059_add_parameterized_lexicon_to_taxon_names.rb, db/structure.sql, spec/models/taxon_name_spec.rb
#2675
I think this is the next step to reducing lexicon variation as well as duplicate names in the same lexicon.
* The backfilling of `parameterized_lexicon` took 2-3 minutes for me if that needs to be a consideration in your planning on when to run the migration.
* Right now it's tough to put in the index as there are already several, albeit only a small fraction (2964/2M+), records that would violate the composite uniqueness constraint. It looks like most if not all are coming from imports. 
* Also, might be worth reexamining the role of `normalize_lexicon` now that `parameterized_lexicon` exists. I think the former will first change "Chinese (TraDitional)" -> Chinese (Tra Ditional)". With `parameterized_lexicon` this results in "chinese-traditional" and "chinese-tra-ditional". 
* …
=> Add parameterized lexicon to taxon_name

app/assets/stylesheets/observations/by_login.scss, app/helpers/application_helper.rb, app/views/facebook/options.html.erb, app/views/observations/by_login.html.erb
Minor alteration to /observations/:login so
1. Increasing font size does not hide text under the map
1. Content fills the whole screen
1. Map wraps to the bottom when the width of the screen won't fit both the table and the map side-by-side
Font size issues were causing issues for both people trying to increase the font size on the page and people viewing the site in languages where long word lengths were causing similar width problems.
It would have been nice to move this over the Bootstrap too, but ironically that would have negated the accessibility improvements, because our bootstrap styles currently hardcode the font sizes making them impossible for the user to increase. Fixing that will require removing the hard-coded base font sizes on the `body` tag and then adjust all other font …
=> Fluid /observations/:login layout

app/models/taxon.rb, spec/helpers/make_helpers.rb, spec/models/observation_spec.rb
As reported here https://forum.inaturalist.org/t/obs-with-only-subspecies-ids-can-get-stuck-without-a-cid/15992
The CID algorithm for an observation ignores inactive taxa
But if an taxon is activated the CID of its observations are not reassessed
This means that if a curator does the following set of actions which is common in curating taxa: (1) inactivates a taxon and moves it to a new taxon (this wipes the CIDs because moving a taxon reassesses CID and inactive taxa are ignored)
(2) reactivates the taxon
the CID's are not reassessed/restored because this doesn't happen when a taxon is activated
This pull request introduces a callback that reassesses the CIDs of obs associated with a taxon if the taxon is_active status changes
=> Reassess community taxa after taxon activation

app/models/identification.rb, app/models/listed_taxon.rb, app/models/observation.rb, app/models/observation_field_value.rb, app/models/taxon_change.rb, app/models/taxon_split.rb, spec/models/taxon_split_spec.rb
I altered taxon splits so that if one of the output taxa is the same as the input taxon the split is still allowed. It leaves the input taxon active and doesn't touch content (identificiations etc.) determined (by atlases) to stay with that taxon. Content determined to go to the other output taxon behaves normally.
The idea here is that with a taxon lump (e.g. Taricha torosa is folded into Taricha granulosa thereby broadening Taricha granulosa) we don't recommend making a new taxon for the broadened Taricha granulosa. Instead we simply swap Taricha torosa with Taricha granulosa and advise curators to make sure that any content may no longer match the broadened Taricha granulosa (e.g. taxon ranges, common names) be manually altered. And with lumps, IDs don't become misspecified - an ID of …
=> Taxon split with same input output

app/controllers/observations_controller.rb, spec/controllers/observation_controller_spec.rb
#2810 
This should gracefully handle any exceptions that come out of the OG description generation. I'm still concerned that these partial iso8601 params are not being parsed correctly for the obs retrieval being done on the front end, however let me know your thoughts. I suppose it's the difference of landing on the obs index with no results vs whale fail. `by_login` action still is parsing these dates correctly, so I think a similar approach could be taken by the angular front end.
FWIW I also have a WIP branch https://github.com/inaturalist/inaturalist/compare/main...todtb:2810-date-params-for-obs that would start to generate this description based on partial dates, but that I think is lower priority.
=> Handle malformed date params on obs index

app/views/users/curation.html.haml
#2822 
Adds links to the user curation page to view profile and a user's projects. 
The glance section didn't seem like the right fit for the profile link so it's up top as shown:
Hope this helps @tiwane
=> Add profile and project links to user curation page

app/models/post.rb, spec/models/post_spec.rb
#2818 
Adjusts `users.journal_posts_count` cache when post is destroyed (previously only when unpublished).
=> Account for destroyed posts in counter cache update

app/assets/stylesheets/taxa/show/wikipedia.scss, app/controllers/taxa_controller.rb, app/views/taxa/_description.html.haml, lib/taxon_describers/lib/taxon_describers/base.rb, lib/taxon_describers/lib/taxon_describers/eol.rb, lib/taxon_describers/lib/taxon_describers/wikipedia.rb, lib/wikipedia_service.rb, spec/lib/taxon_describers/wikipedia_spec.rb
Specifically, this uses HEAD requests to https://hub.toolforge.org to map the iNat production taxon ID to a Wikipedia URL in a specific locale, so even if that language's Wikipedia doesn't have a page corresponding to that name, we can still show Wikipedia content.
Note that this starts storing the page content *and* the URL in a 24-hour cache, but doesn't cache requests to the hub service with an `ApiEndpointCache` like we do for some other services, b/c this service doesn't actually return a request body to cache.
The hub service is hosted by Wikimedia so presumably it won't stress them out too much if we hit it a lot, but if it does we'll need to start pre-caching these data from Wikidata. Some notes on how best to get this data from Wikidata at …
=> Use Wikidata to fetch the correct Wikipedia taxon page

app/controllers/observations_controller.rb
Previously was injecting into search params which was overwriting edit
obs search params. Now injects into params if preferences are present.
#2848
=> Fix edit obs sort

app/assets/javascripts/i18n/translations.js, app/webpack/lifelists/show/components/details_view.jsx, app/webpack/lifelists/show/components/species_noapi.jsx, app/webpack/lifelists/show/util.js, config/locales/en.yml
#2870 
Dynamically changes count based on taxa in new lifelist. The count was
originally calculated in the 'species_noapi' component. Now it, along
with the taxa filter labeling logic, are in a shared util function.
=> Change lifelist count based on taxa

app/assets/javascripts/ang/controllers/observation_search.js, app/assets/javascripts/inaturalist.js.erb, app/assets/javascripts/inaturalist/map3.js.erb, app/assets/javascripts/jquery/plugins/inat/taxonmap.js.erb, app/assets/javascripts/projects/show.js, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, app/views/observations/by_login.html.erb, app/views/taxa/map.html.haml, app/views/taxon_changes/show.html.haml, app/webpack/observations/compare/components/map_comparison.jsx, app/webpack/observations/identify/components/observation_modal.jsx, app/webpack/observations/identify/components/suggestion_row.jsx, app/webpack/observations/identify/components/suggestions.jsx, app/webpack/observations/show/components/map.jsx, app/webpack/observations/uploader/components/location_chooser_map.jsx, app/webpack/projects/show/components/observations_map_view.jsx, app/webpack/projects/show/components/overview_map.jsx, app/webpack/projects/show/components/umbrella_map.jsx, app/webpack/taxa/show/components/taxon_page_map.jsx
This hits a [new logging endpoint](https://github.com/inaturalist/iNaturalistAPI/commit/558475671abf2de90323f712851ee814e5668959) most times we create a Google Map instance so we can investigate ways to cut down on use. This should monitor almost every Google Map on the site that goes through our custom `createMap` method in `map3.js.erb`, which means it's ignoring the location choose in the Uploader since that's using a third-party React component. The node endpoint is filtering by origin, which means it's denying all requests that don't come from inaturalist.org, so if the source of our extreme usage is on one of the partner sites we're going to miss that, but I figure this will at least get us started.
=> Monitor Google map creation

app/assets/javascripts/application_bundle.js, app/assets/javascripts/i18n/translations/.gitignore, app/views/layouts/application.html.erb, app/views/layouts/basic.html.haml, app/views/layouts/bootstrap.html.erb, app/views/observations/upload.html.haml, app/views/shared/_i18n.html.haml, ci/scripts/before_script.sh, lib/tasks/inaturalist.rake, spec/controllers/custom_projects_controller_spec.rb, spec/controllers/trips_controller_api_spec.rb
Creates separate JS files for translations in each locale instead of jamming them all into a single file and forcing everyone to download a bunch of stuff they'll never use. Tries to ensure that all locale files include the names of other locales in those locales, and to make sure that locale files for all relevant fallback locales get loaded (that means English is always loaded for everyone since it's the fallback of last resort).
Closes #2336
=> Separate locale JS files

app/webpack/observations/identify/components/suggestion_row.jsx, app/webpack/observations/show/components/app.jsx, app/webpack/observations/show/components/assessment.jsx, package-lock.json, package.json
Tries not to render parts of obs/show that are generally below the fold until the user scrolls to those areas. Note that this does not prevent API requests to fetch data for those parts of the page, but it should prevent unnecessary image loading.
=> Lazy-load parts of obs/show

app/webpack/shared/components/text_editor.jsx
Fixes https://github.com/inaturalist/inaturalist/issues/2738 where the comment textarea character counter would not disappear if the text was deleted with cmd+a then backspace. Furthermore, the counter wasn't even accurate if only a small amount of content was typed after deleting the original text.
=> Fixes char counter not behaving as expected

app/assets/javascripts/jquery/plugins/inat/generic_autocomplete.js, app/assets/stylesheets/autocomplete.scss, app/views/layouts/basic.html.haml, app/views/layouts/bootstrap.html.erb, app/views/observations/show.html.haml, app/webpack/observations/uploader/components/taxon_autocomplete.jsx, config/locales/en.yml
Like we've started doing in the Android app, this excludes not-nearby suggestions from the automated suggestions in the taxon autocomplete component (in situations where we're showing automated suggestions). Ideally this will reduce errors due to choosing the top automated suggestion when that is visually similar but not seen nearby).
This PR introduces this as an admin-only test.
=> Exclude not-nearby by default in taxon autocomplete

app/controllers/annotations_controller.rb, app/controllers/comments_controller.rb, app/controllers/flags_controller.rb, app/controllers/identifications_controller.rb, app/controllers/observation_field_values_controller.rb, app/controllers/observation_photos_controller.rb, app/controllers/observations_controller.rb, app/controllers/project_observations_controller.rb, app/controllers/projects_controller.rb, app/controllers/quality_metrics_controller.rb, app/controllers/votes_controller.rb, app/models/user.rb, app/webpack/observations/uploader/models/obs_card.js, package-lock.json
all admin users will no longer wait for an ES refresh after most data modification requests. The exceptions for now are obs delete, and obs create via the web uploader until we can ensure the web obs dashboard doesn't use ES _search
=> Skip refresh wait

app/models/update_action.rb, lib/elastic_model/acts_as_elastic_model.rb
Avoid delete_by_query in cases where we have the IDs of records needing to be deleted
=> Alternate ES delete

app/controllers/moderator_actions_controller.rb, app/controllers/moderator_notes_controller.rb, app/controllers/users_controller.rb, app/models/moderator_note.rb, app/models/user.rb, app/views/admin/user_detail.html.haml, app/views/moderator_notes/edit.html.haml, app/views/users/_show.html.haml, app/views/users/moderation.html.haml, config/locales/en.yml, config/routes.rb, db/migrate/20210408221535_create_moderator_notes.rb, db/structure.sql, spec/blueprints.rb, spec/controllers/moderator_notes_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/models/moderator_note_spec.rb
Adds a page to collect information relevant to user moderation, only visible to staff and curators, and not visible to the user who it concerns. Also adds a new `ModeratorNote` model to store notes concerning the moderation history of a particular user.
Closes #3009
=> Moderator Notes

app/assets/stylesheets/bootstrap-inat.scss, config/i18n-js.yml
We don't use the i18n/filtered.js file, which contained translations for all languages. This config change basically ensures that file is pretty much empty saving processing time when precompiling assets like on deploys.
This commit also renames bootstrap-inat.css to bootstrap-inat.scss as I was getting errors when precompiling assets locally since it uses some scss syntax.
=> i18njs config change

app/controllers/sites_controller.rb, app/models/site.rb, app/views/sites/show.html.haml, config/routes.rb, lib/site_data_exporter.rb
This serves site data exports to the site admins they're intended for via the website, assuming the export files are available in `tmp/page_cache/export_site_data/`. This would allow us to automate the process of generating these files every 6 months by adding a cron job to run `rails r tools/export_site_data.rb --dir tmp/page_cache/export_site_data/`.
The downside is that it furthers our reliance on having a big drive mounted via NFS, plus we have to serve some very large files via Rack / nginx. Upside is that access control is simple and we don't have to worry about sharing sensitive data via Amazon.
=> Serve site data exports to site admins

.github/workflows/CI.yml
Splits our Github Actions test suite into more parallel tasks so it completes a little faster.
=> Split CI into more tasks

app/assets/stylesheets/observations/identify/observation_modal.scss, app/webpack/observations/identify/components/observation_modal.jsx, app/webpack/observations/identify/components/suggestions.jsx
This should allow the right pane of the observation modal to scroll vertical with keyboard controls. It should also stop scaling up observation photos that are smaller than the space provided to assist detection of plagiarism.
=> Identify fixes: vertical keyboard scroll and no scale-up for images

app/models/listed_taxon.rb, app/models/shared/sweepers_module.rb, app/models/taxon_change.rb
minor changes to partial_revert:
- avoid inactivating output for when same as input
- make sure committed_on exists to avoid error
- try to avoid lifelist caches triggered via identification destroy -> observation.save
=> minor changes to taxon change partial revert

app/webpack/projects/show/components/requirements.jsx
#2948
Shows user filter (if defined) on the project's show page even when "Project Members Only" rule/preference is set.
In other words, if user filter rules are defined, they will always show on the about page. If they are not defined, it will show "Any" or "Project Members Only" depending on whether that option is set.
=> Add user filter on project when members only

CONTRIBUTING.md, app/webpack/stats/year/components/translators.jsx, tools/seek_common_names.rb
Noticed and updated a few places where the older master branch was referenced. There's also `deploy.rb.example:11` but I wasn't sure it's still being used as a basis for anything cap related so I left it as is.
=> Update docs, links from master to main

app/controllers/taxa_controller.rb, spec/controllers/taxa_controller_spec.rb
https://github.com/inaturalist/inaturalist/issues/3120
Ultimately this comes from a combination of normalizing the geoprivacy field and the params passing blank strings. Since `before_save` still lets the timestamps get touched and the record is "dirty" it shows as updated. Place_id could do something similar after it gets cast from `""` to `nil` on the db end. Nullifying the two offending params is the quickest fix here I think.
=> Filter blank values from conservation status params

app/controllers/places_controller.rb, app/views/places/edit.html.haml, app/views/places/new.html.erb, config/locales/en.yml, spec/controllers/places_controller_spec.rb
Removes the place boundary editing UI, leaving KML as the only way to add or edit a boundary.
=> Remove place boundary editor

app/models/taxon.rb, spec/models/taxon_spec.rb
#3150 
Allow a complex to share name with sibling species, but do not allow multiple sibling complexes with the same name.
=> Fix complex taxon unique validation

app/models/user.rb, lib/tasks/inaturalist.rake
Prior to this we were only removing the files when a user asked to be forgotten. Patrick, I think this should work, but it's a bit hard to test so I'd appreciate another pair of eyes.
=> Remove deleted user profile pics from s3 within a month

bin/setup
On Ubuntu, I wasn't able to get past the createdb check when setting up a development environment, even with the createdb command available in the shell.
I found when run in `irb`:
`system "command -v createdb"`
returned `nil`.
Changing this to:
`system "command -v createdb > /dev/null"`
returned `true`.
Testing:
`system "command -v invalidcommand > /dev/null"`
returned `false`.
NOTE: I haven't tested on macOS, as I don't have access to a mac.
=> Minor fix to bin/setup for Ubuntu

config/config.yml.example
To make setting up a new development environment smoother, as the jwt secret fallbacks in [lib/json_web_token.rb](/inaturalist/inaturalist/blob/main/lib/json_web_token.rb) don't match the jwt secret values in [iNaturalistAPI/config_example.js](https://github.com/inaturalist/iNaturalistAPI/blob/main/config_example.js).
Without this change, authenticated API requests fail out of the box on pages such as the Account Settings page.
These jwt secret values I've added here match the jwt secret values already in `iNaturalistAPI/config_example.js`
Instead of this change, another option could be to strip the jwt secret values from `iNaturalistAPI/config_example.js`, and rely on the fallbacks matching in both codebases for development environments.
=> Add jwt secret entries to config.yml.example

config/config.yml.example
To match tidy of jwt secret defaults in iNaturalistAPI. It makes the example config values match the fallback values in code.
This PR is the pair of  https://github.com/inaturalist/iNaturalistAPI/pull/268 and a follow up to https://github.com/inaturalist/inaturalist/pull/3169
=> Alter default jwt secrets in config.yml.example

app/views/identifications/_identification_for_dashboard.html.erb
Change Dashboard button text to be consistent with the Observation page button text.
Fixes #1500
I checked for usages of the `:agree?` `:remove` and `:removing` text, and they all look to be used elsewhere still.
What it looks like in English:
=> Change Dashboard button text to be consistent

db/migrate/20210819214533_drop_project_invitations.rb
#3129 
In order to preserve the best schema dump match to `structure.sql`, I've omitted that here.
=> Drop project invitations table

spec/factories/identifications.rb, spec/factories/observation_fields.rb, spec/factories/observation_photos.rb, spec/factories/observation_sounds.rb, spec/factories/observations.rb, spec/factories/photos.rb, spec/factories/project_observation_fields.rb, spec/factories/project_observation_rules.rb, spec/factories/project_observations.rb, spec/factories/sounds.rb, spec/models/guide_taxon_spec.rb, spec/models/observation_spec.rb, spec/models/project_observation_spec.rb
More factories added (using existing machinist blueprints as... blueprints), more work on the slowest examples:
`spec/models/project_observation_spec.rb`
`9 minutes 28 seconds` -> `4 minutes 38.2`
`spec/models/observation_spec.rb:58`
`4 minutes 43.9 seconds` -> `2 minutes 2.7 seconds`
=> More slow specs

app/helpers/application_helper.rb
Fixes #3204
Paragraphs were not being applied when in between 2 sections of tables, lists or preformatted text.
This was because the regex used was greedy, and would include everything between the first and last of one of those tags, rather than stop matching after the first end tag it finds.
Fix was to apply the non-greedy `?` modifier to the `*`s.
Issue was also visible on messages as well as journal posts.
=> Fix paragraphs not being applied in journal posts

app/controllers/observation_field_values_controller.rb, app/controllers/observations_controller.rb, app/models/observation_field_value.rb, spec/factories/observation_field_values.rb, spec/factories/observation_photos.rb, spec/factories/observations.rb, spec/factories/place_geometries.rb, spec/factories/places.rb, spec/factories/projects.rb, spec/factories/quality_metrics.rb, spec/factories/taxa.rb, spec/factories/taxon_names.rb, spec/factories/users.rb, spec/models/observation_field_spec.rb, spec/models/observation_field_value_spec.rb, spec/models/observation_spec.rb, spec/support/elastic_stub.rb
Target slower specs in the "o-m" range. Adds in more factories to support.
Related: #3183
=> Use observation stubs where possible in specs

app/controllers/atlases_controller.rb, app/helpers/application_helper.rb, app/models/atlas.rb, app/views/atlases/show.html.haml
Atlases roll up listed taxa for taxon descendants. The idea is that if a species has no listed_taxa for place X but it has sub-species that do, place X should still be calculated as an atlas presence_place.
While atlases were mostly conceived for species, they are our only means of reassigning input_taxon IDs to unambiguous output_taxa as part of a taxon_split which sometimes needs to be done for taxa coarser than species (e.g. families etc.). This method of rolling up listed taxa for taxon descendants for taxa with many many descendants (e.g. large families) isn't scaling well and times out. 
This change makes it so that atlases for taxa coarser than species only calculate presence places based on listed_taxa associated with the taxon itself, ignoring listed_taxa associated with the …
=> Atlas improvements

app/models/conservation_status.rb, spec/models/conservation_status_spec.rb
when global non-obscuring conservation statuses are created or destroyed, no need to reassess observation geoprivacies
=> don't reassess obs on global non-obscuring status creation/deletion

app/webpack/taxa/photos/ducks/photos.js
Fix taxon photo term filter so both term_value_id AND term_id need to be relevant for the taxon for both of them to be included. 
Fixes #3250
Beforehand, if the term_id was valid, but the term_value_id not used, then only the term_id was included in the filter which would filter out all observations that didn't include some value for that term_id. This clashed with what the UI was showing as it indicatied that no filtering was occurring.
I also moved the setObservationParams function call to the bottom of the function (outside the `if ( taxon )` block) as it looked like a more correct location for it.
Note: I've reproduced and tested the fix locally, but as my local dev environment is lacking much data it might be worth putting it through its paces in a test environment.
=> Fix taxon photo term filter

app/controllers/check_lists_controller.rb, app/controllers/users_controller.rb, app/models/listed_taxon.rb, app/models/user.rb, app/views/listed_taxa/_establishment_field.html.erb, app/views/users/delete.html.haml, app/webpack/shared/ducks/config.js, config/locales/en.yml, spec/controllers/check_list_controller_spec.rb, spec/models/user_spec.rb
* Allow default check list deletion when place no longer allows check lists
* Fixed bugs with translatable establishment means descriptions
* When user deletes their account and they made a project that has observations
but no other managers, stop assigning the project to the first admin and just
delete it
=> Several minor fixes

app/assets/stylesheets/projects/show2.scss, app/webpack/projects/show/components/observations_flex_grid_view.jsx, app/webpack/projects/show/components/observations_list_view.jsx, app/webpack/projects/show/components/observations_tab.jsx, app/webpack/projects/show/components/view_more_footer.jsx
Issue: https://github.com/inaturalist/inaturalist/issues/2332
Added View More link buttons to the bottoms of both the Grid and List views of Project observations.
Links will only be visible when there are more observations than are shown on the page and the infinite scroller has reached its limit.
=> Add View More links to bottom of Project observations pages

app/assets/stylesheets/projects.css, app/views/projects/_project_by_login.html.haml
Instead of truncating at the server.
This allows the full width to be used to display text.
No accepted issue #, but see this forum post for an example of the issue:
https://forum.inaturalist.org/t/projects-titles-are-cut-off-in-user-profile/20749
I used `-webkit-line-clamp` etc. for the 2 line truncation as it was being used elsewhere in the codebase.
=> Truncate Projects by_login title and description with css

app/webpack/computer_vision/webpack-entry.js, app/webpack/observations/uploader/webpack-entry.js, app/webpack/projects/form/webpack-entry.js, package-lock.json, package.json
Fixes issue #3276
Coming at this again after a failed attempt in #3324.
Fix was reasonably straight forward. Some react entry points didn't set the moment locale before the react-datetime control was rendered, so ended up rendering the days of the week in the wrong positions for the locale.
It might be possible to move this to some shared initialization? Not sure where though.
Fixes datetime controls in:
- project create
- uploader (just the left menu was broken)
- computer vision demo
Other areas that use the control already had moment locale initialized on webpack-entry:
- identify filters
- observation show (observation fields)
I also changed the react-bootstrap-datetimepicker git hash in `package.json` to point to the head of main rather than the head of a branch in case that branch …
=> Fix react-bootstrap-datetimepicker internationalization 

app/assets/stylesheets/observations/identify/observation_modal.scss, app/views/observations/identify.html.haml, app/webpack/.eslintrc, app/webpack/observations/identify/components/observation_modal.jsx, app/webpack/observations/identify/containers/observation_modal_container.js, app/webpack/observations/identify/webpack-entry.js
Issue: https://github.com/inaturalist/inaturalist/issues/3304
I decided against using the icon within the modal as I felt it would ruin the styling pattern that comes from the fa icons and the name is definitely enough to identify the application. But I can change that if the icon is a must.
=> Added "Created Using" to Observation Modal

app/webpack/projects/show/components/requirements.jsx
Fixes #3318
It's possible to have project user rules for deleted users.
When displaying project user rules, filter out the rules where the user is missing to avoid an error.
I thought about filtering this further up in `/app/webpack/projects/shared/models/project.js`, but as it was a shared, and the API can return rules without users by not passing `rule_details=true` in the request, I thought it best to fix it close to where the error was occurring.
=> Exclude showing project user rules without users

app/controllers/moderator_actions_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/models/comment.rb, app/models/identification.rb, app/models/moderator_action.rb, app/models/user.rb, app/views/users/moderation.html.haml, app/views/users/suspend.html.haml, app/views/users/unsuspend.html.haml, config/environments/development.rb, config/initializers/has_moderator_actions.rb, config/locales/en.yml, spec/controllers/users_controller_spec.rb, spec/factories/comments.rb, spec/factories/moderator_actions.rb, spec/models/moderator_action_spec.rb
Alters account suspension so it happens via Moderator Actions. This means each suspension and unsuspension will be recorded, along with who performed the action and with an explanation for why they did it.
Closes #3050
=> Suspend as moderator action

.rubocop.yml, app/controllers/provider_oauth_controller.rb, app/models/user.rb, config/locales/en.yml, lib/privileges.rb, spec/controllers/provider_oauth_controller_spec.rb, spec/factories/oauth_applications.rb, spec/factories/user_parents.rb, spec/factories/users.rb, spec/models/user_spec.rb, spec/spec_helper.rb
Pulled in a few changes to oauth assertion flow error states from the email confirmation branch so mobile developers can build against them in production. These get our responses to the assertion auth flow in line with the oauth spec, namely that we reply with 400 responses that contain JSON in a standardized format. In theory the iPhone app will handle them, but Android will have to make [some changes](https://github.com/inaturalist/iNaturalistAndroid/issues/1188), and maybe Seek.
=> Changes to assertion oauth flow error states

app/assets/javascripts/ang/controllers/observation_search.js, app/assets/javascripts/ang/inaturalist_angular.js, app/assets/javascripts/ang/templates/observation_search/taxa_grid.html.haml, app/controllers/application_controller.rb, app/controllers/taxa_controller.rb, app/controllers/taxon_names_controller.rb, app/controllers/votes_controller.rb, app/es_indices/observation_index.rb, app/models/observation.rb, app/models/site.rb, app/webpack/projects/show/components/species_tab.jsx, app/webpack/projects/show/containers/species_tab_container.js, app/webpack/projects/show/ducks/project.js, app/webpack/taxa/show/ducks/leaders.js, db/migrate/20220317205240_add_unique_index_on_uuid_to_annotations.rb, db/migrate/20220317210522_add_index_on_ruler_id_and_ruler_type_to_rules.rb, db/structure.sql
A handful of smaller changes:
- Use "infinite scrolling" on species tabs of explore and projects pages. Results in a initial species_counts request that is smaller and a little faster
- Limit data fetched for top observer and IDer for taxon page
- Add indices to annotations and rules. Makes deleting annotations much faster; rules lookups are faster
- Increase query timeout on explore. Explore had a lower timeout than the API
- Cache results of API query from login page
- Change ListedTaxon query for observation bulk indexing to be more performant
- Added various preloading to reduce number of DB queries
=> Small performance improvements

app/models/local_photo.rb, app/webpack/observations/uploader/models/dropped_file.js
Most of the time the uploader will correctly interpret the datetime from the EXIF and populate that value in the obs card immediately. However, if it fails, it will fall back on the `time_observed_at` provided by the server. The bug was occurring when the latter occurred and the uploader was correctly interpreting that value with its specified offset, but then incorrectly formatting that in the *local* time zone for display. This change makes sure that when the client interprets `time_observed_at`, it also sets the moment object to use the correct time zone before formatting the datetime for display.
=> Bugfix: uploader not correctly interpreting time zone from the server

app/models/observation.rb, spec/models/observation_spec.rb
Setting the time zone happens before validation, because it needs to precede setting the datetime, and the datetime needs to be validated to make sure it's not in the future or too far in the past. However, setting the time zone now relies on the coordinates, and for obscured obs, the coordinates are generally in the private_* attributes... except when an observation is getting updated, in which case the client is supposed to just submit new `latitude` and `longitude` values, and we assume a change in those attributes mean they are now the true values and should subsequently be obscured.
Long story short, this change uses those `latitude` and `longitude` to set the time zone if they have changed, but if they haven't it continues to use `private_latitude` and `private_longitude` if they're …
=> Use changed coordinates when assigning a time zone for an obscured obs

app/assets/stylesheets/observations/show.scss, app/models/observation.rb, app/webpack/observations/uploader/models/dropped_file.js, app/webpack/observations/uploader/models/util.js, spec/models/observation_spec.rb
Also attempts to replace AM / PM translated into other languages with the literal English values when parsing a date with Chronic.
Closes #3437
=> Use parsable date format for EXIF date in Uploader (#3437)

app/es_indices/observation_index.rb, lib/observation_search.rb, spec/controllers/observation_controller_api_spec.rb, spec/lib/elastic_model/indices/observation_index_spec.rb
observations/export still uses the Rails endpoint, which wasn't supporting queries like `user_id=carmela,sylvio&ident_user_id=mariner,boimler`.
=> Support multiple values for user_id and ident_user_id in observations/export

app/models/emailer.rb, lib/bulk_observation_file.rb, spec/models/emailer_spec.rb
As of f44050455e2a04a122c17f8f58c33047b7f3a996 we have not been using the
correct locale when translating email subjects. This allows the subject to be
specified with an array of arguments to I18n.t. Also fixed up some code
style.
=> Use appropriate locale when translating email subjects

.github/workflows/CI.yml, app/models/place.rb, app/models/site.rb, app/views/layouts/bootstrap.html.erb, app/views/shared/_footer.html.haml, app/views/welcome/_index.html.haml, app/views/welcome/index.html.haml, bin/setup, config/database.yml.example, docker-compose.override.yml.example, lib/place_sources.rb, lib/site_data_exporter.rb, tools/import_us_states.rb
* Site.default creates a new site if one doesn't exist
* welcome/index should function without a site
* System calls in bin/setup raise exceptions
* Hardcoded default postgres username and password in example database and
Docker config
* Minor updates to some data loading scripts
=> Dev setup changes

config/webpack.config.js, package-lock.json, package.json
Removes the `gulp` package which is no longer actively maintained and requires a bunch of package versions with security warnings. Webpack can be triggered now with `npm run webpack` for a one-time run, and `npm run webpack-watch` to keep webpack listening for changes much like the `gulp` command was doing previously
=> Remove gulp

app/views/admin/users.html.haml
This pull request is for issue [3444](https://github.com/inaturalist/inaturalist/issues/3444).
=> In search results at admin/users, link observations number to Explore, not Edit Observations

app/models/emailer.rb
Plus minor Rubocop cleanup. I don't remember why we stripped unicode initially. Rails docs suggest Rails handles unicode markers in email headers these days, so maybe it's not something we need to worry about.
FWIW, this works on staging:
=> Allow unicode in email from header

app/assets/stylesheets/posts.css, app/controllers/posts_controller.rb, app/helpers/application_helper.rb, app/models/concerns/has_journal.rb, app/models/post.rb, app/models/project.rb, app/models/site.rb, app/models/user.rb, app/views/lists/by_login.html.haml, app/views/posts/_breadcrumbs.html.erb, app/views/posts/_header.html.haml, app/views/posts/_posts.html.haml, app/views/posts/_search_form.html.haml, app/views/posts/browse.html.haml, app/views/posts/index.atom.builder, app/views/posts/index.html.haml, app/views/posts/new.html.haml, app/views/posts/search.html.haml, app/views/posts/show.html.haml, app/views/shared/_by_project_header_bootstrap.html.haml, config/locales/en.yml, config/routes.rb
#3540
- Add pg ilike search to `posts.title` and `posts.body`
- Add search form to `/journal` (browse)
- Add post search results page which shows results, paginated
=> Add pg ilike search to posts title and body

app/views/comments/_comments.html.erb, app/views/shared/_activity_item.html.erb, config/locales/en.yml
#3418 
Adds the translation.
Alternatively, we could add a message here: 
```rb
errors.add( :parent, :prefers_no_comments,  I18n.t(:prefers_no_comment))
```
and reference the existing post translation, though I feel that's less explicit.
Side-note/question:
Should comments made prior to marking the post as non-comment-able be visible at all? (see edit screenshot) 
It's not really a "new comment" either...
=> Add translation

app/models/year_statistic.rb, app/webpack/stats/year/components/streaks.jsx
Previously it was showing overlapping text for multi-year streaks.
Part of #3553
=> Fix ticks for streaks chart in YIR

app/views/donate/index.html.haml, app/views/donate/monthly_supporters.html.haml
-removes the default amount selection from /donate and /monthly-supporters. 
-updates the 2018 campaign utm from the social media share links.
=> Donation page urls

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
Mainly so links with `rel="me"` can be used as a kind of verification, as they seem to be with Mastodon. Also tried to explain what's happening with the negative look behind pattern matching in `hyperlink_mentions`. Not sure if these changes have any performance implications, but I figured they wouldn't since we're already doing that Nokogiri parsing.
=> Support rel=me attribute in profile links

app/webpack/observations/identify/actions/current_observation_actions.js, app/webpack/observations/identify/components/observation_modal.jsx, app/webpack/observations/identify/keyboard_shortcuts.js, config/locales/en.yml
[#3419](https://github.com/inaturalist/inaturalist/issues/3419)
Set focus to first `<audio>` element and play associated sound file. If an `<audio>` element is already active, the `togglePlayFirstSound` action exits early to avoid interfering with default processing.
=> Add Identify keyboard shortcut to play observation's sound

app/webpack/taxa/show/components/interactions_tab.jsx
I know this is a 'hidden' feature, but there are a couple typos that have been bothering me for a long time. I'm unsure why this view renders with a missing space, so I made it one line to be more sure it this edit would work.
=> chore: fix typos

config/initializers/i18n.rb
Fixes inaturalist/inaturalist#3576.
The load paths set in the initializer are already set as part of the default behavior of devise. By adding them in the initializer, they will not be added later by devise, at a higher priority (i.e. later in the list).
```diff
inaturalist fix-i18n-load-path % diff load-path-before.yml load-path-after.yml
353a354,355
> - "/Users/rainhead/.rvm/gems/ruby-3.0.4/gems/devise-4.8.0/config/locales/en.yml"
> - "/Users/rainhead/.rvm/gems/ruby-3.0.4/gems/doorkeeper-5.5.4/config/locales/en.yml"
433,434d434
< - "/Users/rainhead/.rvm/gems/ruby-3.0.4/gems/devise-4.8.0/config/locales/en.yml"
< - "/Users/rainhead/.rvm/gems/ruby-3.0.4/gems/doorkeeper-5.5.4/config/locales/en.yml"
```
=> Ensure our translations override devise's

app/controllers/users/confirmations_controller.rb, app/models/user.rb, app/views/layouts/bootstrap.html.erb, app/webpack/users/edit/ducks/user_settings.js, config/locales/en.yml, spec/models/user_spec.rb
* allows email confirmation without signing existing users out and requiring
them to confirm (way, way too many problems with email delivery)
* maintains lock out for new users, i.e. users created after the release of
email confirmation
* restores guard against remembering that a user was on a confirmation page
* use a date-based definition of existing user to decide whether to send the
welcome email
=> Email confirmation without lockout

app/models/guide_section.rb, app/models/list.rb, app/models/listed_taxon.rb, app/models/observation.rb, app/models/observation_sweeper.rb, app/models/observations_export_flow_task.rb, app/models/photo.rb, app/models/place_sweeper.rb, app/models/project_observation.rb, app/models/shared/sweepers_module.rb, app/models/subscription.rb, app/models/taxon_change.rb, app/models/taxon_swap.rb, app/models/user.rb, app/models/user_sweeper.rb, lib/url_helper.rb, spec/models/observation_spec.rb, spec/models/user_spec.rb
#3264
First step in removing `FakeView`. 
- Creates `UrlHelper` which handles delegating to `Rails.application.routes.url_helpers` in a single purpose class. 
- This should be a large portion, if not the majority, of `FakeView` usages.
- The next big step will be allow calls to these from outside of the view context:
- `image_url`
- `uri_join`
- Also need to address :
- Calls to `render`
- Calls to `ActionView::Helpers`
- DarwinCore (not too familiar with what this is yet)
=> Replace FakeView url helpers in models

app/models/deleted_observation.rb, app/models/observation.rb, db/migrate/20221219015021_add_observation_created_at_to_deleted_observation.rb, db/structure.sql
#3601
- Adds observation created at datetime column
- Sets observation created at on deleted observation `after_destroy` of observation
=> Add observation_created_at to DeletedObservation

app/models/user.rb, spec/models/user_spec.rb
Fixes: inaturalist/inaturalist#3546
I'm happy to factor out some of this responsibility, but it wasn't clear that there was anything generalizable.
I'm using `destroy_all` because I don't know what kind of post-destroy hooks there might be on the records, and because I don't expect there to be enough duplicates for it to be a performance problem.
=> Delete duplicate faves before merging users

app/models/comment.rb, app/models/identification.rb, spec/models/flag_spec.rb
This ensures that the observation's `updated_at` changes after flagging an identification or a comment on that observation, this allowing a client to detect that something has changed with the observation and it probably needs to update its copy. This specifically emerged from trying to implement flagging in the React Native app, where (at present) everything is driven through the local database, so after creating a flag, the app needs to update its local database and the simplest way to do so seemed to be to re-fetch the observation after flagging.
Couple potential problems:
1. We refetch the observation after updating associated records in other clients, but do we still think that's a good approach?
2. If the observation is updated in postgres and reindexed in es during the request to …
=> Touch the observation when flagging a comment or identification

app/views/posts/_attribution.html.haml, app/views/posts/_post.html.haml, app/views/posts/show.html.haml, app/views/trips/show.html.haml, config/locales/en.yml
I removed the `by` translation key because it can't be translated without context, and I neglected to address this usage. I've tried to make this more translatable by using text with more context... albeit with more variables.
=> Make post attribution more consistent and translatable

lib/observation_search.rb
Fixes: https://github.com/inaturalist/inaturalist/issues/3639
I wrote a test for this, but without clear type expectations around params/search_params/etc, the test had to be at the controller level, and I ran out of energy figuring out how to create the fixtures and stubs I needed there. The test did run far enough to exhibit the issue and confirm the fix, as did manual testing.
=> Allow taxon_ids to be ints or strings

app/webpack/taxa/show/components/status_tab.jsx, app/webpack/taxa/show/components/taxon_page_tabs.jsx, config/locales/en.yml
https://github.com/inaturalist/inaturalist/issues/3248
Show "Status applied from a higher level taxon" message when the originating taxon of a conservation status doesn't match the taxon being viewed.
=> Add relevant ancestral taxon to conservation status column

tools/import_place_from_production.rb
Based on a script by @kueda, but:
- imports recursively, recording parent
- records uuid
- uses Faraday, so we can switch to v2 API + JWT token eventually
One trick with this is that Asia cannot be imported because something is amiss with its geometry. Because the script imports a place's parents recursively, nothing in Asia can be imported. Do you have a hunch for whether this is a problem with production data or with the import script?
=> Tool to import a place from the Production API

app/views/taxon_links/_form.html.erb, app/views/taxon_links/edit.html.erb
#3638 
Hey @tiwane, I think the easiest solution, without a redesign is to pull it up:
=> Move taxon_link comments up in view

app/controllers/users_controller.rb, app/views/emailer/_footer.html.erb
#3664 - On emails, change URL for "Update subscription preferences" link
- Adds a redirect to `#notifications` anchor if notifications param present
- Allows linking directly to `#notifications` tab, even when not logged in
(note url in bottom left of first image)
->
-> 
->
=> Redirect to notification settings for email link

app/webpack/observations/identify/ducks/suggestions.js
Bug:
- Identify some unknowns: https://www.inaturalist.org/observations/identify?per_page=100&order_by=random&without_taxon_id=48460
- Click one of them
- Switch to the suggestions tab
- Switch back to the info tab
- Switch back to the suggestions tab
- Get error: `TypeError: state.query.taxon is null`
This line of code assumes that `state.query.taxon` is not null, but it is null.
=> Fix suggestions tab for Unknown

.gitignore, config/webpack.config.js
Closes #3708 by ensuring webpack is in `production` mode when we transpile JS for production. This definitely results in smaller JS files and may result in other performance improvements. May also alleviate some personal embarrassment, in time.
=> Webpack production mode

app/webpack/.eslintrc, app/webpack/observations/show/components/flagging_modal.jsx, app/webpack/projects/show/components/app.jsx, app/webpack/shared/components/flag_an_item.jsx
The problem in #3715 is that ea109554321997116a07063ff61d8bb28c1064bd enabled production webpack builds, which minifies the outputs, a part of which is abbreviating constructor names, so code like `photo.constructor.name === "Photo"` will not work because `photo.constructor.name` gets abbreviated to `"p"`. This forbids the use of constructor.name with eslint and replaces our uses of it with direct constructor comparison per the advice in https://stackoverflow.com/a/49610802, but an alternative approach might be to reconfigure [webpack's minifier](https://webpack.js.org/plugins/terser-webpack-plugin/#minify), or just not minify and rely on the asset pipeline to do that. I'm agnostic, this just seemed like a simple working solution.
Closes #3715
=> constructor.name unreliable with minification; replace with constructor comparison

app/helpers/application_helper.rb, app/views/layouts/bootstrap.html.erb, config/config.yml.example, package-lock.json, package.json
In service of #3636.
Changes:
- Upgrade Google Maps to from 3.48 to 3.51 ([ChangeLog](https://developers.google.com/maps/documentation/javascript/releases#3.48.1)). **NB: 3.48.1 removes support for Internet Explorer**.
- Use the same Maps API version regardless of environment.
- Upgrade type signatures package, whose name changed slightly.
- Do less raw string manipulation in the helper.
- Always load the Maps API over a secure connection.
- Fix a setting in `config.yml.example` that tripped me up when setting up my development environment.
While Google [says](https://developers.google.com/maps/documentation/javascript/overview#sync) you can load the Maps API synchronously, this generates a warning in the console, which is visible in production. It's possible that Google would remove …
=> Upgrade Google Maps API

Gemfile, Gemfile.lock
Fixes: #3692. The date is correct, though the timezone is not based on the location of the observation. If that is a problem, I think it's unrelated.
Pull in https://github.com/mojombo/chronic/pull/396
Before:
```
3.0.4 :001 > date_string = "2023/03/12 00:06"
=> "2023/03/12 00:06"
3.0.4 :002 > Time.zone = ActiveSupport::TimeZone['Central Time (US & Canada)']
=> #<ActiveSupport::TimeZone:0x000000010782b240 @name="Central Time (US & Canada)", @tzinfo=#<TZInfo::DataTimezone: America/Chicago>, @utc_offset=nil>
3.0.4 :003 > Chronic.parse(date_string, context: :past)
=> 2023-03-13 00:06:00 -0700
```
After:
```
3.0.4 :001 > date_string = "2023/03/12 00:06"
=> "2023/03/12 00:06"
3.0.4 :002 > Time.zone = ActiveSupport::TimeZone['Central Time (US & Canada)']
=> …
```
=> Fix datetime parsing at dst crossover

app/models/time_zone_geometry.rb, tools/load_time_zone_geometries.rb
https://github.com/inaturalist/inaturalist/wiki/Development-Setup-Guide gives instructions for loading timezone geometries from a shapefile. However, `tools/load_time_zone_geometries.rb` expects a geojson file, not a shapefile.
* Allow the tool to import shapefiles in addition to geogjson files.
* Fix the connection string fed to `ogr2ogr` to include the port number
=> Fix load time zone geometries

app/webpack/observations/show/components/activity_item.jsx, app/webpack/shared/components/text_editor.jsx
Fixes: https://github.com/inaturalist/inaturalist/issues/3685
I think this represents a bug in jquery.textcomplete, but I didn't feel like changing its source code.
=> Observe changes to Textarea when using mentions

app/assets/javascripts/ang/controllers/observation_search.js.erb, app/webpack/observations/show/ducks/other_observations.js, app/webpack/projects/show/ducks/project.jsx, app/webpack/taxa/show/ducks/observations.js
Requires https://github.com/inaturalist/iNaturalistAPI/pull/377 to be merged and deployed first.
Replaces all uses of `skip_total_hits` (which ends up running ES queries not specifying `track_total_hits`, ultimately using the default of 10,000) with `no_total_hits` (which ends up running ES queries specifying `track_total_hits:false`, returning no value for total hits). Also adds the `no_total_hits` param to explore and project page observation requests after the total has been fetched once, allowing for faster and more efficient infinite-scoll observations requests
=> replace skip_total_hits with no_total_hits

app/assets/javascripts/ang/controllers/observation_search.js.erb, app/assets/javascripts/ang/templates/observation_search/identifiers_table.html.haml, app/assets/javascripts/ang/templates/observation_search/observers_table.html.haml, app/webpack/observations/show/ducks/identifications.js, app/webpack/projects/shared/models/project.js, app/webpack/projects/show/components/observers_tab.jsx, app/webpack/projects/show/containers/observers_tab_container.js, app/webpack/projects/show/containers/top_species_observers_panel_container.js, app/webpack/projects/show/ducks/project.jsx, app/webpack/taxa/show/ducks/leaders.js
* project and explore pages load tab data in sequence, prioritizing current tab
* explore delays loading list of identifiers and observers
* umbrella projects delay loading list of observers
* avoid calculating query totals when possible
=> API query optimizations

app/views/users/dashboard.html.haml
Discourse meta is quite clear that a URL is incomplete/malformed without the topic id, see https://meta.discourse.org/t/inbound-links-dont-show-up-when-topic-id-is-not-included/100551/2
https://meta.discourse.org/t/clicking-an-internal-link-with-slug-only-and-no-topic-id-should-create-a-history-entry/176475
https://meta.discourse.org/t/incomplete-topic-titles-beginning-with-a-number-can-have-odd-behavior/153975
When links are constructed without the topic id, they will redirect to the wrong topic if the topic title starts with a number, e.g.
https://forum.inaturalist.org/t/particular-topic-under-18s-photo-contest-is-redirected-to-an-unrelated-topic-unable-to-search-by-obs-id/23168
https://forum.inaturalist.org/t/forum-link-on-inat-home-page-takes-me-to-wrong-thread/11443 …
=> add topic id

app/models/listed_taxon.rb
Listed taxa without places have no primary_listed_taxa or related_list, so don't attempt to query for them with a nil place_id
=> Listed taxa query fix

app/models/emailer.rb, app/models/user.rb, app/views/emailer/_footer.html.erb, app/views/emailer/email_confirmation_reminder.html.haml, config/initializers/script_find_each.rb, config/locales/en.yml, test/mailers/previews/emailer_preview.rb, tools/email_unconfirmed_users.rb
* Emailer#email_confirmation_reminder to send the email
* tools/email_unconfirmed_users.rb to send the emails
* Enforce User::EMAIL_CONFIRMATION_REQUIREMENT_DATE
* Minor fixes for script_find_each
Open to reviews, but please don't merge until we've had a chance to test this a bit. I want to minimize the churn for translators.
=> Script to remind unconfirmed users to confirm their email (#3764)

app/models/user.rb, spec/models/user_spec.rb
Fixes: #3713 
Do you want to include 666, 69, 420, or anything else in here?
- Clean up code. Remove all conditionals. You can read what happens in a straight line from top to bottom. Variables have meaningful names. The comments are hopefully helpful.
- The same logic is applied to `DEFAULT_LOGIN` as to requested logins. We try the base login, then try adding a single digit (except 9), then try twenty psuedorandom numbers.
- Random-number suffixes are limited at half of `MAX_LOGIN_SIZE` rather than a number derived from the storage of the `id` field.
- It will fail rather than trying logins indefinitely.
This could be done in a single SQL query, but I'd have to write custom Arel, which didn't seem worth it.
This method should perhaps raise an error rather than returning nil, but that …
=> Don't suggest logins containing sensitive numbers

app/assets/javascripts/jquery/plugins/inat/taxon_selectors.js.erb
Fixes: #3746.
Please try this out locally. It wasn't easy to figure out how to set up test data.
Before:
After:
In some places we're good about `extend`ing into a new object, in others we're not.
=> Don't mutate options when calling extend

app/webpack/users/edit/ducks/relationships.js
Fixes: #3744.
Pass the current page number through to the API when refreshing the relationships list.
=> Pass through page number when updating relationship

app/controllers/oauth_tokens_controller.rb, app/controllers/provider_oauth_controller.rb, app/controllers/shared/filters_module.rb, app/controllers/users/sessions_controller.rb, app/models/user.rb, config/initializers/doorkeeper.rb, config/initializers/inat_auth.rb, config/locales/en.yml, spec/controllers/provider_oauth_controller_spec.rb, tools/email_unconfirmed_users.rb
This changes the error message unconfirmed people will see when they try to sign in after we require email confirmation for everyone. Before it just assumed you'd just signed up and asked you to check your email, but now it will show a different message to people who signed up before we required confirmation for signup instructing them to reset their password.
=> Improved error message after confirmation requirement

app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/bootstrap.html.erb, app/views/observations/show.html.haml, app/webpack/taxa/shared/util.js, app/webpack/taxa/show/components/taxon_page_map.jsx
Implements: #3633 
Does this impact the right set of pages? I see maps on the "suggestions" tab on the identify page can have GBIF layers; should this affect them? Are there other pages with GBIF layers?
=> Make GBIF layer on taxon page sticky

app/webpack/observations/show/components/photo_browser.jsx
VoiceOver in Safari doesn't seem to want to focus on an <audio> element controls if it's inside of an element with the button role, so this removes that. I can navigate to the play button with VoiceOver, but it's still pretty bad because Safari seems to read the elapsed time every second, making it impossible to actually hear what's being played.
=> Remove ARIA role that interferes w/ VoiceOver control of audio

lib/taxon_describers/lib/taxon_describers/wikipedia.rb
I assume it was using them correctly at some point, or the API we're hitting wasn't using redirects and now it is. Either way, this seems to fix the issue with fetching the correct Wikipedia URL with Wikidata.
=> Bugfix: fetching Wikipedia URL from Wikidata was not using redirects

app/webpack/taxa/show/containers/last_observation_container.js
Addresses https://github.com/inaturalist/inaturalist/issues/3736
Before
After
=> Display only the month and year for obscured or private Latest Observations on Taxon page

app/webpack/users/edit/containers/blocked_muted_users_container.js, app/webpack/users/edit/ducks/blocked_muted_users.js, app/webpack/users/edit/ducks/relationships.js
https://github.com/inaturalist/inaturalist/issues/3743
Before:
`users/edit#relationships` displays relationships sorted by friend's login desc upon page load
After:
`users/edit#relationships` displays relationships sorted by friend's database id desc upon page load. I didn't sort by the Friendship created_at column b/c the existing frontend relies on the Friendship id.
This PR also contains a second commit to address a circular dependency identified by eslint.
=> 3743 user settings relationships sort

app/controllers/shared/filters_module.rb, config/initializers/devise.rb, config/initializers/i18n.rb, lib/inat_devise_failure_app.rb
This *attempts* to set the I18n.locale correctly before Doorkeeper / Devise / Warden set error messages. It works locally in a dev and prod envs, but not on staging, so I'm curious if it will work in production.
=> Localize doorkeeper devise auth failure

app/webpack/observations/uploader/components/taxon_autocomplete.jsx
Currently the autocomplete popup will leave the visible window space if no space is left on the left side, which causes a scrollbar to appear.
jQuery UI has a build-in option to mitigate this problem (https://api.jqueryui.com/position/):
> "flipfit": First applies the flip logic, placing the element on whichever side allows more of the element to be visible. Then the fit logic is applied to ensure as much of the element is visible as possible.
I stumble quite often over this "small issue" as I upload frequently multiple images and though this simple fix could be a good addition. 
PS: Don't know if I should write an exception for RTL as with my current implementation the RTL style would not be applied.
PPS: I was to lazy to look into the VisionAPI therefore I don't know if everything is ok …
=> fix: :bug: fix autocomplete leaving window on upload page

app/assets/javascripts/announcements/form.js, app/models/announcement.rb, app/views/announcements/_form.html.haml, app/views/announcements/index.html.haml, app/views/announcements/show.html.haml, config/locales/en.yml, db/migrate/20231017190352_add_clients_to_announcements.rb, db/migrate/20231017190352_add_platforms_to_announcements.rb, db/structure.sql, spec/models/announcement_spec.rb
- Adds a new array column `clients` to announcements
- Allows admins to specify the client to which announcement applies #3896
- Fixes staff targeting for web announcements #3888
=> Announcement clients

app/controllers/controlled_terms_controller.rb, app/models/controlled_term.rb, app/models/controlled_term_label.rb, app/models/controlled_term_value.rb, app/views/controlled_term_labels/_form.html.haml, app/views/controlled_term_labels/_form_fields.html.haml, app/views/controlled_terms/_controlled_term_taxon_fields.html.haml, app/views/controlled_terms/_form.html.haml, config/locales/en.yml, spec/blueprints.rb, spec/controllers/annotations_controller_api_spec.rb, spec/controllers/controlled_terms_controller_spec.rb, spec/helpers/make_helpers.rb, spec/lib/darwin_core/archive_spec.rb, spec/lib/darwin_core/occurrence_spec.rb, spec/models/annotation_spec.rb, spec/models/controlled_term_label_spec.rb, spec/models/controlled_term_spec.rb, spec/models/observation_field_value_spec.rb
Requires the presence of a label for new controlled terms and validates that all new labels have the `label` and `description` attributes.
This kind of throws testing for a loop since to make a valid controlled term you now need to build out an associate, so I'm open to ideas about how to make that better.
=> Require controlled term labels

app/controllers/stats_controller.rb, app/models/year_statistic.rb, app/models/year_statistic_localized_shareable_image.rb, app/views/stats/year.html.haml, config/initializers/paperclip.rb, db/migrate/20231025144604_create_year_statistic_localized_shareable_images.rb, db/structure.sql, spec/models/year_statistic_localized_shareable_image_spec.rb, spec/models/year_statistic_spec.rb
* Adds a new model for localizes YIR shareable images #3910
* Generates localized shareable images for stats from 2020 onward, and favors using the localized shareable over unlocalized versions that may have already been generated
* Update the year stats view to use the shareable image matching the current session locale
* Refactors much of the shareable image generation. Leverages caching shared components for up to 10 minutes to speed up and reduce load of generating shareables for all locales
=> Localized Year In Review shareable images

app/helpers/taxa_helper.rb, app/models/observation.rb, app/views/taxa/_taxon.txt.erb, app/webpack/lifelists/show/components/details_view.jsx, app/webpack/lifelists/show/components/species_noapi.jsx, app/webpack/lifelists/show/util.js, app/webpack/observations/uploader/components/taxon_autocomplete.jsx, config/locales/en.yml, lib/tasks/inaturalist.rake, spec/helpers/taxa_helper_spec.rb
* Use translated iconic taxon name as a fallback source of common names when TaxonName records are absent, particularly important for Life, which in theory does not support any taxon names
* Allow use of `@iconic_taxon` inflection in translations keys where the translation might vary depending on taxonomic context, e.g. in East Slavic languages where words like "phylum" will be different for plants and animals
Depends on https://github.com/inaturalist/iNaturalistAPI/pull/414
=> I18n iconic taxon changes

app/webpack/observations/identify/components/suggestions.jsx
Compare modal wasn't honoring the user preference for Taxo naming. currentUser wasn't transmitted to the taxonomic_branch from the suggestion component
=> #3931: Give currentUser props to taxonomic_branch component

app/assets/javascripts/jquery/plugins/inat/generic_autocomplete.js, app/models/user.rb, app/views/observations/identify.html.haml, app/webpack/computer_vision/components/obs_card_component.jsx, app/webpack/observations/identify/actions/current_observation_actions.js, app/webpack/observations/identify/components/observation_modal.jsx, app/webpack/observations/identify/containers/annotations_container.js, app/webpack/observations/identify/containers/observation_fields_container.js, app/webpack/observations/identify/containers/projects_container.js, app/webpack/observations/identify/keyboard_shortcuts.js, app/webpack/observations/shared/ducks/observation.js, app/webpack/observations/show/components/annotations.jsx, app/webpack/observations/show/components/observation_field_input.jsx, app/webpack/observations/show/components/observation_fields.jsx, app/webpack/observations/show/components/projects.jsx, app/webpack/observations/show/ducks/users.js, app/webpack/observations/uploader/components/date_time_field_wrapper.jsx, app/webpack/observations/uploader/components/left_menu.jsx, app/webpack/observations/uploader/components/obs_card_component.jsx, app/webpack/observations/uploader/components/observation_fields_chooser.jsx, config/locales/en.yml, package-lock.json
- Annotation sections on Identify can be collapsed, and the collapse preferences are separate from those on Observation show pages
- Adds keyboard shortcuts on Identify to open and focus on Projects and ObservationFields
- Keeps the list of ObservationFields offered by default Identify and ObsShow up-to-date with fields added while page is loaded
- Also fixes a bug with the datepicker on the upload page where it was not resetting the date to today when the date was deleted
=> Collapsible Identify Annotations

app/es_indices/identification_index.rb, app/models/taxon_change.rb
- catches and retries after some errors experienced when updating associates
- run a task after a taxon change ends to assess and update observations that for whatever reason have an incorrect taxon
=> Taxon Change retry and cleanup

app/models/observation.rb, spec/models/observation_spec.rb
Addresses this issue
https://github.com/inaturalist/inaturalist/issues/4018
which was discussed with the community here 
https://www.inaturalist.org/posts/25514-clarifying-ancestor-disagreements#activity_comment_29df9130-3fa0-49bb-84c3-d6666ca08b05
It is a minor tweak to how the Community Taxon is calculated that treats Ancestor Disagreements as Ancestor Non-Disagreements when the taxon being disagreed to (previous_observation_taxon) is no longer represented in IDs or as the ancestor of IDs (because they were withdrawn or deleted)
=> Ancestor disagreement change

.rubocop.yml, app/controllers/application_controller.rb, app/views/layouts/bootstrap.html.erb, lib/ambidextrous.rb
This makes a few changes to accommodate the embedded webview showing account settings in the iNatRN app. Some of the assumptions here may not prove to be tenable.
- Removes header and footer for iNatRN requests
- Sets mobile viewport for iNatRN requests for the entire site... even though the entire site is not genuinely responsive
- Bumps up the font size for bootstrap layouts to prevent Safari from auto-zooming in on form inputs that it deems to have inaccessibly small font sizes
- Adds a `noh1` param to remove titles from pages that the requester may already handle, e.g. w/ a nav header in a mobile app
These are all a bit hacky, but they work for now.
=> Detect iNatRN requests, make responses headless and responsive

config/initializers/logstasher.rb
Regarding this issue: https://github.com/inaturalist/iNaturalistAPI/issues/417
When the client browser is calling NodeJs which is then calling Rails (ex: /v1/annotations), the client IP is lost, replaced by the NodeJs internal IP (10.0.0.x). This is visible in the last_ip column and in the clientip field in Kibana logs.
NodeJs app is correctly setting the initial client IP when calling Rails, in the `x-forwarded-for` header:
https://github.com/inaturalist/iNaturalistAPI/blob/main/lib/inaturalist_api.js#L712
https://github.com/inaturalist/iNaturalistAPI/blob/main/lib/inaturalist_api.js#L725
==> options.remote_ip
https://github.com/inaturalist/inaturalistjs/blob/9951a0507da318ba9d7f9464e465d9868d4101da/lib/inaturalist_api.js#L146
==> headers["x-forwarded-for"]
Then, our Rails nginx proxy is …
=> 417 last ip

app/models/taxon_change.rb, config/initializers/find_in_batches_in_subsets.rb, spec/initializers/find_in_batches_in_subsets.rb
Adds a find_in_batches_in_subsets wrapper method that limits query scope. This method is a wrapper of `find_in_batches`. It adds query clauses to search in a 200k ID range at one time, resulting in more efficient querying for _some_ queries on some very large tables
=> Add find_in_batches_in_subsets method

config/initializers/logstasher.rb
I removed this initialization to false in `payload_from_request`, because otherwise it overwrites the setting done here: https://github.com/inaturalist/inaturalist/blob/main/app/controllers/application_controller.rb#L787
=> Wrong value for logged_in field in Rails logs

app/models/taxon.rb, spec/models/taxon_spec.rb
This fix is only solving the issue for the species rank. I don't have enough knowledge to know if this kind of situation can happen on other rank.
If it can then it would be better to improve the `capitalize_scientific_name` method in `Taxon` model.
I could work on it if needed.
Also after deploying this PR, every taxon that was created before it the should be forced capitalized and reindexed. 
Something like this can be enough, just need to manage the case where `×` is used with a real `x` 
```
Taxon.where("name LIKE '%×%'").each(&:save)
```
I don't know if I have to do a script, a task or a migration for it.
=> inaturalist#3988: Add species rank for capitalizing name

app/controllers/observations_controller.rb, app/es_indices/observation_index.rb, lib/observation_search.rb
Akin to the other date filtering parameters (`observed_on`, `year`, `month`, and `day`), this rounds out these options with the `week` option which is already part of the ES observation index.
The use case for this is for <https://naturalists.nyc/>, where we have a eBird-esque bar visual that shows observation frequency for that week, as seen here:
What we'd like is the ability to have each bar link to the iNaturalist observation page for the corresponding week across all years.
Thank you for your consideration!
=> Allow `week` to be passed as a search param for `/observations`

app/controllers/photos_controller.rb, app/controllers/sounds_controller.rb, app/models/controlled_term.rb, app/models/local_photo.rb, app/models/observation_field.rb, app/models/photo.rb, app/models/place.rb, app/models/post.rb, app/models/sound.rb, app/models/taxon.rb, app/models/user.rb, lib/acts_as_flaggable/flag.rb, lib/acts_as_uuidable/acts_as_uuidable.rb, spec/controllers/photos_controller_api_spec.rb, spec/controllers/sounds_controller_api_spec.rb
- Photo and Sound files can be updated if given an UUID of an existing object from the same user
- Also restores ActsAsUUIDable for several models that had it disabled until we indexed `uuid`, which we did quite some time ago. This will help provide better error messages if an object is created with a duplicate UUID as Rails will perform the validation rather than hitting a failure at the DB level with a duplicate key error
=> Upsert for photos and sounds

app/controllers/friendships_controller.rb, app/controllers/relationships_controller.rb, app/models/friendship.rb, spec/controllers/relationships_controller_api_spec.rb
For context, iNat Next is running into a problem where the "follow" button on the user profile is appearing when a friendship with the `following` attribute exists, but otherwise shows an "unfollow" button, but if a relationship exists but does not have the `following == true`, it gets an error from POST /relationships when it tries to create a new friendship, because a record with that friend_id already exists. This will make it so those requests will succeed b/c the record the app is trying to create doesn't need to be created again, just updated with the following attribute.
The thing that might be worth reviewing is changing the shape of the error response for this endpoint. Previous it was returning non-JSON, just a string of concatenated error messages. This will make it return …
=> Add upsert behavior for POST /relationships

app/assets/stylesheets/observations/show.scss, app/es_indices/observation_index.rb, app/models/observation.rb, app/webpack/observations/show/components/app.jsx, app/webpack/observations/show/components/assessment.jsx, app/webpack/observations/show/components/assessment_lazy_load.jsx, app/webpack/observations/show/components/map.jsx, app/webpack/observations/show/containers/app_container.js, app/webpack/observations/show/containers/map_container.js, app/webpack/observations/show/ducks/other_observations.js, config/locales/en.yml, spec/lib/elastic_model/indices/observation_index_spec.rb, spec/models/observation_spec.rb
This adds a user-facing link to an existing tool on obs/edit that lets your interpolate the coordinates of your own observation based on observations you made before and after.
* Adds tests for `Observation#interpolate_coordinates`
* Makes `Observation#interpolate_coordinates` use elasticsearch instead of postgres
* Adds a link to `obs/edit?interpolate_coordinates=true` to the map on obs/show if the user is viewing their own obs AND the obs has no coordinates AND the user has observations with coordinates observed within a day in the future AND a day in the past (the last two require two additional API requests on obs/show)
Ideally I think the user should be shown which observations are being used for the interpolation and the locations of all three points on a map, but I didn't get that …
=> Interpolate your own missing coordinates

app/controllers/quality_metrics_controller.rb, spec/controllers/quality_metrics_controller_api_spec.rb
E.g. voting that a date doesn't look right when an observation has no date. It was already failing to create the record, but the endpoint was returning a success response. This changes the API slightly but IMO this should be considered a bug fix.
=> Fail POST /observations/:id/quality/:metric when attr missing

app/webpack/observations/identify/components/observation_modal.jsx, app/webpack/observations/identify/components/suggestions.jsx
Closes https://github.com/inaturalist/inaturalist/issues/4152
This pull request disables the transition effect in the identify modal gallery (and suggestions gallery), making the behavior consistent with the PhotoGallery in the Observation View. This change addresses user feedback requesting the removal of the slide animation when switching between photos.
The transition effect removal can be observed in the provided video.
Note: The suggestion tab functionality cannot be tested locally due to lack of access to the vision API.
[disabled-transitions.webm](https://github.com/inaturalist/inaturalist/assets/16878981/7bc06330-9dbc-42d6-80c7-c745b39ebb20)
Additional note: The same modal is used for compare taxa.
=> feat: :wheelchair: disable gallery animation to reduce motion sickness

app/webpack/observations/identify/ducks/suggestions.js
Closes https://github.com/inaturalist/inaturalist/issues/4146
This fixes the issue, where the compare observation modal failed to update the suggested taxon upon user interaction. The root cause was identified as unintended caching behavior, originally designed to preserve filter states in the identification modal.
Implemented a check to determine if the taxon object attribute has changed when a user clicks on a different compare button. This ensures that the compare observation modal updates the suggested taxon accordingly.
- Manual tests were conducted to verify that the compare observation modal now correctly updates the suggested taxon.
- Additional tests confirmed that the identification modal's caching and filter preservation functionalities remain unaffected by this change.
=> fix: :bug: fix stale compare modal due to caching

app/controllers/flags_controller.rb
This PR fixes the issue #4153  
* The code explicitly looked for flags that matched the reason/user/taxon and unresolved the flag. This PR removes that code path. 
* This is my first PR in this repo, so let me know if I need to do anything else!
=> [Bug Fix] New flag not created, old flag unresolved if flag reason matches user's previous flag for taxon

app/views/taxa/_description.html.haml
I found an issue today where taxobox uses old available fields for the taxobox. This issue has been known for some time - see this discussion, https://forum.inaturalist.org/t/fix-taxobox-parameters-in-create-this-page-on-wikipedia-prompt/18395/12. I've tried to make minimal efforts to remove those fields and to add others.
=> fix: Edited taxobox for Wikipedia entries

app/controllers/users_controller.rb, app/views/users/delete.html.haml, config/locales/en.yml, db/structure.sql, spec/controllers/users_controller_spec.rb
This allows mobile clients showing these pages in webviews to detect if deletion was successful.
=> feat: add param to redirect URL after account deletion

app/assets/javascripts/ang/templates/observation_search/identifiers_table.html.haml, app/assets/javascripts/ang/templates/observation_search/observers_table.html.haml, app/assets/javascripts/ang/templates/observation_search/taxa_grid.html.haml
Currently, when visiting an observation tab (e.g., view=species, view=observers, or view=identifiers), if the result set is empty, the loading spinner continues to display indefinitely. For example: https://www.inaturalist.org/observations?place_id=143465&subview=map&taxon_id=41644&view=observers.
This patch removes the loading spinner when the result set is empty, improving the user experience.
We can use the corresponding `noXXXX` function, which correctly returns false while the search is ongoing. Alternatively, we could use the `searchingStopped` function directly, but that would require some refactoring to make it compatible with the infinite scroll and loading icon behavior.
Cheers
Hannes
=> fix: :bug: remove loading spinner if result is empty

app/models/project_user.rb, app/models/project_user_invitation.rb, app/models/user_block.rb, spec/models/project_user_invitation_spec.rb, spec/models/project_user_spec.rb, spec/models/user_block_spec.rb
Fixes https://github.com/inaturalist/inaturalist/issues/4108
Regardless of project type,
- When blocking a user:
- remove blocker and blockee from one another's projects
- delete any pending project invitations
- Prevent either user from adding the other to their project
This does not affect the requirements of any umbrella project.
=> Blocking removes users from each other's projects

app/webpack/observations/show/components/identifiers.jsx, app/webpack/observations/show/components/user_with_icon.jsx
Closes #4216 
This update introduces a new optional parameter, `subtitleLinkOverwrite`, to the ` user_with_icon` React component. This parameter allows for overriding the default link behavior.
This parameter is used to update the link on the observation page for the top identifiers widget, specifically pointing it to, the identifications page eg. https://www.inaturalist.org/identifications?user_id=samfellows566&taxon_id=4345.
We could add a parameter for `for=others`, but I believe the count currently includes self-identifications as well.
Cheers
Hannes
=> fix: :bug: set correct link for identifier icon subtitle

app/models/taxon.rb, app/models/taxon_description.rb
Some taxa were not getting indexed with a `wikipedia_url` b/c they did not have a `TaxonDescription` for the `en` locale, but they did have one for the `en-US` locale, e.g. https://www.inaturalist.org/taxa/231783-Strangalia-acuminata
=> fix: index wikipedia_url even if description is for en-US

db/migrate/20231206194146_add_path_versions_for_some_attachments.rb, db/structure.sql
Change for migration in https://github.com/inaturalist/inaturalist/pull/3957. The migration needs to be deployed first as when we deploy we run webpack, which loads the Rails environment. If the migration was not yet run, this would throw an error due to columns missing for the added `paperclip_path_versioning` attachment configuration
=> Migrations only for paperclip-path-versioning

app/views/taxa/_description.html.haml
This modifies the template for Wikipedia suggested article content, ensuring that the date field doesn't throw an error on Wikipedia.
Cf. https://en.wikipedia.org/wiki/Help:CS1_errors\#bad_date
=> fix: Change wiki date format

app/webpack/taxa/show/containers/top_identifier_container.js, app/webpack/taxa/show/containers/top_observer_container.js
If a user's state includes a `preferred_place_id`, it is currently appended to the top identifier and observer links on the taxa page. While this behavior could be relevant in some contexts, it may not always make sense, as the counts are global and not restricted to a specific place.
This pull request removes the `preferred_place_id` from the object when generating these links, ensuring the links remain global as intended.
Cheers
Hannes
=> fix: :bug: remove preferred_place_id from leader widget

app/webpack/observations/show/components/map_details.jsx
Fixes: https://github.com/inaturalist/inaturalist/issues/4252
**Solution**: This pull request addresses the issue by truncating the float to 5 decimal places instead of rounding. Truncating in this context is preferable as it avoids the introduction of rounding errors and maintains a precision of approximately 1 meter, which is sufficient for most needs.
Alternative Solutions Considered:
- Using `toFixed(5)` would result in trailing zeroes in all cases, which is undesirable.
- Using `NumberFormat` with `minimumFractionDigits` would have similar issues to lodash rounding, potentially leading to precision problems with floats.
By truncating the float using string converstion, it is ensured a consistent and accurate representation of the coordinates without unnecessary trailing zeroes. …
=> fix: :bug: rounding could lead to truncation of significant zeroes

app/models/observation.rb
Closes https://github.com/inaturalist/inaturalist/issues/4086
In this update, I have added the UUID to the basic columns for the export, positioning it as the second column. This placement is consistent with the default basic export, and it aligns with the position of the ID column, given that the list is not in alphabetical order.
~~The spec test did report some errors, but I believe it is not related to the update, as they are all some geoprivacy problems.~~ (only local issue as the CI did not complain)
`bundle exec rspec spec/models/observations_Export_flow_task_spec.rb`
=> feat: :sparkles: add new default export field uuid

app/webpack/observations/show/components/app.jsx
#4288 
I think it’s better to simply not display the button rather than disabling it. Currently, it also shows errors in the console if you click on it.
This is my first time contributing to an open source project; any feedback is welcome :)
=> #4288 not showing followButton with not logged users

app/models/cohort_lifecycle.rb, app/models/segmentation_statistic.rb
Related to #4285
* Uses dates throughout the script instead of times
* Accepts date as a method parameter
* As a result can be run on days other than today
* This will help prevent issues around daylight savings. We can schedule the task for early in the day UTC to run on data from the previous day UTC, and the schedule can stay the say regardless of local DST
=> Small refactor of CohortLifecycle

app/assets/stylesheets/observations/show.scss, app/webpack/observations/show/components/assessment.jsx, config/locales/en.yml
Previously we've kept this string large to proviede the maximum amount of context for translators, and changed the key every time we updated the text, requiring them to retranslate everything on the assumption that Crowdin's Translation Memory feature will show the previous translation. We've recently learned there is an unknown limit on the size of string TM will work for, which changes the context/change resilience tradeoff in favor of smaller strings.
=> refactor: split DQA help into smaller strings

app/assets/javascripts/ang/factories/observations.js.erb, app/webpack/projects/show/ducks/project.jsx
- add to the species_counts API call the [new parameter](https://github.com/inaturalist/iNaturalistAPI/commit/96126150e08c146d4b9f55a1bad0ecefe4ce119c) `include_ancestors` to prevent the need for subsequent taxon details API calls to fetch taxon ancestors
- ensure that if the user is testing API v2, taxon ancestors include the attribute `preferred_common_names` in order to display multiple common names
=> Potential improvement for explore-taxon-addition-subtraction

app/assets/javascripts/ang/controllers/observation_search.js.erb, app/assets/javascripts/ang/factories/observations.js.erb, app/assets/javascripts/ang/templates/observation_search/taxa_grid.html.haml, app/assets/stylesheets/observations/search.scss, app/views/observations/index.html.haml, app/webpack/projects/show/ducks/project.jsx, config/locales/en.yml
* Add buttons to taxon search results in Explore to refine the search by an ancestor of that taxon or exclude an ancestor of that taxon (staff-only for now)
* Show the currently selected values for `without_taxon_id` below the taxon autocomplete in the Explore header
=> Add taxon inclusion / exclusion to Explore

app/models/taxon_change.rb, spec/models/taxon_swap_spec.rb
Taxon changes skip hidden identifications to prevent them from being re-added as unhidden with updated taxon #4276
=> Taxon changes do not update hidden identifications

app/views/taxa/_description.html.haml
References currently created this way causes errors in citation templates on en wiki because the template does not accept days with leading zeros (see zero-padding: https://en.wikipedia.org/wiki/Help:CS1_errors#bad_date )
%-d inserts the day with no leading 0 instead.
=> Remove 0 padding from day as this causes a CS1 error on en wiki.

app/webpack/shared/components/user_text.jsx
fix #3818
It's not the best solution, but I think it's acceptable. I would first check in Elasticsearch how many descriptions contain the characters "/@" in cases where it's not part of a link. I can't think of a reason why someone would do that, but I would check just in case..
I would do it myself, but I don't have access to the database (or I don't know how to access it). I appreciate any tips on how to populate my local environment with real data.
=> #3818 fix broken links containing at sign

app/models/check_list.rb, app/models/list.rb, app/models/project_list.rb, spec/models/list_spec.rb
It looks to me like the most straightforward way to address this issue is to override the title attribute for lists, and substitute the :life_list translation with the current list owner for the legacy title.
Note that this will mean that anyone in a non-English locale will now see a localized version of the "xxx's Life List" text instead of the hard-coded English phrase. From looking at the [old life list code](https://github.com/inaturalist/inaturalist/blob/a77a4153b002d3d12d955299cd08597819fe9817/app/models/life_list.rb#L239-L243), I see that there was also a taxon-specific version of a life list, but I did not see an appropriate translation for this, so the substitution only replaces the "xxx's Life List" portion of the title.
Please let me know if a different approach is preferred …
=> fix: replace legacy life list titles (#3755)

Gemfile, Gemfile.lock, app/models/user.rb, app/models/user_privilege.rb, db/migrate/20241217203007_add_canonical_email_to_users.rb, db/structure.sql, spec/models/user_privilege_spec.rb, spec/models/user_spec.rb
* Adds canonical_email column to the users table and populates for new users and those that change their email address
* Fixes bug preventing users from earning Organizer privilege after confirming their email address
=> Add canonical email to users

app/controllers/messages_controller.rb, app/models/message.rb, app/models/user.rb, db/migrate/20250130003627_add_sent_at_to_messages.rb, db/structure.sql, spec/factories/messages.rb, spec/models/message_spec.rb, spec/models/user_spec.rb
This only goes part way toward WEB-367 by handling the case where the sender is suspended but their messages are not spam. I'm mostly interested in critiques of the approach using the `sent_at` column in the `messages` table. Overly complicated? Edge cases I'm missing?
Uh, there are a lot of Rubocop changes too, so it might help to look at things commit by commit.
Update: this PR now closes WEB-367.
=> fix: resend messages by unsuspended user

app/controllers/observations_controller.rb, app/es_indices/observation_index.rb, app/webpack/observations/show/components/observations_highlight.jsx, app/webpack/observations/show/containers/nearby_container.js, app/webpack/observations/show/containers/similar_container.js, app/webpack/observations/show/ducks/observation.js, app/webpack/observations/show/ducks/other_observations.js, app/webpack/taxa/show/components/app.jsx
* Data for More from {login}, Nearby observations, and Observations of relatives are lazy loaded
* The components themselves were already being lazy loaded, but the data for them was being fetched when the observation loads. This wasn't saving us much as the rendering is fast - its the API queries that are the largest performance hit
* Queries for both nearby and relatives are improved by leaving off the `not_id` parameter, and instead fetch 1 extra result in case the loaded observation is one of the 7. This will make it so each query is not unique to the loaded observation, increasing the chance the query might get cached
* The query for nearby observations drops precision of the queried lat/lng to again make the query a little less specific to the loaded observation and might be able to …
=> Obs show highlights data are lazy loaded

app/assets/stylesheets/projects/new2.scss, app/es_indices/place_index.rb, app/es_indices/project_index.rb, app/models/project.rb, app/models/project_observation_rule.rb, app/webpack/projects/form/components/project_form.jsx, app/webpack/projects/form/components/regular_form.jsx, app/webpack/projects/form/form_reducer.js, app/webpack/projects/shared/models/project.js, app/webpack/projects/show/components/app.jsx, app/webpack/projects/show/ducks/project.jsx, config/locales/en.yml, spec/lib/elastic_model/indices/project_index_spec.rb, spec/models/project_observation_rule_spec.rb, spec/models/project_spec.rb
* When enabled via project preferences, collection projects can delegate observation requirement defining to an umbrella project
* When enabled, the delegated umbrella project can define rules and sync them to delegating subprojects
=> Some umbrella projects can sync project rules to subprojects

app/webpack/observations/show/components/activity_item.jsx, app/webpack/observations/show/components/community_id_modal.jsx, app/webpack/observations/show/components/hidden_activity_item.jsx
* remove hidden IDs from Community Taxon modal
* try to remove taxon from a hidden ID in disagreement notices for other
identifications (specifically, it hides the taxon disagreed with if that
taxon or its ancestors are associated with a hidden identification AND they
are *not* associated with a taxon or its ancestors from non-hidden
identification)
Closes WEB-547
=> feat: remove hidden IDs from Community Taxon modal

docker-compose.override.yml.example, docker-compose.yml
On make services
```
WARN[0000] /Users/elharo/inaturalist/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] /Users/elharo/inaturalist/docker-compose.override.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
docker compose up -d es memcached redis pg
WARN[0000] /Users/elharo/inaturalist/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
WARN[0000] /Users/elharo/inaturalist/docker-compose.override.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
```
=> Remove obsolete version attribute

app/controllers/observations_controller.rb, config/locales/en.yml, db/migrate/20250204222646_change_collation_on_tags_name.rb, db/structure.sql, spec/models/observation_spec.rb
Took a little digging, but the underlying problem is that acts_as_taggable_on assumes tags are case-insensitive, and when it tries to find an existing tag, it does something like `where( "LOWER(name) = ?", new_tag_name.downcase )`. However, with the default Postgres collation for a VARCHAR column, `LOWER()` behaves differently for some Turkic characters than Ruby's `downcase` method, so in the case of the photo in the issue, the keyword "İç Anadolu Bölgesi" gets lowercased in different ways:
Postgres `LOWER()`: iç anadolu bölgesi
Ruby `downcase`: i̇ç anadolu bölgesi
(the first letters are slightly different)
When acts_as_taggable_on received that as a potential tag, it tried to find an existing tag, failed b/c of the different lowercasing behavior, tried to create a *new* tag, but that …
=> fix: allow Turkic tag reuse

app/helpers/application_helper.rb
Most language codes in `I18n.locale` do not include a region, therefore returning an empty string for `cctld_from_locale`.
This fix uses the request header `HTTP_ACCEPT_LANGUAGE` as a sane fallback for this cases.
Cheers
Hannes
=> fix: localize GMaps using browser locale if no region in user locale

config/initializers/omniauth.rb
It seems to me I often need to signin again, and each time I signin again with google, the site asks for consent to access services I already consented. It seems to me, most sites on internet doesn't behave like this and I find this signin flow annoying.
I tested with a local sinatra app with omniauth and a omniauth-google-oauth2 strategy.
I first used the same settings (`:prompt => "consent"`) , authenticated with my 1st user.
Then I re-opened, re logged in , and had the consent again.
Then, I switched to `:prompt => "select_account"`, re-opened the app, and logged in, with selecting my account like previsously, but without seeing the consent again.
I then tested with another google account, with `select_account`, the 1st login prompt for selecting account and consenting to used service, …
=> fix: don't ask consent for every google oauth2 signins (only at signup)

CONTRIBUTING.md
Following the existing instructions without this added step leads to:
```
~/inaturalist$ make services
docker compose build --parallel es memcached redis pg
docker compose up -d es memcached redis pg
unable to get image 'redis:6.0.3': Cannot connect to the Docker daemon at unix:///Users/elharo/.docker/run/docker.sock. Is the docker daemon running?
make: *** [services] Error 1
```
@kueda
=> docs: document need to start docker before making services

app/assets/javascripts/ang/templates/observation_search/results_grid.html.haml, app/assets/javascripts/ang/templates/observation_search/results_table.html.haml, app/assets/stylesheets/observations.scss
Closes: https://github.com/inaturalist/inaturalist/issues/4165#issuecomment-2619792256
Previous idea now closed: https://github.com/inaturalist/inaturalist/pull/4220
- added flex style for meta info items
- added new icon in front of date (results_grid)
- some minor adjusments to the two date variants and their `ng-show` | `ng-hide` logic. (We could do a `ngIf-Else` and template but yeah, don't actually know what this old angular can handle safely)
=> feat: :sparkles: flex styling for observation results meta information

CONTRIBUTING.md, app/assets/javascripts/ang/templates/observation_search/results_grid.html.haml, app/assets/javascripts/ang/templates/observation_search/results_table.html.haml, app/assets/stylesheets/observations.scss, app/assets/stylesheets/observations/search.scss
* Add an icon before the time to avoid confusion with other numbers like ID count
* Wrap metadata when quality grade label is too wide
* Avoid layout overlaps in list view
Closes WEB-506
=> fix: separate & wrap metadata items better in Explore

app/webpack/taxa/show/components/charts.jsx
This a WIP and a workaround to make the history chart show the last 10 years data by default.
The zoom was enable but didn't work since the migration from C3.  I made it work back.
The option `axis.x.extent` use for creating a default zoom/subchart doesn't seems to work or I am missing something. I have created an [issue](https://github.com/naver/billboard.js/issues/3768) on billboard.js for it.
To workaround this option I forced a zoom on the chart after the initialization. It's working when the Taxon has recent observation but I think it won't work when the last observation is too old.
This solution is only a Frontend solution. 
It would probably be better that the server is sending only the 10 years data to the client. Since I don't know how it was working before I preferred to let all …
=> fix: zoom taxon detail history chart to last 10 years

app/es_indices/observation_index.rb, app/models/observation_field_value.rb, app/webpack/observations/show/components/observation_field_value.jsx, config/locales/en.yml
fix: #4184
API PR: https://github.com/inaturalist/iNaturalistAPI/pull/480
First time with Ruby, Im sorry if I made some mistake.
This approach only works for new obfv updates. in ElasticSearch we are not persisting the updater, but it is where we are taking the rest of the data from. I couldn't find a best way to do this.
I expected to collect this data from postgres but we r using elastic for this. Why?
Thanks for the feedback :)
=> feat: add updater field in observation ofvs

app/webpack/taxa/show/components/charts.jsx
* only zooms when there's 10 years worth of data, and avoids date formatting
problem.
* eslint fixes
Creates label overlap when zoomed out but that seems like the lesser of two
evils for now.
=> fix: zoom taxa/show history only when necessary

app/assets/stylesheets/users/registrations.scss, app/controllers/provider_authorizations_controller.rb, app/models/user.rb, spec/controllers/provider_oauth_controller_spec.rb, spec/controllers/registrations_controller_api_spec.rb
* feat: defaults new 3rd party auth users into CC BY-NC licensing
* fix: allow users to opt-out of licensing at signup, which was apparently
broken
* fix: sign in new 3rd party auth users immediately; previously there was a
bug where auth would work but you wouldn't be signed in and you'd have to
try again before it would work
* fix: restore partial signup form displayed to new 3rd party auth users after
they first sign in, requiring an email address and consents, but also
providing an opportunity to opt out of licensing
=> feat: default new 3rd party auth users into content licensing

app/views/messages/new.html.haml
fix #4408
For some reason, this class applies a 100% width to the image, which breaks the entire layout. Removing the class, I’d say everything works perfectly.
=> fix: unstretch generic user icon when sending new message

app/assets/stylesheets/bootstrap-inat.scss, app/assets/stylesheets/observations/identify/observation_modal.scss, app/assets/stylesheets/observations/show.scss, app/assets/stylesheets/observations/uploader.scss, app/webpack/observations/identify/actions/current_observation_actions.js, app/webpack/observations/identify/actions/current_observation_actions_names.js, app/webpack/observations/identify/actions/identification_actions.js, app/webpack/observations/identify/actions/observations_actions.js, app/webpack/observations/identify/actions/observations_actions_names.js, app/webpack/observations/identify/containers/progress_chart_container.js, app/webpack/observations/identify/containers/quality_metrics_container.js, app/webpack/observations/identify/containers/search_bar_container.js, app/webpack/observations/identify/ducks/suggestions.js, app/webpack/observations/identify/reducers/search_params_reducer.js, app/webpack/observations/identify/webpack-entry.js
Prevents an unexpected nav back to the Info tab after you've added an identification and navigated to another tab before the ident creation request completes.
Also fixes some minor Identify layout problems.
Closes WEB-614
=> fix: prevent unexpected nav back to Info tab on Identify

app/assets/stylesheets/bootstrap-inat.scss, app/assets/stylesheets/observations/show.scss, app/assets/stylesheets/observations/uploader.scss
Restrict previous changes to btn-nostyle to obs detail.
=> fix: restore include / exclude ancestor button in Explore

app/models/moderator_action.rb, lib/has_subscribers.rb, spec/models/moderator_action_spec.rb
Creating a HIDE ModeratorAction deletes all UpdateActions where the moderated item is a resource or a notifier, and prevents the creation of new UpdateActions when the resource or the notifier is hidden.
One implication is that if the offending content is later unhidden, the people it notified on creation will not be notified. That strikes me as fine, but kind of up for debate. Another approach might be to update the existing UpdateAction and clear out its subscribers from ES, but that seemed excessively complicated.
=> fix: remove notifications about comment when hidden

app/models/observation_field_value.rb, app/models/update_action.rb, spec/models/observation_field_value_spec.rb
- Notifications are not generated when muted users update observation fields
- Blocked users are not allowed to update observation fields
=> fixes related to observation field value updates by muted or blocked users

app/assets/javascripts/application_bundle.js, app/assets/javascripts/i18n/default_value_pre_fallback.js, app/views/stats/year.html.haml, app/webpack/shared/components/error_boundary.jsx, app/webpack/stats/year/components/app.jsx, app/webpack/stats/year/components/donate_content_2022.jsx, app/webpack/stats/year/components/observations.jsx, app/webpack/stats/year/components/observations_grid.jsx, app/webpack/stats/year/components/publications.jsx, app/webpack/stats/year/components/store_content.jsx, app/webpack/stats/year/components/translators.jsx
* Replace override of defaultValue behavior in I18n.js with
defaultValuePreFallback
* Switch to jsdelivr from unpkgs for some YIR libs due to flaky loading
* Wrap some YIR components in ErrorBoundaries so errors there don't take out
the entire page
Re: defaultValue, we had overridden this option so that the default value
would be used even if fallback translations existed, which is *not* how it
works in Rails, and is frankly just kind of confusing. Instead, I've changed
the option to defaultValuePreFallback to be explicit about the fact that it
gets used before even checking for fallback translations.
FWIW, this is meant for use in situations where an alternate translation
exists in the current locale that would be better than the default English
fallback that exists for all locales. …
=> fix: show translations for sort by options in Identify

app/webpack/taxa/show/components/taxonomy_tab.jsx
fixes https://github.com/inaturalist/inaturalist/issues/4428
Removed the whole `ul` element, as both buttons depend on a logged-in user.
=> fix: taxon page remove name buttons elements for visitors

app/assets/javascripts/announcements/form.js, app/models/announcement.rb, app/views/announcements/_form.html.haml, app/views/announcements/show.html.haml, spec/controllers/announcements_controller_api_spec.rb
* fix: exclude siteless anncs after excluding dismissed anncs
* fix: include no-locale anncs even if user dismissed locale-specific ones
* fix: show current client choice when editing announcement
* feat: add impressions count to announcements/:id
=> fix: repair announcement targeting

app/controllers/announcements_controller.rb, app/models/announcement.rb, app/models/user.rb, app/views/announcements/_form.html.haml, app/views/announcements/index.html.haml, app/views/announcements/show.html.haml, config/locales/en.yml, db/migrate/20250326223846_add_user_to_announcements.rb, db/migrate/20250327191619_add_target_creator_to_announcements.rb, db/structure.sql, spec/factories/announcements.rb, spec/models/announcement_spec.rb, tools/donorbox-plans.rb, tools/donorbox.rb, tools/donorbox_user_donations.rb
Closes WEB-638
Also
* backoff behavior for donorbox scripts; they may not have been working
reliably without this
* fixed bug where targeting unconfirmed users was blocking last obs date
filters from working
=> feat: allow announcement to target only the user who made it

app/controllers/application_controller.rb, app/controllers/observations_controller.rb, app/models/observation.rb, db/migrate/20250328144900_add_uuid_to_deleted_observations.rb, db/structure.sql, spec/controllers/observation_controller_spec.rb
* When visiting observation details pages, using IDs or UUIDs, if the observations have been deleted from the database but are still in Elasticsearch for some reason, remove them from Elasticsearch
* Observation details pages return a 410 instead of a 404 when we know the observation once existed but has since been deleted
* Adds migration to add observation UUID to DeletedObservations, and indexes it as well as indexes the existing observation ID column for more efficient deleted observation lookups
=> Remove orphan deleted observations from index

app/assets/stylesheets/observations/identify/observation_modal.scss, app/assets/stylesheets/shared/easyzoom.scss, package-lock.json
fix #4424
I'm not a CSS master, so I hope I'm not falling into any bad practices, but this apparently fixes the bug.
I've also found another possible bug. Some images (in my case, it's the first one, but I think it doesn't depend on the order but rather on the image size) don't allow zooming when viewed on my ultrawide monitor, but they do on a smaller monitor. I'm investigating the reason why. Is this behavior familiar to you?
=> fix: zoom bug in Identify images

app/models/observation.rb
Previously if you agreed with the observer's ID, `num_identification_agreements` would be zero... despite tests to the contrary. This does fix it, but I wasn't able to write a test to prove it was broken. Easy to repro on a working site, though.
Related to WEB-612
=> fix: set num_identification_agreements when agreeing w/ observer ID

app/webpack/observations/show/components/quality_metrics.jsx
I thought #4473 would fix [WEB-612](https://linear.app/inaturalist/issue/WEB-612), but as I was trying to update the data, I realized that while we were using `num_identification_agreements` to control the offending part of the DQA, we don't actually use that to set the quality grade, b/c the quality grade concerns the Community Taxon, and `num_identification_agreements` concerns the Observation Taxon. So an obs might have an Observation Taxon of _Abra cadabra dubius_ b/c of an ID sequence like this:
Observation: _Abra cadabra dubius_
User A: _Abra cadabra_
User B: _Abra cadabra_
but the Community Taxon is _Abra cadabra_. Since `num_identification_agreements` is relative to the Observation Taxon its value is 0 (no one agrees with the observer), but the obs is Research Grade b/c it has a …
=> fix: use Com Taxon presence to mark DQA as has ID supported by 2 or more

app/webpack/observations/identify/actions/current_observation_actions.js, app/webpack/observations/identify/reducers/current_observation_reducer.js
Potentially fixes WEB-688 / #4478 in which annotations for previously viewed observations appear in Identify, particularly under slow network conditions.
I can't replicate that bug, so I'm just working on the theory that there are attempts to update the current observation that happen after very slow network requests.
=> fix: prevent stale updates to current obs in Identify

db/migrate/20250409212827_alter_identifications_indices.rb, db/structure.sql
Replace an index on both `observation_id` and `created_at` with an index on only `observation_id`
=> refactor: simplify identifications index on observation_id

app/controllers/identifications_controller.rb, app/controllers/lists_controller.rb, app/controllers/observation_fields_controller.rb, app/controllers/shared/lists_module.rb, app/controllers/users_controller.rb, lib/dj_makara_plugin.rb
* allow more endpoint to query replica DB
* allow more DJ to start off by querying replica DB
* preload more associations for some endpoints that were generating a lot of queries
=> refactor: more actions and DJs use replica and more association loading

app/models/subscription.rb, app/models/update_action.rb, lib/has_subscribers.rb
This modifies `HasSubscribers::notify_subscribers_with` which is the HasSubscribers method we spend the most processing time on. We were already fetching all UpdateActions for a notifier, then making subsequent more specific requests with more filters for each subscribable, when we might have the information on hand from the earlier call. The change made is to leverage already fetched Elasticsearch records when possible, saving an ES query each subscribable, otherwise the original logic will be used
=> refactor: reduce number of ES queries needed for notify_subscribers_with

app/models/place.rb, spec/models/place_spec.rb
Affected places will need to have their slugs updated after this is merged.
WEB-679
=> fix: prevent places w/ slugs w/ leading numbers from being suggested

app/models/observation.rb, lib/has_subscribers.rb, spec/models/check_list_spec.rb, spec/models/identification_spec.rb, spec/models/listed_taxon_spec.rb, spec/models/observation_basics_spec.rb
* Observation notify subscribers of user and notify mentioned users are not longer delayed as they are fast tasks and using delayed jobs can add an unnecessary amount of overhead
* Observation triggering of CheckList.refresh_with_observation is also no longer delayed. This is a job that queues other jobs and is generally quite fast
* Decrease priority of Observation notify subscribers of places and taxa. These jobs are not as important as say notifying users of identification updates, so they can have a lower priority
* In has_subscribers, change order of operations to lookup existing update actions only when there may be users to notify. This can save time for tasks like notify subscribers of user when there are no subscribers to the given user
=> Notification delay and priority updates

app/controllers/observations_controller.rb
Unforuntately the iNat iOS app is hard-coded to expect 404 responses when DELETEing obs that no longer exist, so until we can update that we should continue to respond with 404.
WEB-562
=> fix: restrict 410 responses for obs to GET requests

app/webpack/users/edit/components/profile.jsx
=> fix: prevent user settings from going blank after deleting email & username

app/models/user.rb, app/webpack/users/edit/components/checkbox_row.jsx, app/webpack/users/edit/components/content.jsx, config/locales/en.yml, spec/controllers/users_controller_api_spec.rb, spec/models/user_spec.rb
Previously if a user changed their license preference and requested that it be retroactive, the task was happening in the request, which caused it to time out if the user had a lot of observations.
Closes WEB-682
=> fix: ensure license changes happen in a delayed job

app/models/place_geometry.rb, config/locales/en.yml, spec/models/place_geometry_spec.rb
RGeo allows polygons that have multiple points that are identical, and when that happens their bounding boxes are points, which causes problems for us. This should prevent it.
Closes WEB-663
=> fix: prevent creation of polygons without bounding boxes

app/es_indices/taxon_index.rb, app/es_indices/taxon_photo_index.rb, app/models/photo.rb, app/models/shared/license_module.rb, app/webpack/taxa/shared/ducks/taxon.js, app/webpack/taxa/shared/util.js, spec/lib/elastic_model/indices/taxon_index_spec.rb
related to WEB-551. Adds an attribute `attribution_name` to taxon photos in the taxon index that can be used for better attribution of photos, particularly those not associated with iNaturalist users or those with a CC0 license
=> feat: index attribution_name for taxon photos

app/assets/javascripts/announcements/form.js, app/models/announcement.rb, app/views/announcements/_form.html.haml, spec/controllers/announcements_controller_api_spec.rb, spec/controllers/users_controller_spec.rb, spec/models/announcement_spec.rb
If one of the start date options is set, the announcement should not appear for signed out users. This also modifies the form so the person making/editing the announcement will not be able to target "any" or logged out users if they choose one of the start date options.
Closes WEB-699
=> fix: prevent anncs targeting user signup date and logged in

app/models/user.rb
FWIW, the query to fetch all relevant IDs can still be a bit slow, but each batch is then only a few seconds.
Closes WEB-698
=> refactor: update licenses in batches when changing user preference

app/webpack/users/edit/components/account.jsx, app/webpack/users/edit/components/app.jsx, app/webpack/users/edit/components/checkbox_row.jsx, app/webpack/users/edit/components/content.jsx, app/webpack/users/edit/components/notifications.jsx, app/webpack/users/edit/components/profile.jsx, app/webpack/users/edit/components/save_button.jsx, app/webpack/users/edit/containers/account_container.js, app/webpack/users/edit/containers/app_container.js, app/webpack/users/edit/containers/checkbox_row_container.js, app/webpack/users/edit/containers/content_container.js, app/webpack/users/edit/containers/favorite_projects_container.js, app/webpack/users/edit/containers/notifications_container.js, app/webpack/users/edit/containers/profile_container.js, app/webpack/users/edit/containers/save_button_container.js, app/webpack/users/edit/containers/taxon_name_priorities_container.js, app/webpack/users/edit/containers/taxon_name_priorities_dragdrop_container.js, app/webpack/users/edit/ducks/favorite_projects.js, app/webpack/users/edit/ducks/network_sites.js, app/webpack/users/edit/ducks/relationships.js, app/webpack/users/edit/ducks/user_settings.js, app/webpack/users/edit/webpack-entry.js
* make user_settings.js export a reducer that reduces a part of state called userSettings
* action in user_settings.js that sets userSettings is now called setUserSettings
* action in user_settings.js that actually posts data to the server is now called postUserSettings
Closes WEB-690
=> refactor: reduce reducer confusion in users/edit

app/es_indices/observation_index.rb, app/webpack/observations/identify/components/filter_checkbox.jsx, app/webpack/observations/identify/components/filters_button.jsx, config/locales/en.yml, spec/lib/elastic_model/indices/observation_index_spec.rb
Adds `disagreements=true` param to the Identify UI to allow people to search for observations that have some disagreement. Requires a new `identification_disagreements_count` attribute in the observations index, so we'll need to reindex ~20M observations, which I estimate will take about 2 weeks with a single process.
In terms of review, I'm never sure if I'm changing the index in the right way or not, so just want to double check. I imagine I'll need to update the production index before deploying like this:
```ruby
Observation.__elasticsearch__.client.indices.put_mapping(
index: Observation.index_name,
body: {
properties: {
identification_disagreements_count: { type: "integer" }
}
}
)
```
Identify integration depends on https://github.com/inaturalist/iNaturalistAPI/pull/517
WEB-508
=> feat: allow filtering observations by whether there are disagreements

app/controllers/users_controller.rb, app/models/emailer.rb, app/models/update_action.rb, spec/factories/subscriptions.rb, spec/factories/update_actions.rb, spec/models/update_action_spec.rb
The dashboard stubs out UpdateActions for additional content associated with resources that might generate notifications, e.g. if you are subscribed to a journal post and an UpdateAction exists for a comment on that post, you will both be notified about it on your dashboard *and* all the additional comments on that post will be loaded as well, so you can see the full context. However, we were doing that loading even if you had unsubscribed from the post, so in situations where you were subscribed, a comment was made and thus an UpdateAction existed for you, but when you unsubscribed from the post, we were showing you that UpdateAction as well as all the subsequent comments made after you unsubscribed, which made it seem like you were still subscribed to subsequent updates. This stops that …
=> fix: stop dashboard updates after user unsubscribed from resource

app/views/users/leaderboard.html.haml
fixes: https://forum.inaturalist.org/t/minor-leaderboard-shows-identification-for-month-year-instead-of-actual-date/65554
The change corrects the pluralization of the word "identification" to "identifications", which fixes the wrong translation variable naming. Additionally adjusted the syntax for consistency (consistent key-value pairs with colons instead of hash rockets).
Cheers
Hannes
=> fix: pluralize leaderboard identifications title for previous month correctly

app/helpers/application_helper.rb, app/views/users/index.html.erb, app/views/users/leaderboard.html.haml
fixes: https://github.com/inaturalist/inaturalist/issues/4594
Modified the _/people_ identification page to ensure it links to the correct URL with the appropriate parameters, as specified in the issue.
Updated the _/people/leaderboard/x/x_ page to utilize the translation string.
Cheers
Hannes
=> fix: link identifications leaderboard users to their identifications

app/models/site_statistic.rb
We should probably add also this exclusion filter to:
https://github.com/inaturalist/inaturalist/blob/main/app/models/site_statistic.rb#L195
https://github.com/inaturalist/inaturalist/blob/main/app/models/site_statistic.rb#L362
as these taxon change identifications are generated and should not be counted as user's identifications
=> WEB-737 Ignore Taxon Change when calculating Active Users

app/assets/javascripts/application_bundle.js, app/assets/javascripts/i18n_bundle.js
Since the Uploader uses a different layout, it wasn't actually loading all of
our pluralization customization. This consolidates that stuff into a single
bundle.
Closes WEB-731
=> fix: show pluralizations in all languages in obs Uploader

app/views/announcements/_announcement.html.haml, app/views/announcements/index.html.haml, app/views/announcements/show.html.haml
Puts the announcement in a shadow DOM with our bootstrap styles but nothing else. This definitely needs testing with some actual announcements b/c this changes the assumption that announcements have access to all the styles and Javascript available in the environment in which they're displayed (using an iframe would come with the same cost).
=> fix: prevent announcements CSS from affecting the rest of the site

Gemfile.lock
Terrapin 1.1.0 fixed  a bug, `Don't hang on stderr`, that we were occasionally affected by
=> fix: update terrapin gem, related to WEB-754

Gemfile, Gemfile.lock
Updates delayed_job_active_record to [leverage](https://github.com/collectiveidea/delayed_job_active_record/commit/38613dbad9a3b041b4a6cef4767f916a0296c3bf) the PostgreSQL feature `SELECT ... FOR UPDATE SKIP LOCKED`
=> chore: update delayed_job_active_record

app/assets/stylesheets/shared/quality_metrics.scss, app/webpack/observations/show/components/quality_metrics.jsx, config/locales/en.yml
I’m not fully sure how internationalization works for the project (is this OK to merge as is? or do translations need to be added first / does a process need to be kicked off?), but here’s the requested change. I’ve tested the changes locally and I’ve provided screenshots for what it looks like on my end (please ignore the broken map; I’ve had to comment out the mapnik stuff for my dev env if that is related at all).
Before DQA is available:
After DQA is available:
Note: The current community taxon is NOT a link currently, but it can be updated to link to `/taxa/${taxon.id}` or whatever else if desired. Just let me know if it should be the whole line or just the taxon name
=> show current community taxon under DQA (#3990)
